// helpers_dtor_like (ai) -- cube. 2 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0042ef10  gamemisc  [role:dtor-like] */
undefined FUN_0042ef10(void);

/* 005a9ca0  gamemisc  [role:dtor-like] */
undefined FUN_005a9ca0(void);

