// Helpers (ai) -- cube. 21 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0043f470  gamemisc  [caller-vote] */
undefined FUN_0043f470(void);

/* 00444520  gamemisc  [caller-vote] */
undefined FUN_00444520(void);

/* 00444bf0  gamemisc  [caller-vote] */
undefined FUN_00444bf0(void);

/* 004452a0  gamemisc  [caller-vote] */
undefined FUN_004452a0(void);

/* 00445410  gamemisc  [caller-vote] */
undefined FUN_00445410(void);

/* 004456a0  gamemisc  [caller-vote] */
undefined FUN_004456a0(void);

/* 00446bb0  gamemisc  [caller-vote] */
undefined FUN_00446bb0(void);

/* 00451d70  gamemisc  [caller-vote] */
undefined FUN_00451d70(void);

/* 004594c0  gamemisc  [caller-vote] */
undefined FUN_004594c0(void);

/* 0058ce60  gamemisc  [caller-vote] */
undefined FUN_0058ce60(void);

/* 0058ceb0  gamemisc  [caller-vote] */
undefined FUN_0058ceb0(void);

/* 0058cfe0  gamemisc  [caller-vote] */
undefined FUN_0058cfe0(void);

/* 005957c0  gamemisc  [caller-vote] */
undefined FUN_005957c0(void);

/* 0059ed30  gamemisc  [caller-vote] */
undefined FUN_0059ed30(void);

/* 0059f0a0  gamemisc  [caller-vote] */
undefined FUN_0059f0a0(void);

/* 005a78a0  gamemisc  [caller-vote] */
undefined FUN_005a78a0(void);

/* 005a7a40  gamemisc  [caller-vote] */
undefined FUN_005a7a40(void);

/* 005a7c10  gamemisc  [caller-vote] */
undefined FUN_005a7c10(void);

/* 005a9d40  gamemisc  [caller-vote] */
undefined FUN_005a9d40(void);

/* 005a9e50  gamemisc  [caller-vote] */
undefined FUN_005a9e50(void);

/* 00609480  gamemisc  [caller-vote] */
undefined FUN_00609480(void);

