// helpers_wrapper (world) -- server. 1 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00406ef0  gamemisc  [role:wrapper] */
undefined4 * __fastcall FUN_00406ef0(undefined4 * param_1);

