// Proven_02 (world) -- server. 19 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 005054fa  game  [ledger]  ~dungeon_assembler__split_5054fa */
undefined __stdcall FUN_005054fa(void);

/* 0050702a  game  [ledger]  ~dungeon_assembler__split_50702a */
undefined __stdcall FUN_0050702a(void);

/* 0050998a  game  [ledger]  ~dungeon_assembler__split_50998a */
undefined __stdcall FUN_0050998a(void);

/* 0050e080  game  [ledger]  ~featureGrid */
undefined __thiscall FUN_0050e080(void * this, int param_1, int param_2);

/* 00518630  game  [ledger]  ~zone_builder */
undefined FUN_00518630(void);

/* 00522290  game  [ledger]  ~feature_count_range */
undefined __thiscall FUN_00522290(void * this, undefined4 * param_1, undefined4 * param_2);

/* 00522840  game  [ledger]  ~biome_border */
undefined __thiscall FUN_00522840(void * this, int param_1, int param_2);

/* 00522d80  gamemisc  [ledger]  ~World_terrainOffset2D */
float * __stdcall FUN_00522d80(float * param_1, int param_2, int param_3);

/* 00522e20  gamemisc  [ledger]  ~World_waterProximityInfluence */
undefined __thiscall FUN_00522e20(void * this, int param_1, int param_2);

/* 005234b0  game  [ledger]  ~seg_carve */
undefined __thiscall FUN_005234b0(void * this, int * param_1, int * param_2);

/* 005236d0  game  [ledger]  ~room_carve */
undefined __thiscall FUN_005236d0(void * this, int * param_1, int * param_2, char param_3);

/* 00524540  game  [ledger]  ~creature_spawn_builder */
undefined __thiscall FUN_00524540(void * this, void * param_1, uint * param_2, uint param_3, undefined4 param_4, int param_5, int param_6, char param_7, int * param_8, int param_9);

/* 0052a830  game  [ledger]  ~dungeon_scatter_emitter */
undefined __cdecl FUN_0052a830(void * param_1, uint * param_2, uint param_3, int param_4);

/* 0052c370  game  [ledger]  ~dungeon_decor_emitter */
int * __cdecl FUN_0052c370(int * param_1, undefined4 param_2, int * param_3, int param_4);

/* 0052c820  game  [ledger]  ~World_objectFalloffWeight */
float10 __thiscall FUN_0052c820(uint * param_1, uint * param_2, uint * param_3);

/* 0052cd50  game  [ledger]  ~World_sampleTerrainHeight */
float10 __thiscall FUN_0052cd50(void * param_1, uint param_2, float param_3, int param_4);

/* 0052d990  game  [ledger]  ~World_computeClimateColor */
undefined __thiscall FUN_0052d990(void * this, uint param_1, uint param_2);

/* 0052dee0  gamemisc  [ledger]  ~World_falloffSquared */
float10 __thiscall FUN_0052dee0(uint * param_1, uint * param_2, uint * param_3);

/* 00549c50  game  [ledger]  ~world_create */
undefined __thiscall FUN_00549c50(void * this);

