// Spawn (world) -- server. 2 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004e10c0  game  [rtti] */
void __thiscall ~Spawn(Spawn * this);

/* 004e11d0  game  [rtti] */
undefined4 * __thiscall scalar_deleting_destructor(Spawn * this, byte param_1);

