// helpers_dtor_like (control) -- cube. 21 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004041c0  gamemisc  [role:dtor-like] */
undefined FUN_004041c0(void);

/* 00450e00  gamemisc  [role:dtor-like] */
undefined FUN_00450e00(void);

/* 0046e330  gamemisc  [role:dtor-like] */
undefined FUN_0046e330(void);

/* 004815e0  gamemisc  [role:dtor-like] */
undefined FUN_004815e0(void);

/* 00484230  gamemisc  [role:dtor-like] */
undefined FUN_00484230(void);

/* 004e75c0  gamemisc  [role:dtor-like] */
undefined FUN_004e75c0(void);

/* 005866a0  gamemisc  [role:dtor-like] */
undefined FUN_005866a0(void);

/* 00586730  gamemisc  [role:dtor-like] */
undefined FUN_00586730(void);

/* 00586980  gamemisc  [role:dtor-like] */
undefined FUN_00586980(void);

/* 00586a80  gamemisc  [role:dtor-like] */
undefined FUN_00586a80(void);

/* 00587020  gamemisc  [role:dtor-like] */
undefined FUN_00587020(void);

/* 00587180  gamemisc  [role:dtor-like] */
undefined FUN_00587180(void);

/* 005871f0  gamemisc  [role:dtor-like] */
undefined FUN_005871f0(void);

/* 00587290  gamemisc  [role:dtor-like] */
undefined FUN_00587290(void);

/* 00587350  gamemisc  [role:dtor-like] */
undefined FUN_00587350(void);

/* 00636ad0  gamemisc  [role:dtor-like] */
undefined FUN_00636ad0(void);

/* 00658530  gamemisc  [role:dtor-like] */
undefined FUN_00658530(void);

/* 00661830  gamemisc  [role:dtor-like] */
undefined FUN_00661830(void);

/* 00677d10  gamemisc  [role:dtor-like] */
undefined FUN_00677d10(void);

/* 006fb270  gamemisc  [role:dtor-like] */
undefined FUN_006fb270(void);

/* 006fb2d0  gamemisc  [role:dtor-like] */
undefined FUN_006fb2d0(void);

