// helpers_ctor_like (control) -- cube. 1 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004515f0  gamemisc  [role:ctor-like] */
undefined FUN_004515f0(void);

