// Helpers_02 (control) -- cube. 200 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0049d650  gamemisc  [caller-vote] */
undefined FUN_0049d650(void);

/* 004a19d0  gamemisc  [caller-vote] */
undefined FUN_004a19d0(void);

/* 004a1e50  gamemisc  [caller-vote] */
undefined FUN_004a1e50(void);

/* 004a2780  gamemisc  [caller-vote] */
undefined FUN_004a2780(void);

/* 004a6b50  gamemisc  [caller-vote] */
undefined FUN_004a6b50(void);

/* 004a8f20  gamemisc  [caller-vote] */
undefined FUN_004a8f20(void);

/* 004a8f90  gamemisc  [caller-vote] */
undefined FUN_004a8f90(void);

/* 004a9200  gamemisc  [caller-vote] */
undefined FUN_004a9200(void);

/* 004a9320  gamemisc  [caller-vote] */
undefined FUN_004a9320(void);

/* 004a9520  gamemisc  [caller-vote] */
undefined FUN_004a9520(void);

/* 004a96b0  gamemisc  [caller-vote] */
undefined FUN_004a96b0(void);

/* 004a9a00  gamemisc  [caller-vote] */
undefined FUN_004a9a00(void);

/* 004a9bf0  gamemisc  [caller-vote] */
undefined FUN_004a9bf0(void);

/* 004a9f00  gamemisc  [caller-vote] */
undefined FUN_004a9f00(void);

/* 004aa0d0  gamemisc  [caller-vote] */
undefined FUN_004aa0d0(void);

/* 004aa160  gamemisc  [caller-vote] */
undefined FUN_004aa160(void);

/* 004aa260  gamemisc  [caller-vote] */
undefined FUN_004aa260(void);

/* 004aa580  gamemisc  [caller-vote] */
undefined FUN_004aa580(void);

/* 004aa6c0  gamemisc  [caller-vote] */
undefined FUN_004aa6c0(void);

/* 004aa840  gamemisc  [caller-vote] */
undefined FUN_004aa840(void);

/* 004aa980  gamemisc  [caller-vote] */
undefined FUN_004aa980(void);

/* 004ab190  gamemisc  [caller-vote] */
undefined FUN_004ab190(void);

/* 004ab940  gamemisc  [caller-vote] */
undefined FUN_004ab940(void);

/* 004aba20  gamemisc  [caller-vote] */
undefined FUN_004aba20(void);

/* 004aba70  gamemisc  [caller-vote] */
undefined FUN_004aba70(void);

/* 004abae0  gamemisc  [caller-vote] */
undefined FUN_004abae0(void);

/* 004abb10  gamemisc  [caller-vote] */
undefined FUN_004abb10(void);

/* 004abc10  gamemisc  [caller-vote] */
undefined FUN_004abc10(void);

/* 004abc40  gamemisc  [caller-vote] */
undefined FUN_004abc40(void);

/* 004abc80  gamemisc  [caller-vote] */
undefined FUN_004abc80(void);

/* 004abcc0  gamemisc  [caller-vote] */
undefined FUN_004abcc0(void);

/* 004abe90  gamemisc  [caller-vote] */
undefined FUN_004abe90(void);

/* 004abf80  gamemisc  [caller-vote] */
undefined FUN_004abf80(void);

/* 004ac0a0  gamemisc  [caller-vote] */
undefined FUN_004ac0a0(void);

/* 004ac150  gamemisc  [caller-vote] */
undefined FUN_004ac150(void);

/* 004c1100  gamemisc  [caller-vote] */
undefined FUN_004c1100(void);

/* 004c11f0  gamemisc  [caller-vote] */
undefined FUN_004c11f0(void);

/* 004c14d0  gamemisc  [caller-vote] */
undefined FUN_004c14d0(void);

/* 004c14f0  gamemisc  [caller-vote] */
undefined FUN_004c14f0(void);

/* 004c1a10  gamemisc  [caller-vote] */
undefined FUN_004c1a10(void);

/* 004c1a90  gamemisc  [caller-vote] */
undefined __thiscall FUN_004c1a90(void * this);

/* 004c1bb0  gamemisc  [caller-vote] */
undefined FUN_004c1bb0(void);

/* 004c6140  gamemisc  [caller-vote] */
undefined FUN_004c6140(void);

/* 004c6610  gamemisc  [caller-vote] */
undefined FUN_004c6610(void);

/* 004c69b0  gamemisc  [caller-vote] */
undefined FUN_004c69b0(void);

/* 004c6cc0  gamemisc  [caller-vote] */
undefined FUN_004c6cc0(void);

/* 004c6f20  gamemisc  [caller-vote] */
undefined FUN_004c6f20(void);

/* 004c71c0  gamemisc  [caller-vote] */
undefined FUN_004c71c0(void);

/* 004c79b0  gamemisc  [caller-vote] */
undefined FUN_004c79b0(void);

/* 004c7a90  gamemisc  [caller-vote] */
undefined FUN_004c7a90(void);

/* 004c95a0  gamemisc  [caller-vote] */
undefined FUN_004c95a0(void);

/* 004cc7d0  gamemisc  [caller-vote] */
undefined FUN_004cc7d0(void);

/* 004ce180  gamemisc  [caller-vote] */
undefined FUN_004ce180(void);

/* 004ce660  gamemisc  [caller-vote] */
undefined FUN_004ce660(void);

/* 004cf220  gamemisc  [caller-vote] */
undefined FUN_004cf220(void);

/* 004cf2a0  gamemisc  [caller-vote] */
undefined __thiscall FUN_004cf2a0(void * this);

/* 004cf3c0  gamemisc  [caller-vote] */
undefined FUN_004cf3c0(void);

/* 004d4de0  gamemisc  [caller-vote] */
undefined FUN_004d4de0(void);

/* 004d4f10  gamemisc  [caller-vote] */
undefined FUN_004d4f10(void);

/* 004dc470  gamemisc  [caller-vote] */
undefined FUN_004dc470(void);

/* 004dc4e0  gamemisc  [caller-vote] */
undefined FUN_004dc4e0(void);

/* 004dc5b0  gamemisc  [caller-vote] */
undefined FUN_004dc5b0(void);

/* 004dc750  gamemisc  [caller-vote] */
undefined FUN_004dc750(void);

/* 004dc820  gamemisc  [caller-vote] */
undefined FUN_004dc820(void);

/* 004dc8b0  gamemisc  [caller-vote] */
undefined FUN_004dc8b0(void);

/* 004dd5e0  gamemisc  [caller-vote] */
undefined FUN_004dd5e0(void);

/* 004dd640  gamemisc  [caller-vote] */
undefined FUN_004dd640(void);

/* 004dd6a0  gamemisc  [caller-vote] */
undefined FUN_004dd6a0(void);

/* 004dd700  gamemisc  [caller-vote] */
undefined FUN_004dd700(void);

/* 004dd750  gamemisc  [caller-vote] */
undefined FUN_004dd750(void);

/* 004dfac0  gamemisc  [caller-vote] */
undefined FUN_004dfac0(void);

/* 004e0070  gamemisc  [caller-vote] */
undefined FUN_004e0070(void);

/* 004e0080  gamemisc  [caller-vote] */
undefined FUN_004e0080(void);

/* 004e0300  gamemisc  [caller-vote] */
undefined FUN_004e0300(void);

/* 004e03c0  gamemisc  [caller-vote] */
undefined FUN_004e03c0(void);

/* 004e0440  gamemisc  [caller-vote] */
undefined FUN_004e0440(void);

/* 004e3790  gamemisc  [caller-vote] */
undefined FUN_004e3790(void);

/* 004e42c0  gamemisc  [caller-vote] */
undefined FUN_004e42c0(void);

/* 004e4350  gamemisc  [caller-vote] */
undefined FUN_004e4350(void);

/* 004e4a20  gamemisc  [caller-vote] */
undefined FUN_004e4a20(void);

/* 004e5320  gamemisc  [caller-vote] */
undefined FUN_004e5320(void);

/* 004e5c10  gamemisc  [caller-vote] */
undefined FUN_004e5c10(void);

/* 004e5c90  gamemisc  [caller-vote] */
undefined FUN_004e5c90(void);

/* 004e6530  gamemisc  [caller-vote] */
undefined FUN_004e6530(void);

/* 004e6550  gamemisc  [caller-vote] */
undefined FUN_004e6550(void);

/* 004e6d80  gamemisc  [caller-vote] */
undefined FUN_004e6d80(void);

/* 004e7520  gamemisc  [caller-vote] */
undefined FUN_004e7520(void);

/* 004eb8d0  gamemisc  [caller-vote] */
undefined FUN_004eb8d0(void);

/* 004eba80  gamemisc  [caller-vote] */
undefined FUN_004eba80(void);

/* 004ebb40  gamemisc  [caller-vote] */
undefined FUN_004ebb40(void);

/* 004ebd50  gamemisc  [caller-vote] */
undefined FUN_004ebd50(void);

/* 004ebf80  gamemisc  [caller-vote] */
undefined FUN_004ebf80(void);

/* 004ec1b0  gamemisc  [caller-vote] */
undefined FUN_004ec1b0(void);

/* 004ec1f0  gamemisc  [caller-vote] */
undefined FUN_004ec1f0(void);

/* 0051c310  gamemisc  [caller-vote] */
undefined FUN_0051c310(void);

/* 00583270  gamemisc  [caller-vote] */
undefined FUN_00583270(void);

/* 00583b40  gamemisc  [caller-vote] */
undefined FUN_00583b40(void);

/* 00583f70  gamemisc  [caller-vote] */
undefined FUN_00583f70(void);

/* 00583fc0  gamemisc  [caller-vote] */
undefined FUN_00583fc0(void);

/* 00584010  gamemisc  [caller-vote] */
undefined FUN_00584010(void);

/* 00584060  gamemisc  [caller-vote] */
undefined FUN_00584060(void);

/* 005840b0  gamemisc  [caller-vote] */
undefined FUN_005840b0(void);

/* 00584100  gamemisc  [caller-vote] */
undefined FUN_00584100(void);

/* 00584150  gamemisc  [caller-vote] */
undefined FUN_00584150(void);

/* 005841a0  gamemisc  [caller-vote] */
undefined FUN_005841a0(void);

/* 005841f0  gamemisc  [caller-vote] */
undefined FUN_005841f0(void);

/* 005842d0  gamemisc  [caller-vote] */
undefined FUN_005842d0(void);

/* 00584300  gamemisc  [caller-vote] */
undefined __thiscall FUN_00584300(void * this);

/* 00587660  gamemisc  [caller-vote] */
undefined FUN_00587660(void);

/* 00587f30  gamemisc  [caller-vote] */
undefined FUN_00587f30(void);

/* 00587f70  gamemisc  [caller-vote] */
undefined FUN_00587f70(void);

/* 00588250  gamemisc  [caller-vote] */
undefined FUN_00588250(void);

/* 0058ce20  gamemisc  [caller-vote] */
undefined FUN_0058ce20(void);

/* 0058ce40  gamemisc  [caller-vote] */
undefined FUN_0058ce40(void);

/* 0058dc20  gamemisc  [caller-vote] */
undefined FUN_0058dc20(void);

/* 00593e20  gamemisc  [caller-vote] */
undefined FUN_00593e20(void);

/* 00594620  gamemisc  [caller-vote] */
undefined FUN_00594620(void);

/* 00594840  gamemisc  [caller-vote] */
undefined FUN_00594840(void);

/* 005948d0  gamemisc  [caller-vote] */
undefined FUN_005948d0(void);

/* 00594ad0  gamemisc  [caller-vote] */
undefined FUN_00594ad0(void);

/* 00594bf0  gamemisc  [caller-vote] */
undefined FUN_00594bf0(void);

/* 00595a60  gamemisc  [caller-vote] */
undefined FUN_00595a60(void);

/* 00596d30  gamemisc  [caller-vote] */
undefined FUN_00596d30(void);

/* 005988a0  gamemisc  [caller-vote] */
undefined FUN_005988a0(void);

/* 0059a800  gamemisc  [caller-vote] */
undefined FUN_0059a800(void);

/* 0059aa60  gamemisc  [caller-vote] */
undefined FUN_0059aa60(void);

/* 0059c800  gamemisc  [caller-vote] */
undefined FUN_0059c800(void);

/* 0059cff0  gamemisc  [caller-vote] */
undefined FUN_0059cff0(void);

/* 0059d640  gamemisc  [caller-vote] */
undefined FUN_0059d640(void);

/* 0059f070  gamemisc  [caller-vote] */
undefined FUN_0059f070(void);

/* 0059f850  gamemisc  [caller-vote] */
undefined FUN_0059f850(void);

/* 0059fb90  gamemisc  [caller-vote] */
undefined FUN_0059fb90(void);

/* 0059fea0  gamemisc  [caller-vote] */
undefined FUN_0059fea0(void);

/* 005a03d0  gamemisc  [caller-vote] */
undefined FUN_005a03d0(void);

/* 005a0910  gamemisc  [caller-vote] */
undefined FUN_005a0910(void);

/* 005a0bf0  gamemisc  [caller-vote] */
undefined FUN_005a0bf0(void);

/* 005a0d80  gamemisc  [caller-vote] */
undefined FUN_005a0d80(void);

/* 005a35d0  gamemisc  [caller-vote] */
undefined FUN_005a35d0(void);

/* 005a58e0  gamemisc  [caller-vote] */
undefined FUN_005a58e0(void);

/* 005a5a60  gamemisc  [caller-vote] */
undefined FUN_005a5a60(void);

/* 005a5cb0  gamemisc  [caller-vote] */
undefined FUN_005a5cb0(void);

/* 005a6270  gamemisc  [caller-vote] */
undefined FUN_005a6270(void);

/* 005a6ab0  gamemisc  [caller-vote] */
undefined FUN_005a6ab0(void);

/* 005a6ba0  gamemisc  [caller-vote] */
undefined FUN_005a6ba0(void);

/* 005a6c60  gamemisc  [caller-vote] */
undefined FUN_005a6c60(void);

/* 005a6ce0  gamemisc  [caller-vote] */
undefined FUN_005a6ce0(void);

/* 005a6da0  gamemisc  [caller-vote] */
undefined FUN_005a6da0(void);

/* 005a7290  gamemisc  [caller-vote] */
undefined FUN_005a7290(void);

/* 005a7520  gamemisc  [caller-vote] */
undefined FUN_005a7520(void);

/* 005a7900  gamemisc  [caller-vote] */
undefined FUN_005a7900(void);

/* 005a7b50  gamemisc  [caller-vote] */
undefined FUN_005a7b50(void);

/* 005a7b90  gamemisc  [caller-vote] */
undefined FUN_005a7b90(void);

/* 005a7e60  gamemisc  [caller-vote] */
undefined FUN_005a7e60(void);

/* 005a7eb0  gamemisc  [caller-vote] */
undefined FUN_005a7eb0(void);

/* 005ae9a0  gamemisc  [caller-vote] */
undefined FUN_005ae9a0(void);

/* 005c0420  gamemisc  [caller-vote] */
undefined FUN_005c0420(void);

/* 005c0630  gamemisc  [caller-vote] */
undefined FUN_005c0630(void);

/* 005c0b10  gamemisc  [caller-vote] */
undefined FUN_005c0b10(void);

/* 005c1690  gamemisc  [caller-vote] */
undefined FUN_005c1690(void);

/* 005c21f0  gamemisc  [caller-vote] */
undefined FUN_005c21f0(void);

/* 005c2630  gamemisc  [caller-vote] */
undefined FUN_005c2630(void);

/* 005c29a0  gamemisc  [caller-vote] */
undefined FUN_005c29a0(void);

/* 005c3360  gamemisc  [caller-vote] */
undefined FUN_005c3360(void);

/* 005cb0d0  gamemisc  [caller-vote] */
undefined FUN_005cb0d0(void);

/* 005d8750  gamemisc  [caller-vote] */
undefined FUN_005d8750(void);

/* 005d9ad0  gamemisc  [caller-vote] */
undefined FUN_005d9ad0(void);

/* 005ee7a0  gamemisc  [caller-vote] */
undefined FUN_005ee7a0(void);

/* 005f0720  gamemisc  [caller-vote] */
undefined FUN_005f0720(void);

/* 005f0c80  gamemisc  [caller-vote] */
undefined FUN_005f0c80(void);

/* 005f7400  gamemisc  [caller-vote] */
undefined FUN_005f7400(void);

/* 005f7820  gamemisc  [caller-vote] */
undefined FUN_005f7820(void);

/* 005fa500  gamemisc  [caller-vote] */
undefined FUN_005fa500(void);

/* 005fa5b0  gamemisc  [caller-vote] */
undefined FUN_005fa5b0(void);

/* 005fa650  gamemisc  [caller-vote] */
undefined FUN_005fa650(void);

/* 005fa750  gamemisc  [caller-vote] */
undefined FUN_005fa750(void);

/* 005fa9e0  gamemisc  [caller-vote] */
undefined FUN_005fa9e0(void);

/* 005faad0  gamemisc  [caller-vote] */
undefined FUN_005faad0(void);

/* 005fab40  gamemisc  [caller-vote] */
undefined FUN_005fab40(void);

/* 005fc0d0  gamemisc  [caller-vote] */
undefined FUN_005fc0d0(void);

/* 005fc160  gamemisc  [caller-vote] */
undefined FUN_005fc160(void);

/* 00601cc0  gamemisc  [caller-vote] */
undefined FUN_00601cc0(void);

/* 00601eb0  gamemisc  [caller-vote] */
undefined FUN_00601eb0(void);

/* 00601f00  gamemisc  [caller-vote] */
undefined FUN_00601f00(void);

/* 00608a60  gamemisc  [caller-vote] */
undefined FUN_00608a60(void);

/* 00608a90  gamemisc  [caller-vote] */
undefined FUN_00608a90(void);

/* 00608b30  gamemisc  [caller-vote] */
undefined FUN_00608b30(void);

/* 00608ba0  gamemisc  [caller-vote] */
undefined FUN_00608ba0(void);

/* 00608c20  gamemisc  [caller-vote] */
undefined FUN_00608c20(void);

/* 00608c80  gamemisc  [caller-vote] */
undefined FUN_00608c80(void);

/* 00608d40  gamemisc  [caller-vote] */
undefined FUN_00608d40(void);

/* 00608db0  gamemisc  [caller-vote] */
undefined FUN_00608db0(void);

/* 00608e80  gamemisc  [caller-vote] */
undefined FUN_00608e80(void);

/* 00608f20  gamemisc  [caller-vote] */
undefined FUN_00608f20(void);

/* 00608f40  gamemisc  [caller-vote] */
undefined FUN_00608f40(void);

/* 00608f60  gamemisc  [caller-vote] */
undefined FUN_00608f60(void);

/* 00608ff0  gamemisc  [caller-vote] */
undefined FUN_00608ff0(void);

/* 00609080  gamemisc  [caller-vote] */
undefined FUN_00609080(void);

/* 006091a0  gamemisc  [caller-vote] */
undefined FUN_006091a0(void);

/* 006091b0  gamemisc  [caller-vote] */
undefined FUN_006091b0(void);

/* 006091d0  gamemisc  [caller-vote] */
undefined FUN_006091d0(void);

