// helpers_wrapper (control) -- cube. 30 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00403eb0  gamemisc  [role:wrapper] */
undefined FUN_00403eb0(void);

/* 00412220  gamemisc  [role:wrapper] */
undefined FUN_00412220(void);

/* 004122e0  gamemisc  [role:wrapper] */
undefined FUN_004122e0(void);

/* 00423ee0  gamemisc  [role:wrapper] */
undefined FUN_00423ee0(void);

/* 004240f0  gamemisc  [role:wrapper] */
undefined FUN_004240f0(void);

/* 0042b810  gamemisc  [role:wrapper] */
undefined FUN_0042b810(void);

/* 0042b860  gamemisc  [role:wrapper] */
undefined FUN_0042b860(void);

/* 0042b8b0  gamemisc  [role:wrapper] */
undefined FUN_0042b8b0(void);

/* 0042b910  gamemisc  [role:wrapper] */
undefined FUN_0042b910(void);

/* 0042b950  gamemisc  [role:wrapper] */
undefined FUN_0042b950(void);

/* 0042b990  gamemisc  [role:wrapper] */
undefined FUN_0042b990(void);

/* 0042b9e0  gamemisc  [role:wrapper] */
undefined FUN_0042b9e0(void);

/* 0042ba20  gamemisc  [role:wrapper] */
undefined FUN_0042ba20(void);

/* 0042ba60  gamemisc  [role:wrapper] */
undefined FUN_0042ba60(void);

/* 0042bab0  gamemisc  [role:wrapper] */
undefined FUN_0042bab0(void);

/* 0043a450  gamemisc  [role:wrapper] */
undefined FUN_0043a450(void);

/* 0043ab30  gamemisc  [role:wrapper] */
undefined FUN_0043ab30(void);

/* 00444860  gamemisc  [role:wrapper] */
undefined FUN_00444860(void);

/* 00459530  gamemisc  [role:wrapper] */
undefined FUN_00459530(void);

/* 004860b0  gamemisc  [role:wrapper] */
undefined FUN_004860b0(void);

/* 00486240  gamemisc  [role:wrapper] */
undefined FUN_00486240(void);

/* 004864c0  gamemisc  [role:wrapper] */
undefined FUN_004864c0(void);

/* 004d4650  gamemisc  [role:wrapper] */
undefined FUN_004d4650(void);

/* 004da480  gamemisc  [role:wrapper] */
undefined FUN_004da480(void);

/* 00585840  gamemisc  [role:wrapper] */
undefined FUN_00585840(void);

/* 00585880  gamemisc  [role:wrapper] */
undefined FUN_00585880(void);

/* 0062f660  gamemisc  [role:wrapper] */
undefined FUN_0062f660(void);

/* 0062f8c0  gamemisc  [role:wrapper] */
undefined FUN_0062f8c0(void);

/* 006502e0  gamemisc  [role:wrapper] */
undefined FUN_006502e0(void);

/* 0067e480  gamemisc  [role:wrapper] */
undefined FUN_0067e480(void);

