// Unsorted (control) -- cube. 183 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00403350  gamemisc  [logic:caller-vote] */
undefined FUN_00403350(void);

/* 00405060  gamemisc  [logic:caller-vote] */
undefined FUN_00405060(void);

/* 00408fc0  gamemisc  [logic:caller-vote] */
undefined FUN_00408fc0(void);

/* 0040c380  gamemisc  [logic:caller-vote] */
undefined FUN_0040c380(void);

/* 0040c520  gamemisc  [logic:caller-vote] */
undefined FUN_0040c520(void);

/* 0040cba0  gamemisc  [logic:caller-vote] */
undefined FUN_0040cba0(void);

/* 0040ea50  gamemisc  [logic:caller-vote] */
undefined FUN_0040ea50(void);

/* 0040ea70  gamemisc  [logic:caller-vote] */
undefined FUN_0040ea70(void);

/* 0040eac0  gamemisc  [logic:caller-vote] */
undefined FUN_0040eac0(void);

/* 0040eb60  gamemisc  [logic:caller-vote] */
undefined FUN_0040eb60(void);

/* 0040f570  gamemisc  [logic:caller-vote] */
undefined FUN_0040f570(void);

/* 0040f7a0  gamemisc  [logic:caller-vote] */
undefined FUN_0040f7a0(void);

/* 00412080  gamemisc  [logic:caller-vote] */
undefined FUN_00412080(void);

/* 004120f0  gamemisc  [logic:caller-vote] */
undefined FUN_004120f0(void);

/* 00412200  gamemisc  [logic:caller-vote] */
undefined FUN_00412200(void);

/* 00412280  gamemisc  [logic:caller-vote] */
undefined FUN_00412280(void);

/* 004122c0  gamemisc  [logic:caller-vote] */
undefined FUN_004122c0(void);

/* 00412350  gamemisc  [logic:caller-vote] */
undefined FUN_00412350(void);

/* 00412780  gamemisc  [logic:caller-vote] */
undefined FUN_00412780(void);

/* 00412850  gamemisc  [logic:caller-vote] */
undefined FUN_00412850(void);

/* 00424830  gamemisc  [logic:caller-vote] */
undefined FUN_00424830(void);

/* 00424860  gamemisc  [logic:caller-vote] */
undefined FUN_00424860(void);

/* 004248a0  gamemisc  [logic:caller-vote] */
undefined FUN_004248a0(void);

/* 00424990  gamemisc  [logic:caller-vote] */
undefined FUN_00424990(void);

/* 00424da0  gamemisc  [logic:caller-vote] */
undefined FUN_00424da0(void);

/* 004252f0  gamemisc  [logic:caller-vote] */
undefined FUN_004252f0(void);

/* 00425330  gamemisc  [logic:caller-vote] */
undefined FUN_00425330(void);

/* 00425390  gamemisc  [logic:caller-vote] */
undefined FUN_00425390(void);

/* 00428750  gamemisc  [logic:caller-vote] */
undefined FUN_00428750(void);

/* 00428920  gamemisc  [logic:caller-vote] */
undefined FUN_00428920(void);

/* 00428db0  gamemisc  [logic:caller-vote] */
undefined FUN_00428db0(void);

/* 0042bd90  gamemisc  [logic:caller-vote] */
undefined FUN_0042bd90(void);

/* 0042c080  gamemisc  [logic:caller-vote] */
undefined FUN_0042c080(void);

/* 0042c460  gamemisc  [logic:caller-vote] */
undefined FUN_0042c460(void);

/* 0042c520  gamemisc  [logic:caller-vote] */
undefined FUN_0042c520(void);

/* 0042c5b0  gamemisc  [logic:caller-vote] */
undefined FUN_0042c5b0(void);

/* 0042c5e0  gamemisc  [logic:caller-vote] */
undefined FUN_0042c5e0(void);

/* 0042c7a0  gamemisc  [logic:caller-vote] */
undefined FUN_0042c7a0(void);

/* 0042c800  gamemisc  [logic:caller-vote] */
undefined FUN_0042c800(void);

/* 0042c8d0  gamemisc  [logic:caller-vote] */
undefined FUN_0042c8d0(void);

/* 0042ca00  gamemisc  [logic:caller-vote] */
undefined FUN_0042ca00(void);

/* 0042f470  gamemisc  [logic:caller-vote] */
undefined FUN_0042f470(void);

/* 0042f640  gamemisc  [logic:caller-vote] */
undefined FUN_0042f640(void);

/* 0042f860  gamemisc  [logic:caller-vote] */
undefined FUN_0042f860(void);

/* 004391d0  gamemisc  [logic:caller-vote] */
undefined FUN_004391d0(void);

/* 0043abc0  gamemisc  [logic:caller-vote] */
undefined FUN_0043abc0(void);

/* 0043abf0  gamemisc  [logic:caller-vote] */
undefined FUN_0043abf0(void);

/* 0043ac20  gamemisc  [logic:caller-vote] */
undefined FUN_0043ac20(void);

/* 0043b610  gamemisc  [logic:caller-vote] */
undefined FUN_0043b610(void);

/* 0043e350  gamemisc  [logic:caller-vote] */
undefined FUN_0043e350(void);

/* 0043e4a0  gamemisc  [logic:caller-vote] */
undefined FUN_0043e4a0(void);

/* 0043e550  gamemisc  [logic:caller-vote] */
undefined FUN_0043e550(void);

/* 0043e5a0  gamemisc  [logic:caller-vote] */
undefined FUN_0043e5a0(void);

/* 0043f040  gamemisc  [logic:caller-vote] */
undefined FUN_0043f040(void);

/* 0043f100  gamemisc  [logic:caller-vote] */
undefined FUN_0043f100(void);

/* 0043f720  gamemisc  [logic:caller-vote] */
undefined FUN_0043f720(void);

/* 0043f7c0  gamemisc  [logic:caller-vote] */
undefined FUN_0043f7c0(void);

/* 00444230  gamemisc  [logic:caller-vote] */
undefined FUN_00444230(void);

/* 004445d0  gamemisc  [logic:caller-vote] */
undefined FUN_004445d0(void);

/* 00444610  gamemisc  [logic:caller-vote] */
undefined FUN_00444610(void);

/* 00444650  gamemisc  [logic:caller-vote] */
undefined FUN_00444650(void);

/* 00444680  gamemisc  [logic:caller-vote] */
undefined FUN_00444680(void);

/* 00444820  gamemisc  [logic:caller-vote] */
undefined FUN_00444820(void);

/* 00444a90  gamemisc  [logic:caller-vote] */
undefined FUN_00444a90(void);

/* 00445ff0  gamemisc  [logic:caller-vote] */
undefined FUN_00445ff0(void);

/* 00447700  gamemisc  [logic:caller-vote] */
undefined FUN_00447700(void);

/* 004478b0  gamemisc  [logic:caller-vote] */
undefined FUN_004478b0(void);

/* 00449720  gamemisc  [logic:caller-vote] */
undefined FUN_00449720(void);

/* 00449920  gamemisc  [logic:caller-vote] */
undefined FUN_00449920(void);

/* 0044a3c0  gamemisc  [logic:caller-vote] */
undefined FUN_0044a3c0(void);

/* 0044a410  gamemisc  [logic:caller-vote] */
undefined FUN_0044a410(void);

/* 0044a4b0  gamemisc  [logic:caller-vote] */
undefined FUN_0044a4b0(void);

/* 0044a500  gamemisc  [logic:caller-vote] */
undefined FUN_0044a500(void);

/* 0044a7c0  gamemisc  [logic:caller-vote] */
undefined FUN_0044a7c0(void);

/* 0044aa20  gamemisc  [logic:caller-vote] */
undefined FUN_0044aa20(void);

/* 0044ad30  gamemisc  [logic:caller-vote] */
undefined FUN_0044ad30(void);

/* 0044b580  gamemisc  [logic:caller-vote] */
undefined FUN_0044b580(void);

/* 0044b5f0  gamemisc  [logic:caller-vote] */
undefined FUN_0044b5f0(void);

/* 0044bcc0  gamemisc  [logic:caller-vote] */
undefined FUN_0044bcc0(void);

/* 0044d660  gamemisc  [logic:caller-vote] */
undefined FUN_0044d660(void);

/* 00450960  gamemisc  [logic:caller-vote] */
undefined FUN_00450960(void);

/* 004511e0  gamemisc  [logic:caller-vote] */
undefined FUN_004511e0(void);

/* 00451510  gamemisc  [logic:caller-vote] */
undefined FUN_00451510(void);

/* 00451940  gamemisc  [logic:caller-vote] */
undefined FUN_00451940(void);

/* 00453040  gamemisc  [logic:caller-vote] */
undefined FUN_00453040(void);

/* 00453420  gamemisc  [logic:caller-vote] */
undefined FUN_00453420(void);

/* 00454190  gamemisc  [logic:caller-vote] */
undefined FUN_00454190(void);

/* 00454260  gamemisc  [logic:caller-vote] */
undefined FUN_00454260(void);

/* 00454b50  gamemisc  [logic:caller-vote] */
undefined FUN_00454b50(void);

/* 004551b0  gamemisc  [logic:caller-vote] */
undefined FUN_004551b0(void);

/* 00455340  gamemisc  [logic:caller-vote] */
undefined FUN_00455340(void);

/* 004553c0  gamemisc  [logic:caller-vote] */
undefined FUN_004553c0(void);

/* 004556b0  gamemisc  [logic:caller-vote] */
undefined FUN_004556b0(void);

/* 00455860  gamemisc  [logic:caller-vote] */
undefined FUN_00455860(void);

/* 00455c30  gamemisc  [logic:caller-vote] */
undefined FUN_00455c30(void);

/* 00455fb0  gamemisc  [logic:caller-vote] */
undefined FUN_00455fb0(void);

/* 00456160  gamemisc  [logic:caller-vote] */
undefined FUN_00456160(void);

/* 00456c30  gamemisc  [logic:caller-vote] */
undefined FUN_00456c30(void);

/* 00456dc0  gamemisc  [logic:caller-vote] */
undefined FUN_00456dc0(void);

/* 00456f70  gamemisc  [logic:caller-vote] */
undefined FUN_00456f70(void);

/* 004592f0  gamemisc  [logic:caller-vote] */
undefined FUN_004592f0(void);

/* 00459800  gamemisc  [logic:caller-vote] */
undefined FUN_00459800(void);

/* 00466650  gamemisc  [logic:caller-vote] */
undefined FUN_00466650(void);

/* 00468000  gamemisc  [logic:caller-vote] */
undefined FUN_00468000(void);

/* 00468840  gamemisc  [logic:caller-vote] */
undefined FUN_00468840(void);

/* 00468910  gamemisc  [logic:caller-vote] */
undefined FUN_00468910(void);

/* 00468ad0  gamemisc  [logic:caller-vote] */
undefined FUN_00468ad0(void);

/* 00468d30  gamemisc  [logic:caller-vote] */
undefined FUN_00468d30(void);

/* 00468dd0  gamemisc  [logic:caller-vote] */
undefined FUN_00468dd0(void);

/* 00468df0  gamemisc  [logic:caller-vote] */
undefined FUN_00468df0(void);

/* 0046d590  gamemisc  [logic:caller-vote] */
undefined FUN_0046d590(void);

/* 0046d5d0  gamemisc  [logic:caller-vote] */
undefined FUN_0046d5d0(void);

/* 0046d650  gamemisc  [logic:caller-vote] */
undefined FUN_0046d650(void);

/* 0046dd40  gamemisc  [logic:caller-vote] */
undefined FUN_0046dd40(void);

/* 0046e710  gamemisc  [logic:caller-vote] */
undefined FUN_0046e710(void);

/* 0046ef60  gamemisc  [logic:caller-vote] */
undefined FUN_0046ef60(void);

/* 0046f050  gamemisc  [logic:caller-vote] */
undefined FUN_0046f050(void);

/* 0046f390  gamemisc  [logic:caller-vote] */
undefined FUN_0046f390(void);

/* 004718b0  gamemisc  [logic:caller-vote] */
undefined FUN_004718b0(void);

/* 004772b0  gamemisc  [logic:caller-vote] */
undefined FUN_004772b0(void);

/* 004777f0  gamemisc  [logic:caller-vote] */
undefined FUN_004777f0(void);

/* 004778b0  gamemisc  [logic:caller-vote] */
undefined FUN_004778b0(void);

/* 00477d90  gamemisc  [logic:caller-vote] */
undefined FUN_00477d90(void);

/* 0047f9f0  gamemisc  [logic:caller-vote] */
undefined FUN_0047f9f0(void);

/* 0047fa30  gamemisc  [logic:caller-vote] */
undefined FUN_0047fa30(void);

/* 0047fae0  gamemisc  [logic:caller-vote] */
undefined FUN_0047fae0(void);

/* 00484350  gamemisc  [logic:caller-vote] */
undefined FUN_00484350(void);

/* 00486600  gamemisc  [logic:caller-vote] */
undefined FUN_00486600(void);

/* 004878a0  gamemisc  [logic:caller-vote] */
undefined __thiscall FUN_004878a0(void * this);

/* 004a14c0  gamemisc  [logic:caller-vote] */
undefined FUN_004a14c0(void);

/* 004a19d0  gamemisc  [logic:caller-vote] */
undefined FUN_004a19d0(void);

/* 004a2300  gamemisc  [logic:caller-vote] */
undefined FUN_004a2300(void);

/* 004a23d0  gamemisc  [logic:caller-vote] */
undefined FUN_004a23d0(void);

/* 004a2870  gamemisc  [logic:caller-vote] */
undefined FUN_004a2870(void);

/* 004ab8b0  gamemisc  [logic:caller-vote] */
undefined FUN_004ab8b0(void);

/* 004c6350  gamemisc  [logic:caller-vote] */
undefined FUN_004c6350(void);

/* 004c64c0  gamemisc  [logic:caller-vote] */
undefined FUN_004c64c0(void);

/* 004c7c00  gamemisc  [logic:caller-vote] */
undefined FUN_004c7c00(void);

/* 004ccbf0  gamemisc  [logic:caller-vote] */
undefined FUN_004ccbf0(void);

/* 004cef80  gamemisc  [logic:caller-vote] */
undefined FUN_004cef80(void);

/* 004e6d80  gamemisc  [logic:caller-vote] */
undefined FUN_004e6d80(void);

/* 004e7520  gamemisc  [logic:caller-vote] */
undefined FUN_004e7520(void);

/* 004e7870  gamemisc  [logic:caller-vote] */
undefined FUN_004e7870(void);

/* 004eb8d0  gamemisc  [logic:caller-vote] */
undefined FUN_004eb8d0(void);

/* 00584eb0  gamemisc  [logic:caller-vote] */
undefined FUN_00584eb0(void);

/* 00584fb0  gamemisc  [logic:caller-vote] */
undefined FUN_00584fb0(void);

/* 005856b0  gamemisc  [logic:caller-vote] */
undefined FUN_005856b0(void);

/* 005868a0  gamemisc  [logic:caller-vote] */
undefined FUN_005868a0(void);

/* 0058dc20  gamemisc  [logic:caller-vote] */
undefined FUN_0058dc20(void);

/* 00596ca0  gamemisc  [logic:caller-vote] */
undefined FUN_00596ca0(void);

/* 0059ee90  gamemisc  [logic:caller-vote] */
undefined FUN_0059ee90(void);

/* 005a0ed0  gamemisc  [logic:caller-vote] */
undefined FUN_005a0ed0(void);

/* 005a6a70  gamemisc  [logic:caller-vote] */
undefined FUN_005a6a70(void);

/* 005a6e60  gamemisc  [logic:caller-vote] */
undefined FUN_005a6e60(void);

/* 005c0350  gamemisc  [logic:caller-vote] */
undefined FUN_005c0350(void);

/* 005c1060  gamemisc  [logic:caller-vote] */
undefined FUN_005c1060(void);

/* 005c14e0  gamemisc  [logic:caller-vote] */
undefined FUN_005c14e0(void);

/* 005c1690  gamemisc  [logic:caller-vote] */
undefined FUN_005c1690(void);

/* 005c1ef0  gamemisc  [logic:caller-vote] */
undefined FUN_005c1ef0(void);

/* 005c21f0  gamemisc  [logic:caller-vote] */
undefined FUN_005c21f0(void);

/* 005c3d60  gamemisc  [logic:caller-vote] */
undefined FUN_005c3d60(void);

/* 005cade0  gamemisc  [logic:caller-vote] */
undefined FUN_005cade0(void);

/* 005fbc10  gamemisc  [logic:caller-vote] */
undefined FUN_005fbc10(void);

/* 005fc0d0  gamemisc  [logic:caller-vote] */
undefined FUN_005fc0d0(void);

/* 00602440  gamemisc  [logic:caller-vote] */
undefined FUN_00602440(void);

/* 006089c0  gamemisc  [logic:caller-vote] */
undefined FUN_006089c0(void);

/* 0062f690  gamemisc  [logic:caller-vote] */
undefined FUN_0062f690(void);

/* 0062f9b0  gamemisc  [logic:caller-vote] */
undefined FUN_0062f9b0(void);

/* 0062fdc0  gamemisc  [logic:caller-vote] */
undefined FUN_0062fdc0(void);

/* 0062ffb0  gamemisc  [logic:caller-vote] */
undefined FUN_0062ffb0(void);

/* 00630a10  gamemisc  [logic:caller-vote] */
undefined FUN_00630a10(void);

/* 00633d70  gamemisc  [logic:caller-vote] */
undefined FUN_00633d70(void);

/* 00636040  gamemisc  [logic:caller-vote] */
undefined FUN_00636040(void);

/* 00636b70  gamemisc  [logic:caller-vote] */
undefined FUN_00636b70(void);

/* 00638db0  gamemisc  [logic:caller-vote] */
undefined FUN_00638db0(void);

/* 0064b540  gamemisc  [logic:caller-vote] */
undefined FUN_0064b540(void);

/* 006504e0  gamemisc  [logic:caller-vote] */
undefined FUN_006504e0(void);

/* 006612f0  gamemisc  [logic:caller-vote] */
undefined FUN_006612f0(void);

/* 00677b00  gamemisc  [logic:caller-vote] */
undefined FUN_00677b00(void);

/* 006819e0  gamemisc  [logic:caller-vote] */
undefined FUN_006819e0(void);

/* 0068d910  gamemisc  [logic:caller-vote] */
undefined FUN_0068d910(void);

/* 0068d946  gamemisc  [logic:caller-vote] */
undefined FUN_0068d946(void);

/* 0068da90  gamemisc  [logic:caller-vote] */
undefined __allmul(void);

