// Unsorted (control) -- cube. 76 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00403350  gamemisc  [logic:caller-vote] */
undefined FUN_00403350(void);

/* 0040ea50  gamemisc  [logic:caller-vote] */
undefined FUN_0040ea50(void);

/* 0040ea70  gamemisc  [logic:caller-vote] */
undefined FUN_0040ea70(void);

/* 0040f570  gamemisc  [logic:caller-vote] */
undefined FUN_0040f570(void);

/* 0040f7a0  gamemisc  [logic:caller-vote] */
undefined FUN_0040f7a0(void);

/* 004120c0  gamemisc  [logic:caller-vote] */
undefined FUN_004120c0(void);

/* 004120f0  gamemisc  [logic:caller-vote] */
undefined FUN_004120f0(void);

/* 00412280  gamemisc  [logic:caller-vote] */
undefined FUN_00412280(void);

/* 00412780  gamemisc  [logic:caller-vote] */
undefined FUN_00412780(void);

/* 00412850  gamemisc  [logic:caller-vote] */
undefined FUN_00412850(void);

/* 00424830  gamemisc  [logic:caller-vote] */
undefined FUN_00424830(void);

/* 00424860  gamemisc  [logic:caller-vote] */
undefined FUN_00424860(void);

/* 004248a0  gamemisc  [logic:caller-vote] */
undefined FUN_004248a0(void);

/* 00424990  gamemisc  [logic:caller-vote] */
undefined FUN_00424990(void);

/* 004252f0  gamemisc  [logic:caller-vote] */
undefined FUN_004252f0(void);

/* 00428920  gamemisc  [logic:caller-vote] */
undefined FUN_00428920(void);

/* 00428db0  gamemisc  [logic:caller-vote] */
undefined FUN_00428db0(void);

/* 0042c5e0  gamemisc  [logic:caller-vote] */
undefined FUN_0042c5e0(void);

/* 0042c7a0  gamemisc  [logic:caller-vote] */
undefined FUN_0042c7a0(void);

/* 0042ca00  gamemisc  [logic:caller-vote] */
undefined FUN_0042ca00(void);

/* 0042f470  gamemisc  [logic:caller-vote] */
undefined FUN_0042f470(void);

/* 0042f640  gamemisc  [logic:caller-vote] */
undefined FUN_0042f640(void);

/* 0043abf0  gamemisc  [logic:caller-vote] */
undefined FUN_0043abf0(void);

/* 0043ac20  gamemisc  [logic:caller-vote] */
undefined FUN_0043ac20(void);

/* 0043e4a0  gamemisc  [logic:caller-vote] */
undefined FUN_0043e4a0(void);

/* 00444230  gamemisc  [logic:caller-vote] */
undefined FUN_00444230(void);

/* 004445d0  gamemisc  [logic:caller-vote] */
undefined FUN_004445d0(void);

/* 00444610  gamemisc  [logic:caller-vote] */
undefined FUN_00444610(void);

/* 00444650  gamemisc  [logic:caller-vote] */
undefined FUN_00444650(void);

/* 0044b580  gamemisc  [logic:caller-vote] */
undefined FUN_0044b580(void);

/* 00450960  gamemisc  [logic:caller-vote] */
undefined FUN_00450960(void);

/* 00451510  gamemisc  [logic:caller-vote] */
undefined FUN_00451510(void);

/* 00454190  gamemisc  [logic:caller-vote] */
undefined FUN_00454190(void);

/* 00454260  gamemisc  [logic:caller-vote] */
undefined FUN_00454260(void);

/* 00455340  gamemisc  [logic:caller-vote] */
undefined FUN_00455340(void);

/* 00459800  gamemisc  [logic:caller-vote] */
undefined FUN_00459800(void);

/* 00468000  gamemisc  [logic:caller-vote] */
undefined FUN_00468000(void);

/* 00468840  gamemisc  [logic:caller-vote] */
undefined FUN_00468840(void);

/* 00468910  gamemisc  [logic:caller-vote] */
undefined FUN_00468910(void);

/* 00468ad0  gamemisc  [logic:caller-vote] */
undefined FUN_00468ad0(void);

/* 00468d30  gamemisc  [logic:caller-vote] */
undefined FUN_00468d30(void);

/* 00468df0  gamemisc  [logic:caller-vote] */
undefined FUN_00468df0(void);

/* 0046d590  gamemisc  [logic:caller-vote] */
undefined FUN_0046d590(void);

/* 0046d5d0  gamemisc  [logic:caller-vote] */
undefined FUN_0046d5d0(void);

/* 0046d650  gamemisc  [logic:caller-vote] */
undefined FUN_0046d650(void);

/* 004777f0  gamemisc  [logic:caller-vote] */
undefined FUN_004777f0(void);

/* 00484350  gamemisc  [logic:caller-vote] */
undefined FUN_00484350(void);

/* 004878a0  gamemisc  [logic:caller-vote] */
undefined __thiscall FUN_004878a0(void * this);

/* 004a14c0  gamemisc  [logic:caller-vote] */
undefined FUN_004a14c0(void);

/* 004a2870  gamemisc  [logic:caller-vote] */
undefined FUN_004a2870(void);

/* 004ab8b0  gamemisc  [logic:caller-vote] */
undefined FUN_004ab8b0(void);

/* 004c7250  gamemisc  [logic:caller-vote] */
undefined FUN_004c7250(void);

/* 004ccbf0  gamemisc  [logic:caller-vote] */
undefined FUN_004ccbf0(void);

/* 004e7870  gamemisc  [logic:caller-vote] */
undefined FUN_004e7870(void);

/* 00596ca0  gamemisc  [logic:caller-vote] */
undefined FUN_00596ca0(void);

/* 0059ee90  gamemisc  [logic:caller-vote] */
undefined FUN_0059ee90(void);

/* 005a6a00  gamemisc  [logic:caller-vote] */
undefined FUN_005a6a00(void);

/* 005a6a70  gamemisc  [logic:caller-vote] */
undefined FUN_005a6a70(void);

/* 005a6e60  gamemisc  [logic:caller-vote] */
undefined FUN_005a6e60(void);

/* 005c0350  gamemisc  [logic:caller-vote] */
undefined FUN_005c0350(void);

/* 005c1060  gamemisc  [logic:caller-vote] */
undefined FUN_005c1060(void);

/* 005c14e0  gamemisc  [logic:caller-vote] */
undefined FUN_005c14e0(void);

/* 005c1ef0  gamemisc  [logic:caller-vote] */
undefined FUN_005c1ef0(void);

/* 005c3d60  gamemisc  [logic:caller-vote] */
undefined FUN_005c3d60(void);

/* 005cade0  gamemisc  [logic:caller-vote] */
undefined FUN_005cade0(void);

/* 005fbc10  gamemisc  [logic:caller-vote] */
undefined FUN_005fbc10(void);

/* 00602440  gamemisc  [logic:caller-vote] */
undefined FUN_00602440(void);

/* 006089c0  gamemisc  [logic:caller-vote] */
undefined FUN_006089c0(void);

/* 0062f690  gamemisc  [logic:caller-vote] */
undefined FUN_0062f690(void);

/* 0062fdc0  gamemisc  [logic:caller-vote] */
undefined FUN_0062fdc0(void);

/* 00633d70  gamemisc  [logic:caller-vote] */
undefined FUN_00633d70(void);

/* 00636040  gamemisc  [logic:caller-vote] */
undefined FUN_00636040(void);

/* 00636b70  gamemisc  [logic:caller-vote] */
undefined FUN_00636b70(void);

/* 0064b540  gamemisc  [logic:caller-vote] */
undefined FUN_0064b540(void);

/* 006504e0  gamemisc  [logic:caller-vote] */
undefined FUN_006504e0(void);

/* 0068da90  gamemisc  [logic:caller-vote] */
undefined __allmul(void);

