// CubeShader (render) -- cube. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00447c20  game  [rtti] */
CubeShader * __thiscall CubeShader(CubeShader * this, undefined4 param_1);

/* 00447c70  game  [rtti] */
void __thiscall ~CubeShader(CubeShader * this);

/* 00447ce0  game  [rtti] */
CubeShader * __thiscall deleting_destructor(CubeShader * this, byte param_1);

