// Helpers (render) -- cube. 1 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004c7830  gamemisc  [caller-vote] */
undefined FUN_004c7830(void);

