// Proven (render) -- cube. 10 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00424610  game  [ledger]  ~mat4_rotateZ */
undefined FUN_00424610(void);

/* 00424730  game  [ledger]  ~mat4_scaleAxes */
undefined FUN_00424730(void);

/* 00424a60  game  [ledger]  ~mat4_translate */
undefined FUN_00424a60(void);

/* 0042c4a0  gamemisc  [ledger]  ~vec3i64_toFloat */
undefined FUN_0042c4a0(void);

/* 004c85f0  game  [ledger]  ~App_render_frame */
undefined FUN_004c85f0(void);

/* 005f51e0  game  [ledger]  ~GameController_buildDecalMesh */
undefined FUN_005f51e0(void);

/* 005f8ad0  game  [ledger]  ~GameController_buildDecalMesh2 */
undefined FUN_005f8ad0(void);

/* 005f8e10  gamemisc  [ledger]  ~vec3_distanceSquared */
undefined FUN_005f8e10(void);

/* 005f9620  gamemisc  [ledger]  ~vec3_store4 */
undefined FUN_005f9620(void);

/* 005f9e50  gamemisc  [ledger]  ~vec2_store */
undefined FUN_005f9e50(void);

