// Helpers_01 (world) -- cube. 71 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 005c3de0  gamemisc  [caller-vote] */
undefined FUN_005c3de0(void);

/* 005c3e80  gamemisc  [caller-vote] */
undefined FUN_005c3e80(void);

/* 005c3ef0  gamemisc  [caller-vote] */
undefined FUN_005c3ef0(void);

/* 005c3f30  gamemisc  [caller-vote] */
undefined FUN_005c3f30(void);

/* 005c3fe0  gamemisc  [caller-vote] */
undefined FUN_005c3fe0(void);

/* 005c4040  gamemisc  [caller-vote] */
undefined FUN_005c4040(void);

/* 005c4130  gamemisc  [caller-vote] */
undefined FUN_005c4130(void);

/* 005c4230  gamemisc  [caller-vote] */
undefined FUN_005c4230(void);

/* 005c4320  gamemisc  [caller-vote] */
undefined FUN_005c4320(void);

/* 005c43d0  gamemisc  [caller-vote] */
undefined FUN_005c43d0(void);

/* 005c4480  gamemisc  [caller-vote] */
undefined FUN_005c4480(void);

/* 005c46f0  gamemisc  [caller-vote] */
undefined FUN_005c46f0(void);

/* 005c4770  gamemisc  [caller-vote] */
undefined FUN_005c4770(void);

/* 005c52a0  gamemisc  [caller-vote] */
undefined FUN_005c52a0(void);

/* 005c8310  gamemisc  [caller-vote] */
undefined FUN_005c8310(void);

/* 005c8350  gamemisc  [caller-vote] */
undefined FUN_005c8350(void);

/* 005c8390  gamemisc  [caller-vote] */
undefined FUN_005c8390(void);

/* 005c9b30  gamemisc  [caller-vote] */
undefined FUN_005c9b30(void);

/* 005c9f90  gamemisc  [caller-vote] */
undefined FUN_005c9f90(void);

/* 005ca0a0  gamemisc  [caller-vote] */
undefined FUN_005ca0a0(void);

/* 005cb3b0  gamemisc  [caller-vote] */
undefined FUN_005cb3b0(void);

/* 005cb550  gamemisc  [caller-vote] */
undefined FUN_005cb550(void);

/* 005cb600  gamemisc  [caller-vote] */
undefined FUN_005cb600(void);

/* 005cbe00  gamemisc  [caller-vote] */
undefined FUN_005cbe00(void);

/* 005d6040  gamemisc  [caller-vote] */
undefined FUN_005d6040(void);

/* 005d7a70  gamemisc  [caller-vote] */
undefined FUN_005d7a70(void);

/* 005d9460  gamemisc  [caller-vote] */
undefined FUN_005d9460(void);

/* 005da280  gamemisc  [caller-vote] */
undefined __thiscall FUN_005da280(void * this, int param_1, int param_2);

/* 005dc6e0  gamemisc  [caller-vote] */
undefined FUN_005dc6e0(void);

/* 005df600  gamemisc  [caller-vote] */
undefined FUN_005df600(void);

/* 005ee0f0  gamemisc  [caller-vote] */
undefined FUN_005ee0f0(void);

/* 005eea40  gamemisc  [caller-vote] */
undefined FUN_005eea40(void);

/* 005ef5a0  gamemisc  [caller-vote] */
undefined FUN_005ef5a0(void);

/* 005ef6d0  gamemisc  [caller-vote] */
undefined FUN_005ef6d0(void);

/* 005ef8f0  gamemisc  [caller-vote] */
undefined FUN_005ef8f0(void);

/* 005efdb0  gamemisc  [caller-vote] */
undefined FUN_005efdb0(void);

/* 005f4b50  gamemisc  [caller-vote] */
undefined FUN_005f4b50(void);

/* 005f4ba0  gamemisc  [caller-vote] */
undefined FUN_005f4ba0(void);

/* 005f4c30  gamemisc  [caller-vote] */
undefined FUN_005f4c30(void);

/* 005f4d10  gamemisc  [caller-vote] */
undefined FUN_005f4d10(void);

/* 005f4da0  gamemisc  [caller-vote] */
undefined FUN_005f4da0(void);

/* 005f56c0  gamemisc  [caller-vote] */
undefined FUN_005f56c0(void);

/* 005f6e20  gamemisc  [caller-vote] */
undefined FUN_005f6e20(void);

/* 005f77b0  gamemisc  [caller-vote] */
undefined FUN_005f77b0(void);

/* 005f79e0  gamemisc  [caller-vote] */
undefined FUN_005f79e0(void);

/* 005f7a60  gamemisc  [caller-vote] */
undefined FUN_005f7a60(void);

/* 005f8590  gamemisc  [caller-vote] */
undefined FUN_005f8590(void);

/* 005f8750  gamemisc  [caller-vote] */
undefined FUN_005f8750(void);

/* 005f8960  gamemisc  [caller-vote] */
undefined FUN_005f8960(void);

/* 005f9e10  gamemisc  [caller-vote] */
undefined FUN_005f9e10(void);

/* 005f9e30  gamemisc  [caller-vote] */
undefined FUN_005f9e30(void);

/* 005fa170  gamemisc  [caller-vote] */
undefined FUN_005fa170(void);

/* 005fa3c0  gamemisc  [caller-vote] */
undefined FUN_005fa3c0(void);

/* 005fa440  gamemisc  [caller-vote] */
undefined FUN_005fa440(void);

/* 005fbc90  gamemisc  [caller-vote] */
undefined __thiscall FUN_005fbc90(void * this);

/* 00601f80  gamemisc  [caller-vote] */
undefined FUN_00601f80(void);

/* 006050b0  gamemisc  [caller-vote] */
undefined __thiscall FUN_006050b0(void * this);

/* 00605420  gamemisc  [caller-vote] */
undefined __thiscall FUN_00605420(void * this);

/* 00609280  gamemisc  [caller-vote] */
undefined FUN_00609280(void);

/* 0064aec0  gamemisc  [caller-vote] */
undefined FUN_0064aec0(void);

/* 0064cd70  gamemisc  [caller-vote] */
undefined FUN_0064cd70(void);

/* 0064e790  gamemisc  [caller-vote] */
undefined FUN_0064e790(void);

/* 0064e7b0  gamemisc  [caller-vote] */
undefined FUN_0064e7b0(void);

/* 00650a20  gamemisc  [caller-vote] */
undefined FUN_00650a20(void);

/* 0065a110  gamemisc  [caller-vote] */
undefined FUN_0065a110(void);

/* 00681220  gamemisc  [caller-vote] */
undefined FUN_00681220(void);

/* 00687ad0  gamemisc  [caller-vote] */
undefined FUN_00687ad0(void);

/* 00688180  gamemisc  [caller-vote] */
undefined FUN_00688180(void);

/* 00688490  gamemisc  [caller-vote] */
undefined FUN_00688490(void);

/* 00688510  gamemisc  [caller-vote] */
undefined FUN_00688510(void);

/* 00688610  gamemisc  [caller-vote] */
undefined FUN_00688610(void);

