// Region (world) -- cube. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 005c3ac0  game  [rtti] */
Region * __thiscall Region(Region * this);

/* 005c3cc0  game  [rtti] */
void __thiscall ~Region(Region * this);

/* 005c3fb0  game  [rtti] */
Region * __thiscall deleting_destructor(Region * this, byte param_1);

