// World (world) -- cube. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0058eb00  game  [rtti] */
void __thiscall World(World * this, undefined4 param_1, char param_2);

/* 00593ed0  game  [rtti] */
void __thiscall ~World(World * this);

/* 005946c0  game  [rtti] */
World * __thiscall deleting_destructor(World * this, byte param_1);

