// Database (db) -- cube. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00449380  game  [rtti] */
Database * __thiscall Database(Database * this);

/* 00449390  game  [rtti] */
void __thiscall Database(Database * this);

/* 004493c0  game  [rtti] */
Database * __thiscall deleting_destructor(Database * this, byte param_1);

