// Helpers_00 (db) -- cube. 200 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0040c380  gamemisc  [caller-vote] */
undefined FUN_0040c380(void);

/* 00520620  gamemisc  [caller-vote] */
undefined FUN_00520620(void);

/* 005240c0  gamemisc  [caller-vote] */
undefined FUN_005240c0(void);

/* 00524410  gamemisc  [caller-vote] */
undefined FUN_00524410(void);

/* 00525a30  gamemisc  [caller-vote] */
undefined FUN_00525a30(void);

/* 00526480  gamemisc  [caller-vote] */
undefined FUN_00526480(void);

/* 00526b60  gamemisc  [caller-vote] */
undefined FUN_00526b60(void);

/* 00527300  gamemisc  [caller-vote] */
undefined FUN_00527300(void);

/* 00527590  gamemisc  [caller-vote] */
undefined FUN_00527590(void);

/* 00527610  gamemisc  [caller-vote] */
undefined FUN_00527610(void);

/* 00528070  gamemisc  [caller-vote] */
undefined FUN_00528070(void);

/* 005280f0  gamemisc  [caller-vote] */
undefined FUN_005280f0(void);

/* 00528cb0  gamemisc  [caller-vote] */
undefined FUN_00528cb0(void);

/* 00528d20  gamemisc  [caller-vote] */
undefined FUN_00528d20(void);

/* 0052b7f0  gamemisc  [caller-vote] */
undefined FUN_0052b7f0(void);

/* 0052e030  gamemisc  [caller-vote] */
undefined FUN_0052e030(void);

/* 0052e070  gamemisc  [caller-vote] */
undefined FUN_0052e070(void);

/* 0052e890  gamemisc  [caller-vote] */
undefined FUN_0052e890(void);

/* 0052f080  gamemisc  [caller-vote] */
undefined FUN_0052f080(void);

/* 0052ff10  gamemisc  [caller-vote] */
undefined FUN_0052ff10(void);

/* 005303a0  gamemisc  [caller-vote] */
undefined FUN_005303a0(void);

/* 005308c0  gamemisc  [caller-vote] */
undefined FUN_005308c0(void);

/* 00532670  gamemisc  [caller-vote] */
undefined FUN_00532670(void);

/* 005326d0  gamemisc  [caller-vote] */
undefined FUN_005326d0(void);

/* 00532e30  gamemisc  [caller-vote] */
undefined FUN_00532e30(void);

/* 005342f0  gamemisc  [caller-vote] */
undefined FUN_005342f0(void);

/* 005343b0  gamemisc  [caller-vote] */
undefined FUN_005343b0(void);

/* 00534680  gamemisc  [caller-vote] */
undefined FUN_00534680(void);

/* 00537190  gamemisc  [caller-vote] */
undefined FUN_00537190(void);

/* 00539320  gamemisc  [caller-vote] */
undefined FUN_00539320(void);

/* 00539a30  gamemisc  [caller-vote] */
undefined FUN_00539a30(void);

/* 0053b980  gamemisc  [caller-vote] */
undefined FUN_0053b980(void);

/* 0053bf40  gamemisc  [caller-vote] */
undefined FUN_0053bf40(void);

/* 0053cc30  gamemisc  [caller-vote] */
undefined FUN_0053cc30(void);

/* 0053cd40  gamemisc  [caller-vote] */
undefined FUN_0053cd40(void);

/* 0053d2a0  gamemisc  [caller-vote] */
undefined FUN_0053d2a0(void);

/* 0053dcf0  gamemisc  [caller-vote] */
undefined FUN_0053dcf0(void);

/* 00540b30  gamemisc  [caller-vote] */
undefined FUN_00540b30(void);

/* 00541500  gamemisc  [caller-vote] */
undefined FUN_00541500(void);

/* 005417c0  gamemisc  [caller-vote] */
undefined FUN_005417c0(void);

/* 00541940  gamemisc  [caller-vote] */
undefined FUN_00541940(void);

/* 00541a10  gamemisc  [caller-vote] */
undefined FUN_00541a10(void);

/* 00541ab0  gamemisc  [caller-vote] */
undefined FUN_00541ab0(void);

/* 00541e00  gamemisc  [caller-vote] */
undefined FUN_00541e00(void);

/* 00542000  gamemisc  [caller-vote] */
undefined FUN_00542000(void);

/* 005422c0  gamemisc  [caller-vote] */
undefined FUN_005422c0(void);

/* 00542600  gamemisc  [caller-vote] */
undefined FUN_00542600(void);

/* 00542920  gamemisc  [caller-vote] */
undefined FUN_00542920(void);

/* 00542a20  gamemisc  [caller-vote] */
undefined FUN_00542a20(void);

/* 00542b40  gamemisc  [caller-vote] */
undefined FUN_00542b40(void);

/* 00542bc0  gamemisc  [caller-vote] */
undefined FUN_00542bc0(void);

/* 00542d70  gamemisc  [caller-vote] */
undefined FUN_00542d70(void);

/* 00542df0  gamemisc  [caller-vote] */
undefined FUN_00542df0(void);

/* 00544190  gamemisc  [caller-vote] */
undefined FUN_00544190(void);

/* 00544570  gamemisc  [caller-vote] */
undefined FUN_00544570(void);

/* 005445e0  gamemisc  [caller-vote] */
undefined FUN_005445e0(void);

/* 00544710  gamemisc  [caller-vote] */
undefined FUN_00544710(void);

/* 00544c20  gamemisc  [caller-vote] */
undefined FUN_00544c20(void);

/* 00544d30  gamemisc  [caller-vote] */
undefined FUN_00544d30(void);

/* 00544d80  gamemisc  [caller-vote] */
undefined FUN_00544d80(void);

/* 00544e80  gamemisc  [caller-vote] */
undefined FUN_00544e80(void);

/* 005450a0  gamemisc  [caller-vote] */
undefined FUN_005450a0(void);

/* 005452d0  gamemisc  [caller-vote] */
undefined FUN_005452d0(void);

/* 005455d0  gamemisc  [caller-vote] */
undefined FUN_005455d0(void);

/* 00545650  gamemisc  [caller-vote] */
undefined FUN_00545650(void);

/* 00545740  gamemisc  [caller-vote] */
undefined FUN_00545740(void);

/* 00545a20  gamemisc  [caller-vote] */
undefined FUN_00545a20(void);

/* 00545b50  gamemisc  [caller-vote] */
undefined FUN_00545b50(void);

/* 00545bb0  gamemisc  [caller-vote] */
undefined FUN_00545bb0(void);

/* 00545c40  gamemisc  [caller-vote] */
undefined FUN_00545c40(void);

/* 00546130  gamemisc  [caller-vote] */
undefined FUN_00546130(void);

/* 005472b0  gamemisc  [caller-vote] */
undefined FUN_005472b0(void);

/* 005473d0  gamemisc  [caller-vote] */
undefined FUN_005473d0(void);

/* 005489b0  gamemisc  [caller-vote] */
undefined FUN_005489b0(void);

/* 00548e20  gamemisc  [caller-vote] */
undefined FUN_00548e20(void);

/* 00548e60  gamemisc  [caller-vote] */
undefined FUN_00548e60(void);

/* 00548ec0  gamemisc  [caller-vote] */
undefined FUN_00548ec0(void);

/* 00548f50  gamemisc  [caller-vote] */
undefined FUN_00548f50(void);

/* 00549000  gamemisc  [caller-vote] */
undefined FUN_00549000(void);

/* 00549060  gamemisc  [caller-vote] */
undefined FUN_00549060(void);

/* 005490f0  gamemisc  [caller-vote] */
undefined FUN_005490f0(void);

/* 00549230  gamemisc  [caller-vote] */
undefined FUN_00549230(void);

/* 00549280  gamemisc  [caller-vote] */
undefined FUN_00549280(void);

/* 00549420  gamemisc  [caller-vote] */
undefined FUN_00549420(void);

/* 00549610  gamemisc  [caller-vote] */
undefined FUN_00549610(void);

/* 00549fd0  gamemisc  [caller-vote] */
undefined FUN_00549fd0(void);

/* 0054a110  gamemisc  [caller-vote] */
undefined FUN_0054a110(void);

/* 0054a160  gamemisc  [caller-vote] */
undefined FUN_0054a160(void);

/* 0054a2b0  gamemisc  [caller-vote] */
undefined FUN_0054a2b0(void);

/* 0054ab50  gamemisc  [caller-vote] */
undefined FUN_0054ab50(void);

/* 0054b6e0  gamemisc  [caller-vote] */
undefined FUN_0054b6e0(void);

/* 0054c040  gamemisc  [caller-vote] */
undefined FUN_0054c040(void);

/* 0054c100  gamemisc  [caller-vote] */
undefined FUN_0054c100(void);

/* 0054c2e0  gamemisc  [caller-vote] */
undefined FUN_0054c2e0(void);

/* 0054c710  gamemisc  [caller-vote] */
undefined FUN_0054c710(void);

/* 0054c7f0  gamemisc  [caller-vote] */
undefined FUN_0054c7f0(void);

/* 0054c990  gamemisc  [caller-vote] */
undefined FUN_0054c990(void);

/* 0054ca30  gamemisc  [caller-vote] */
undefined FUN_0054ca30(void);

/* 0054d260  gamemisc  [caller-vote] */
undefined FUN_0054d260(void);

/* 0054d340  gamemisc  [caller-vote] */
undefined FUN_0054d340(void);

/* 0054ddf0  gamemisc  [caller-vote] */
undefined FUN_0054ddf0(void);

/* 0054de20  gamemisc  [caller-vote] */
undefined FUN_0054de20(void);

/* 0054ed50  gamemisc  [caller-vote] */
undefined FUN_0054ed50(void);

/* 0054f060  gamemisc  [caller-vote] */
undefined FUN_0054f060(void);

/* 0054f600  gamemisc  [caller-vote] */
undefined FUN_0054f600(void);

/* 0054fc20  gamemisc  [caller-vote] */
undefined FUN_0054fc20(void);

/* 0054fcf0  gamemisc  [caller-vote] */
undefined FUN_0054fcf0(void);

/* 0054fdb0  gamemisc  [caller-vote] */
undefined FUN_0054fdb0(void);

/* 00550b60  gamemisc  [caller-vote] */
undefined FUN_00550b60(void);

/* 00551190  gamemisc  [caller-vote] */
undefined FUN_00551190(void);

/* 00552000  gamemisc  [caller-vote] */
undefined FUN_00552000(void);

/* 005521a0  gamemisc  [caller-vote] */
undefined FUN_005521a0(void);

/* 00552230  gamemisc  [caller-vote] */
undefined FUN_00552230(void);

/* 005522c0  gamemisc  [caller-vote] */
undefined FUN_005522c0(void);

/* 00552390  gamemisc  [caller-vote] */
undefined FUN_00552390(void);

/* 00552450  gamemisc  [caller-vote] */
undefined FUN_00552450(void);

/* 00552540  gamemisc  [caller-vote] */
undefined FUN_00552540(void);

/* 00552560  gamemisc  [caller-vote] */
undefined FUN_00552560(void);

/* 005529a0  gamemisc  [caller-vote] */
undefined FUN_005529a0(void);

/* 00552b20  gamemisc  [caller-vote] */
undefined FUN_00552b20(void);

/* 005530e0  gamemisc  [caller-vote] */
undefined FUN_005530e0(void);

/* 00553890  gamemisc  [caller-vote] */
undefined FUN_00553890(void);

/* 00553950  gamemisc  [caller-vote] */
undefined FUN_00553950(void);

/* 00553ae0  gamemisc  [caller-vote] */
undefined FUN_00553ae0(void);

/* 00553bb0  gamemisc  [caller-vote] */
undefined FUN_00553bb0(void);

/* 00553e40  gamemisc  [caller-vote] */
undefined FUN_00553e40(void);

/* 005540d0  gamemisc  [caller-vote] */
undefined FUN_005540d0(void);

/* 005545d0  gamemisc  [caller-vote] */
undefined FUN_005545d0(void);

/* 00554760  gamemisc  [caller-vote] */
undefined FUN_00554760(void);

/* 00554810  gamemisc  [caller-vote] */
undefined FUN_00554810(void);

/* 00555e30  gamemisc  [caller-vote] */
undefined FUN_00555e30(void);

/* 00555ed0  gamemisc  [caller-vote] */
undefined FUN_00555ed0(void);

/* 005565a0  gamemisc  [caller-vote] */
undefined FUN_005565a0(void);

/* 00556650  gamemisc  [caller-vote] */
undefined FUN_00556650(void);

/* 00556700  gamemisc  [caller-vote] */
undefined FUN_00556700(void);

/* 00556980  gamemisc  [caller-vote] */
undefined FUN_00556980(void);

/* 00556a00  gamemisc  [caller-vote] */
undefined FUN_00556a00(void);

/* 00556b40  gamemisc  [caller-vote] */
undefined FUN_00556b40(void);

/* 00556be0  gamemisc  [caller-vote] */
undefined FUN_00556be0(void);

/* 00557190  gamemisc  [caller-vote] */
undefined FUN_00557190(void);

/* 00557410  gamemisc  [caller-vote] */
undefined FUN_00557410(void);

/* 005579f0  gamemisc  [caller-vote] */
undefined FUN_005579f0(void);

/* 00557a40  gamemisc  [caller-vote] */
undefined FUN_00557a40(void);

/* 00557ad0  gamemisc  [caller-vote] */
undefined FUN_00557ad0(void);

/* 005581b0  gamemisc  [caller-vote] */
undefined FUN_005581b0(void);

/* 00558520  gamemisc  [caller-vote] */
undefined FUN_00558520(void);

/* 00559bc0  gamemisc  [caller-vote] */
undefined FUN_00559bc0(void);

/* 00559f10  gamemisc  [caller-vote] */
undefined FUN_00559f10(void);

/* 00559fd0  gamemisc  [caller-vote] */
undefined FUN_00559fd0(void);

/* 0055a0e0  gamemisc  [caller-vote] */
undefined FUN_0055a0e0(void);

/* 0055a220  gamemisc  [caller-vote] */
undefined FUN_0055a220(void);

/* 0055a900  gamemisc  [caller-vote] */
undefined FUN_0055a900(void);

/* 0055ab80  gamemisc  [caller-vote] */
undefined FUN_0055ab80(void);

/* 0055ac70  gamemisc  [caller-vote] */
undefined FUN_0055ac70(void);

/* 0055ada0  gamemisc  [caller-vote] */
undefined FUN_0055ada0(void);

/* 0055af40  gamemisc  [caller-vote] */
undefined FUN_0055af40(void);

/* 0055afc0  gamemisc  [caller-vote] */
undefined FUN_0055afc0(void);

/* 0055b460  gamemisc  [caller-vote] */
undefined FUN_0055b460(void);

/* 0055bc20  gamemisc  [caller-vote] */
undefined FUN_0055bc20(void);

/* 0055cf00  gamemisc  [caller-vote] */
undefined FUN_0055cf00(void);

/* 0055cf90  gamemisc  [caller-vote] */
undefined FUN_0055cf90(void);

/* 0055d020  gamemisc  [caller-vote] */
undefined FUN_0055d020(void);

/* 0055d180  gamemisc  [caller-vote] */
undefined FUN_0055d180(void);

/* 0055d6b0  gamemisc  [caller-vote] */
undefined FUN_0055d6b0(void);

/* 0055d830  gamemisc  [caller-vote] */
undefined FUN_0055d830(void);

/* 0055d980  gamemisc  [caller-vote] */
undefined FUN_0055d980(void);

/* 0055da00  gamemisc  [caller-vote] */
undefined FUN_0055da00(void);

/* 0055da70  gamemisc  [caller-vote] */
undefined FUN_0055da70(void);

/* 0055daf0  gamemisc  [caller-vote] */
undefined FUN_0055daf0(void);

/* 0055dc60  gamemisc  [caller-vote] */
undefined FUN_0055dc60(void);

/* 0055e380  gamemisc  [caller-vote] */
undefined FUN_0055e380(void);

/* 0055e3f0  gamemisc  [caller-vote] */
undefined FUN_0055e3f0(void);

/* 0055e6e0  gamemisc  [caller-vote] */
undefined FUN_0055e6e0(void);

/* 0055e900  gamemisc  [caller-vote] */
undefined FUN_0055e900(void);

/* 0055e930  gamemisc  [caller-vote] */
undefined FUN_0055e930(void);

/* 0055ea00  gamemisc  [caller-vote] */
undefined FUN_0055ea00(void);

/* 0055ea20  gamemisc  [caller-vote] */
undefined FUN_0055ea20(void);

/* 0055ea40  gamemisc  [caller-vote] */
undefined FUN_0055ea40(void);

/* 0055ea60  gamemisc  [caller-vote] */
undefined FUN_0055ea60(void);

/* 0055eaf0  gamemisc  [caller-vote] */
undefined FUN_0055eaf0(void);

/* 0055eb70  gamemisc  [caller-vote] */
undefined FUN_0055eb70(void);

/* 0055ee50  gamemisc  [caller-vote] */
undefined FUN_0055ee50(void);

/* 0055f050  gamemisc  [caller-vote] */
undefined FUN_0055f050(void);

/* 0055f260  gamemisc  [caller-vote] */
undefined FUN_0055f260(void);

/* 0055f390  gamemisc  [caller-vote] */
undefined FUN_0055f390(void);

/* 0055faf0  gamemisc  [caller-vote] */
undefined FUN_0055faf0(void);

/* 0055fbc0  gamemisc  [caller-vote] */
undefined FUN_0055fbc0(void);

/* 0055fc70  gamemisc  [caller-vote] */
undefined FUN_0055fc70(void);

/* 0055fe80  gamemisc  [caller-vote] */
undefined FUN_0055fe80(void);

/* 00560030  gamemisc  [caller-vote] */
undefined FUN_00560030(void);

/* 00560280  gamemisc  [caller-vote] */
undefined FUN_00560280(void);

/* 005602d0  gamemisc  [caller-vote] */
undefined FUN_005602d0(void);

/* 00560330  gamemisc  [caller-vote] */
undefined FUN_00560330(void);

/* 00560af0  gamemisc  [caller-vote] */
undefined FUN_00560af0(void);

/* 00560c30  gamemisc  [caller-vote] */
undefined FUN_00560c30(void);

/* 00560c70  gamemisc  [caller-vote] */
undefined FUN_00560c70(void);

/* 00560cd0  gamemisc  [caller-vote] */
undefined FUN_00560cd0(void);

/* 00560e50  gamemisc  [caller-vote] */
undefined FUN_00560e50(void);

/* 00560e90  gamemisc  [caller-vote] */
undefined FUN_00560e90(void);

/* 00561000  gamemisc  [caller-vote] */
undefined FUN_00561000(void);

