// ContinuousArrayAttribute (engine) -- cube. 23 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0063c5e0  game  [rtti] */
void __thiscall ~ContinuousArrayAttribute<plasma::Vector<4,float>_>(ContinuousArrayAttribute<plasma::Vector<4,float>_> * this);

/* 0063d7f0  game  [rtti] */
ContinuousArrayAttribute<plasma::Vector<4,float>_> * __thiscall deleting_destructor(ContinuousArrayAttribute<plasma::Vector<4,float>_> * this, byte param_1);

/* 0063df60  game  [rtti] */
int __thiscall vfunction3(ContinuousArrayAttribute<plasma::Vector<4,float>_> * this);

/* 00641440  game  [rtti] */
void __thiscall vfunction5(ContinuousArrayAttribute<plasma::Vector<4,float>_> * this, int param_1);

/* 00641b30  game  [rtti] */
void __thiscall vfunction4(ContinuousArrayAttribute<plasma::Vector<4,float>_> * this, int param_1);

/* 00641b70  game  [rtti] */
void __thiscall vfunction7(ContinuousArrayAttribute<plasma::Vector<4,float>_> * this, int param_1, int param_2, int param_3, int param_4, float param_5, float param_6, undefined4 param_7, float param_8, float param_9, float param_10, float param_11);

/* 00642580  game  [rtti] */
int __thiscall vfunction2(ContinuousArrayAttribute<plasma::Vector<4,float>_> * this);

/* 00642870  game  [rtti] */
void __thiscall vfunction6(ContinuousArrayAttribute<plasma::Vector<4,float>_> * this, int param_1);

/* 006661b0  game  [rtti] */
ContinuousArrayAttribute<float> * __thiscall ContinuousArrayAttribute<float>(ContinuousArrayAttribute<float> * this, undefined4 param_1, undefined4 param_2);

/* 00666280  game  [rtti] */
ContinuousArrayAttribute<plasma::Vector<2,float>_> * __thiscall ContinuousArrayAttribute<plasma::Vector<2,float>_>(ContinuousArrayAttribute<plasma::Vector<2,float>_> * this, undefined4 param_1, undefined4 param_2);

/* 00666350  game  [rtti] */
ContinuousArrayAttribute<plasma::Vector<4,float>_> * __thiscall ContinuousArrayAttribute<plasma::Vector<4,float>_>(ContinuousArrayAttribute<plasma::Vector<4,float>_> * this, undefined4 param_1, undefined4 param_2);

/* 00667370  game  [rtti] */
void __thiscall ~ContinuousArrayAttribute<float>(ContinuousArrayAttribute<float> * this);

/* 00667410  game  [rtti] */
void __thiscall ~ContinuousArrayAttribute<plasma::Vector<2,float>_>(ContinuousArrayAttribute<plasma::Vector<2,float>_> * this);

/* 00667d40  game  [rtti] */
ContinuousArrayAttribute<float> * __thiscall deleting_destructor(ContinuousArrayAttribute<float> * this, byte param_1);

/* 00667d70  game  [rtti] */
ContinuousArrayAttribute<plasma::Vector<2,float>_> * __thiscall deleting_destructor(ContinuousArrayAttribute<plasma::Vector<2,float>_> * this, byte param_1);

/* 00668d20  game  [rtti] */
int __thiscall vfunction3(ContinuousArrayAttribute<float> * this);

/* 00668de0  game  [rtti] */
int __thiscall vfunction3(ContinuousArrayAttribute<plasma::Vector<2,float>_> * this);

/* 006695d0  game  [rtti] */
void __thiscall vfunction4(ContinuousArrayAttribute<float> * this, int param_1);

/* 00669600  game  [rtti] */
void __thiscall vfunction4(ContinuousArrayAttribute<plasma::Vector<2,float>_> * this, int param_1);

/* 00669720  game  [rtti] */
void __thiscall vfunction7(ContinuousArrayAttribute<float> * this, int param_1, int param_2, int param_3, int param_4, float param_5, float param_6, undefined4 param_7, float param_8, float param_9, float param_10, float param_11);

/* 00669850  game  [rtti] */
void __thiscall vfunction7(ContinuousArrayAttribute<plasma::Vector<2,float>_> * this, int param_1, int param_2, int param_3, int param_4, float param_5, float param_6, undefined4 param_7, float param_8, float param_9, float param_10, float param_11);

/* 0066afc0  game  [rtti] */
void __thiscall vfunction6(ContinuousArrayAttribute<float> * this, int param_1);

/* 0066aff0  game  [rtti] */
void __thiscall vfunction6(ContinuousArrayAttribute<plasma::Vector<2,float>_> * this, int param_1);

