// CurveShape (engine) -- cube. 11 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0066b1f0  game  [rtti] */
void __thiscall vfunction12(CurveShape * this);

/* 0066be80  game  [rtti] */
void __thiscall vfunction11(CurveShape * this);

/* 0067a470  game  [rtti] */
void __thiscall ~CurveShape(CurveShape * this);

/* 0067a8c0  game  [rtti] */
CurveShape * __thiscall deleting_destructor(CurveShape * this, byte param_1);

/* 0067a8f0  game  [rtti] */
void __thiscall vfunction8(CurveShape * this, undefined4 * param_1);

/* 0067a910  game  [rtti] */
void __thiscall vfunction7(CurveShape * this, undefined4 * param_1);

/* 0067a930  game  [rtti] */
int * __thiscall vfunction14(CurveShape * this);

/* 0067ab30  game  [rtti] */
void __thiscall vfunction5(CurveShape * this, float * param_1);

/* 0067ad00  game  [rtti] */
void __thiscall vfunction20(CurveShape * this);

/* 0067bd60  game  [rtti] */
void __thiscall vfunction2(CurveShape * this);

/* 0067cd10  game  [rtti] */
void __thiscall vfunction13(CurveShape * this, float * param_1, float * param_2, float * param_3, undefined8 * param_4, float * param_5, float * param_6);

