// D3D9Engine (engine) -- cube. 22 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00653320  game  [rtti] */
int __thiscall ~D3D9Engine(D3D9Engine * this);

/* 006887a0  game  [rtti] */
D3D9Engine * __thiscall D3D9Engine(D3D9Engine * this, undefined4 param_1);

/* 00688900  game  [rtti] */
void __thiscall ~D3D9Engine(D3D9Engine * this);

/* 00688af0  game  [rtti] */
D3D9Engine * __thiscall deleting_destructor(D3D9Engine * this, byte param_1);

/* 00688b60  game  [rtti] */
void __thiscall vfunction20(D3D9Engine * this);

/* 00688db0  game  [rtti] */
void __thiscall vfunction22(D3D9Engine * this, int param_1);

/* 00688e70  game  [rtti] */
void __thiscall vfunction17(D3D9Engine * this, int param_1);

/* 00689130  game  [rtti] */
void __thiscall vfunction26(D3D9Engine * this, int * param_1, float * param_2, float * param_3, float param_4, char param_5);

/* 00689660  game  [rtti] */
undefined4 __thiscall vfunction13(D3D9Engine * this);

/* 006896d0  game  [rtti] */
undefined4 __thiscall vfunction14(D3D9Engine * this, undefined4 param_1);

/* 00689740  game  [rtti] */
undefined4 __thiscall vfunction3(D3D9Engine * this, undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6);

/* 006897c0  game  [rtti] */
void __thiscall vfunction4(D3D9Engine * this, undefined4 * param_1, int param_2);

/* 00689950  game  [rtti] */
void __thiscall vfunction5(D3D9Engine * this, float * param_1, float * param_2);

/* 00689af0  game  [rtti] */
void __thiscall vfunction6(D3D9Engine * this, float * param_1, float * param_2, float * param_3, float * param_4, undefined4 * param_5);

/* 00689d50  game  [rtti] */
void __thiscall vfunction7(D3D9Engine * this, float * param_1, float * param_2, undefined4 * param_3);

/* 0068a250  game  [rtti] */
void __thiscall vfunction21(D3D9Engine * this);

/* 0068a260  game  [rtti] */
void __thiscall vfunction23(D3D9Engine * this);

/* 0068a2c0  game  [rtti] */
void __thiscall deleting_destructor(D3D9Engine * this);

/* 0068a330  game  [rtti] */
void __thiscall vfunction15(D3D9Engine * this, undefined4 * param_1);

/* 0068a350  game  [rtti] */
void __thiscall vfunction2(D3D9Engine * this);

/* 0068a7e0  game  [rtti] */
void __thiscall vfunction16(D3D9Engine * this, undefined4 * param_1);

/* 0068a800  game  [rtti] */
void __thiscall vfunction19(D3D9Engine * this);

