// GenericShape (engine) -- cube. 7 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0067cff0  game  [rtti] */
GenericShape * __thiscall GenericShape(GenericShape * this, int * param_1, undefined4 param_2, undefined4 param_3);

/* 0067d0b0  game  [rtti] */
GenericShape * __thiscall deleting_destructor(GenericShape * this, byte param_1);

/* 0067d150  game  [rtti] */
float * __thiscall vfunction8(GenericShape * this, float * param_1);

/* 0067d190  game  [rtti] */
void __thiscall vfunction7(GenericShape * this, undefined4 * param_1);

/* 0067d1b0  game  [rtti] */
int * __thiscall vfunction14(GenericShape * this);

/* 0067d1f0  game  [rtti] */
void __thiscall vfunction20(GenericShape * this);

/* 0067d440  game  [rtti] */
void __thiscall vfunction2(GenericShape * this);

