// HelperCmpClass (engine) -- cube. 2 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00408760  game  [rtti] */
void __stdcall HelperCmpClass_Constructor_or_Destructor(abstr__HelperCmpClass_data * param_1);

/* 0040cbe0  game  [rtti] */
undefined4 __thiscall vfunction1(HelperCmpClass * this, int param_1);

