// MeshShape (engine) -- cube. 11 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00666580  game  [rtti] */
void __thiscall MeshShape(MeshShape * this, int param_1, undefined4 param_2);

/* 006674b0  game  [rtti] */
void __thiscall ~MeshShape(MeshShape * this);

/* 00667da0  game  [rtti] */
MeshShape * __thiscall deleting_destructor(MeshShape * this, byte param_1);

/* 00668b60  game  [rtti] */
void __thiscall vfunction19(MeshShape * this, float * param_1, float * param_2);

/* 00669060  game  [rtti] */
void __thiscall vfunction8(MeshShape * this, undefined4 * param_1);

/* 00669080  game  [rtti] */
void __thiscall vfunction7(MeshShape * this, undefined4 * param_1);

/* 006690a0  game  [rtti] */
int * __thiscall vfunction14(MeshShape * this);

/* 00669460  game  [rtti] */
void __thiscall vfunction10(MeshShape * this, float * param_1, float * param_2, float * param_3, char * param_4);

/* 0066ac20  game  [rtti] */
void __thiscall vfunction5(MeshShape * this, float * param_1);

/* 0066be90  game  [rtti] */
void __thiscall vfunction20(MeshShape * this);

/* 0066c8f0  game  [rtti] */
void __thiscall vfunction13(MeshShape * this, float * param_1, float * param_2, float * param_3, undefined8 * param_4, float * param_5, float * param_6);

