// Method1 (engine) -- cube. 6 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00585970  game  [rtti] */
void __thiscall vfunction1(Method1<cube::System,int,int> * this, undefined4 param_1);

/* 00585990  game  [rtti] */
void __thiscall vfunction1(Method1<cube::System,int,std::basic_string<char,std::char_traits<char>,std::allocator<char>_>_> * this, undefined4 param_1);

/* 005859b0  game  [rtti] */
void __thiscall vfunction1(Method1<cube::System,std::basic_string<char,std::char_traits<char>,std::allocator<char>_>,int> * this, undefined4 param_1);

/* 005859d0  game  [rtti] */
void __thiscall vfunction1(Method1<cube::System,std::basic_string<char,std::char_traits<char>,std::allocator<char>_>,std::basic_string<char,struct_std::char_traits<char>,class_std::allocator<char>_>_> * this, undefined4 param_1);

/* 00585ad0  game  [rtti] */
void __thiscall vfunction1(Method1<cube::System,void,int> * this, undefined4 param_1);

/* 00585be0  game  [rtti] */
void __thiscall vfunction1(Method1<cube::System,void,std::basic_string<char,std::char_traits<char>,std::allocator<char>_>_> * this, undefined4 param_1);

