// Object (engine) -- cube. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00662730  game  [rtti] */
Object * __thiscall Object(Object * this, int param_1);

/* 00662760  game  [rtti] */
void __thiscall ~Object(Object * this);

/* 006627a0  game  [rtti] */
Object * __thiscall deleting_destructor(Object * this, byte param_1);

