// PixelFont (engine) -- cube. 7 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0067f290  game  [rtti] */
PixelFont * __thiscall PixelFont(PixelFont * this, Font * param_1, int param_2);

/* 0067f330  game  [rtti] */
void __thiscall ~PixelFont(PixelFont * this);

/* 0067f3d0  game  [rtti] */
PixelFont * __thiscall deleting_destructor(PixelFont * this, byte param_1);

/* 0067f400  game  [rtti] */
void __thiscall vfunction5(PixelFont * this, undefined4 * param_1);

/* 0067f420  game  [rtti] */
void __thiscall vfunction4(PixelFont * this, undefined4 * param_1);

/* 0067f450  game  [rtti] */
void __thiscall vfunction3(PixelFont * this, undefined4 * param_1, float * param_2, float * param_3, uint param_4);

/* 0067f720  game  [rtti] */
void __thiscall vfunction2(PixelFont * this, undefined4 * param_1, int param_2, float * param_3, float * param_4, undefined4 param_5);

