; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

	TITLE	C:\Users\asuna\Desktop\RatRealms\CubegameV1\RatForge\tools\cw_decomp\reccmp\formula_inverse.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_formula_inverse
PUBLIC	__real@3f800000
PUBLIC	__real@41a00000
EXTRN	__fltused:DWORD
;	COMDAT __real@41a00000
CONST	SEGMENT
__real@41a00000 DD 041a00000r			; 20
CONST	ENDS
;	COMDAT __real@3f800000
CONST	SEGMENT
__real@3f800000 DD 03f800000r			; 1
CONST	ENDS
; Function compile flags: /Ogtp
;	COMDAT _formula_inverse
_TEXT	SEGMENT
tv131 = 8						; size = 4
_x$ = 8							; size = 4
_formula_inverse PROC					; COMDAT
; File c:\users\asuna\desktop\ratrealms\cubegamev1\ratforge\tools\cw_decomp\reccmp\formula_inverse.c
; Line 4
	push	ebp
	mov	ebp, esp
; Line 5
	movss	xmm2, DWORD PTR __real@3f800000
	movaps	xmm0, xmm2
	subss	xmm0, DWORD PTR _x$[ebp]
	movaps	xmm1, xmm2
	divss	xmm1, xmm0
	subss	xmm1, xmm2
	mulss	xmm1, DWORD PTR __real@41a00000
	addss	xmm1, xmm2
	movss	DWORD PTR tv131[ebp], xmm1
	fld	DWORD PTR tv131[ebp]
; Line 6
	pop	ebp
	ret	0
_formula_inverse ENDP
_TEXT	ENDS
END
