// eh_funclets_00 (_library) -- server. 200 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00401786  lib  [eh] */
undefined * __stdcall Catch_All@00401786(void);

/* 004017c3  lib  [eh] */
undefined __stdcall Catch_All@004017c3(void);

/* 004027ef  lib  [eh] */
undefined __stdcall Catch_All@004027ef(void);

/* 00402954  lib  [eh] */
undefined __stdcall Catch_All@00402954(void);

/* 004128ba  lib  [eh] */
undefined * __stdcall Catch_All@004128ba(void);

/* 0041391e  lib  [eh] */
undefined __stdcall Catch_All@0041391e(void);

/* 00416dff  lib  [eh] */
undefined * __stdcall Catch_All@00416dff(void);

/* 00416e3c  lib  [eh] */
undefined __stdcall Catch_All@00416e3c(void);

/* 0041a657  lib  [eh] */
undefined __stdcall Catch_All@0041a657(void);

/* 0041a78f  lib  [eh] */
undefined __stdcall Catch_All@0041a78f(void);

/* 0041aaef  lib  [eh] */
undefined __stdcall Catch_All@0041aaef(void);

/* 0041bb5f  lib  [eh] */
undefined __stdcall Catch_All@0041bb5f(void);

/* 0041d4c6  lib  [eh] */
undefined __stdcall Catch_All@0041d4c6(void);

/* 0041d7bf  lib  [eh] */
undefined __stdcall Catch_All@0041d7bf(void);

/* 0041dac0  lib  [eh] */
undefined __stdcall Catch_All@0041dac0(void);

/* 0041dc43  lib  [eh] */
undefined __stdcall Catch_All@0041dc43(void);

/* 0041de13  lib  [eh] */
undefined __stdcall Catch_All@0041de13(void);

/* 0041e520  lib  [eh] */
undefined __stdcall Catch_All@0041e520(void);

/* 0041e61e  lib  [eh] */
undefined __stdcall Catch_All@0041e61e(void);

/* 0041e71c  lib  [eh] */
undefined __stdcall Catch_All@0041e71c(void);

/* 0041e820  lib  [eh] */
undefined __stdcall Catch_All@0041e820(void);

/* 0041f75d  lib  [eh] */
undefined __stdcall Catch_All@0041f75d(void);

/* 0041f860  lib  [eh] */
undefined __stdcall Catch_All@0041f860(void);

/* 004201e2  lib  [eh] */
undefined __stdcall Catch_All@004201e2(void);

/* 00420299  lib  [eh] */
undefined __stdcall Catch_All@00420299(void);

/* 00420362  lib  [eh] */
undefined __stdcall Catch_All@00420362(void);

/* 0042052c  lib  [eh] */
undefined __stdcall Catch_All@0042052c(void);

/* 004205df  lib  [eh] */
undefined __stdcall Catch_All@004205df(void);

/* 00420a0f  lib  [eh] */
undefined __stdcall Catch_All@00420a0f(void);

/* 00420b74  lib  [eh] */
undefined __stdcall Catch_All@00420b74(void);

/* 00420c39  lib  [eh] */
undefined __stdcall Catch_All@00420c39(void);

/* 00420d09  lib  [eh] */
undefined __stdcall Catch_All@00420d09(void);

/* 00420dd9  lib  [eh] */
undefined __stdcall Catch_All@00420dd9(void);

/* 00420ea9  lib  [eh] */
undefined __stdcall Catch_All@00420ea9(void);

/* 00420f79  lib  [eh] */
undefined __stdcall Catch_All@00420f79(void);

/* 00421049  lib  [eh] */
undefined __stdcall Catch_All@00421049(void);

/* 00421119  lib  [eh] */
undefined __stdcall Catch_All@00421119(void);

/* 004211e9  lib  [eh] */
undefined __stdcall Catch_All@004211e9(void);

/* 004212b9  lib  [eh] */
undefined __stdcall Catch_All@004212b9(void);

/* 00421389  lib  [eh] */
undefined __stdcall Catch_All@00421389(void);

/* 00421459  lib  [eh] */
undefined __stdcall Catch_All@00421459(void);

/* 00421529  lib  [eh] */
undefined __stdcall Catch_All@00421529(void);

/* 004215f9  lib  [eh] */
undefined __stdcall Catch_All@004215f9(void);

/* 004216c9  lib  [eh] */
undefined __stdcall Catch_All@004216c9(void);

/* 00421799  lib  [eh] */
undefined __stdcall Catch_All@00421799(void);

/* 00421867  lib  [eh] */
undefined __stdcall Catch_All@00421867(void);

/* 00421939  lib  [eh] */
undefined __stdcall Catch_All@00421939(void);

/* 00421eff  lib  [eh] */
undefined __stdcall Catch_All@00421eff(void);

/* 00421f9f  lib  [eh] */
undefined __stdcall Catch_All@00421f9f(void);

/* 0042203f  lib  [eh] */
undefined __stdcall Catch_All@0042203f(void);

/* 004220df  lib  [eh] */
undefined __stdcall Catch_All@004220df(void);

/* 0042217f  lib  [eh] */
undefined __stdcall Catch_All@0042217f(void);

/* 0042221f  lib  [eh] */
undefined __stdcall Catch_All@0042221f(void);

/* 004222bf  lib  [eh] */
undefined __stdcall Catch_All@004222bf(void);

/* 0042235f  lib  [eh] */
undefined __stdcall Catch_All@0042235f(void);

/* 004223ff  lib  [eh] */
undefined __stdcall Catch_All@004223ff(void);

/* 0042249f  lib  [eh] */
undefined __stdcall Catch_All@0042249f(void);

/* 0042253f  lib  [eh] */
undefined __stdcall Catch_All@0042253f(void);

/* 004225df  lib  [eh] */
undefined __stdcall Catch_All@004225df(void);

/* 0042267f  lib  [eh] */
undefined __stdcall Catch_All@0042267f(void);

/* 0042271f  lib  [eh] */
undefined __stdcall Catch_All@0042271f(void);

/* 004227bf  lib  [eh] */
undefined __stdcall Catch_All@004227bf(void);

/* 00426e8e  lib  [eh] */
undefined __stdcall Catch_All@00426e8e(void);

/* 00429040  lib  [eh] */
undefined * __stdcall Catch_All@00429040(void);

/* 00429180  lib  [eh] */
undefined __stdcall Catch_All@00429180(void);

/* 00429227  lib  [eh] */
undefined __stdcall Catch_All@00429227(void);

/* 0042931d  lib  [eh] */
undefined __stdcall Catch_All@0042931d(void);

/* 00429415  lib  [eh] */
undefined __stdcall Catch_All@00429415(void);

/* 0042954f  lib  [eh] */
undefined __stdcall Catch_All@0042954f(void);

/* 0042a018  lib  [eh] */
undefined __stdcall Catch_All@0042a018(void);

/* 0042a244  lib  [eh] */
undefined __stdcall Catch_All@0042a244(void);

/* 0042a434  lib  [eh] */
undefined __stdcall Catch_All@0042a434(void);

/* 0042a624  lib  [eh] */
undefined __stdcall Catch_All@0042a624(void);

/* 0042a814  lib  [eh] */
undefined __stdcall Catch_All@0042a814(void);

/* 0042a908  lib  [eh] */
undefined __stdcall Catch_All@0042a908(void);

/* 0042aac0  lib  [eh] */
undefined __stdcall Catch_All@0042aac0(void);

/* 0042ac24  lib  [eh] */
undefined __stdcall Catch_All@0042ac24(void);

/* 0042ad84  lib  [eh] */
undefined __stdcall Catch_All@0042ad84(void);

/* 0042ae29  lib  [eh] */
undefined __stdcall Catch_All@0042ae29(void);

/* 0042af1d  lib  [eh] */
undefined __stdcall Catch_All@0042af1d(void);

/* 0042b0b6  lib  [eh] */
undefined __stdcall Catch_All@0042b0b6(void);

/* 0042b156  lib  [eh] */
undefined __stdcall Catch_All@0042b156(void);

/* 0042b1ff  lib  [eh] */
undefined __stdcall Catch_All@0042b1ff(void);

/* 0042f318  lib  [eh] */
undefined __stdcall Catch_All@0042f318(void);

/* 00430033  lib  [eh] */
undefined __stdcall Catch_All@00430033(void);

/* 00430911  lib  [eh] */
undefined __stdcall Catch_All@00430911(void);

/* 00430d18  lib  [eh] */
undefined __stdcall Catch_All@00430d18(void);

/* 00430e4d  lib  [eh] */
undefined __stdcall Catch_All@00430e4d(void);

/* 004c5cfd  lib  [eh] */
undefined __stdcall Catch_All@004c5cfd(void);

/* 004c66ee  lib  [eh] */
undefined * __stdcall Catch_All@004c66ee(void);

/* 004c7527  lib  [eh] */
undefined __stdcall Catch_All@004c7527(void);

/* 004c776f  lib  [eh] */
undefined __stdcall Catch_All@004c776f(void);

/* 004c7994  lib  [eh] */
undefined __stdcall Catch_All@004c7994(void);

/* 004c7a8a  lib  [eh] */
undefined __stdcall Catch_All@004c7a8a(void);

/* 004c7c38  lib  [eh] */
undefined __stdcall Catch_All@004c7c38(void);

/* 004c7dbd  lib  [eh] */
undefined __stdcall Catch_All@004c7dbd(void);

/* 004c7f4d  lib  [eh] */
undefined __stdcall Catch_All@004c7f4d(void);

/* 004c7fdd  lib  [eh] */
undefined __stdcall Catch_All@004c7fdd(void);

/* 004c808c  lib  [eh] */
undefined __stdcall Catch_All@004c808c(void);

/* 004c833c  lib  [eh] */
undefined __stdcall Catch_All@004c833c(void);

/* 004ce8c7  lib  [eh] */
undefined __stdcall Catch_All@004ce8c7(void);

/* 004d9aa8  lib  [eh] */
undefined __stdcall Catch_All@004d9aa8(void);

/* 004d9b31  lib  [eh] */
undefined __stdcall Catch_All@004d9b31(void);

/* 004d9cff  lib  [eh] */
undefined __stdcall Catch_All@004d9cff(void);

/* 004d9dbf  lib  [eh] */
undefined __stdcall Catch_All@004d9dbf(void);

/* 004da44c  lib  [eh] */
undefined __stdcall Catch_All@004da44c(void);

/* 004da611  lib  [eh] */
undefined __stdcall Catch_All@004da611(void);

/* 004da75f  lib  [eh] */
undefined __stdcall Catch_All@004da75f(void);

/* 004da906  lib  [eh] */
undefined __stdcall Catch_All@004da906(void);

/* 004dab0f  lib  [eh] */
undefined __stdcall Catch_All@004dab0f(void);

/* 004e1350  lib  [eh] */
undefined __stdcall Catch_All@004e1350(void);

/* 004e1f6c  lib  [eh] */
undefined __stdcall Catch_All@004e1f6c(void);

/* 004e24e4  lib  [eh] */
undefined __stdcall Catch_All@004e24e4(void);

/* 004e25bc  lib  [eh] */
undefined __stdcall Catch_All@004e25bc(void);

/* 004e269d  lib  [eh] */
undefined __stdcall Catch_All@004e269d(void);

/* 004f3803  lib  [eh] */
undefined __stdcall Catch_All@004f3803(void);

/* 004f427f  lib  [eh] */
undefined __stdcall Catch_All@004f427f(void);

/* 004f4505  lib  [eh] */
undefined __stdcall Catch_All@004f4505(void);

/* 004f469e  lib  [eh] */
undefined __stdcall Catch_All@004f469e(void);

/* 004f483e  lib  [eh] */
undefined __stdcall Catch_All@004f483e(void);

/* 004f71a6  lib  [eh] */
undefined __stdcall Catch_All@004f71a6(void);

/* 004f7dd4  lib  [eh] */
undefined __stdcall Catch_All@004f7dd4(void);

/* 004f7ed1  lib  [eh] */
undefined __stdcall Catch_All@004f7ed1(void);

/* 004f7fbf  lib  [eh] */
undefined __stdcall Catch_All@004f7fbf(void);

/* 004f80af  lib  [eh] */
undefined __stdcall Catch_All@004f80af(void);

/* 0052e02c  lib  [eh] */
undefined __stdcall Catch_All@0052e02c(void);

/* 0052e1bf  lib  [eh] */
undefined __stdcall Catch_All@0052e1bf(void);

/* 0052e567  lib  [eh] */
undefined __stdcall Catch_All@0052e567(void);

/* 0052e617  lib  [eh] */
undefined __stdcall Catch_All@0052e617(void);

/* 0052e906  lib  [eh] */
undefined __stdcall Catch_All@0052e906(void);

/* 0052eb79  lib  [eh] */
undefined __stdcall Catch_All@0052eb79(void);

/* 0052ee5c  lib  [eh] */
undefined __stdcall Catch_All@0052ee5c(void);

/* 0054928d  lib  [eh] */
undefined * __stdcall Catch_All@0054928d(void);

/* 0054b980  lib  [eh] */
undefined __stdcall Unwind@0054b980(void);

/* 0054b98b  lib  [eh] */
undefined __stdcall Unwind@0054b98b(void);

/* 0054b996  lib  [eh] */
undefined __stdcall Unwind@0054b996(void);

/* 0054b9a1  lib  [eh] */
undefined __stdcall Unwind@0054b9a1(void);

/* 0054b9e0  lib  [eh] */
undefined __stdcall Unwind@0054b9e0(void);

/* 0054b9ee  lib  [eh] */
undefined __stdcall Unwind@0054b9ee(void);

/* 0054b9fc  lib  [eh] */
undefined __stdcall Unwind@0054b9fc(void);

/* 0054ba0a  lib  [eh] */
undefined __stdcall Unwind@0054ba0a(void);

/* 0054ba18  lib  [eh] */
undefined __stdcall Unwind@0054ba18(void);

/* 0054ba26  lib  [eh] */
undefined __stdcall Unwind@0054ba26(void);

/* 0054ba34  lib  [eh] */
undefined __stdcall Unwind@0054ba34(void);

/* 0054ba42  lib  [eh] */
undefined __stdcall Unwind@0054ba42(void);

/* 0054ba50  lib  [eh] */
undefined __stdcall Unwind@0054ba50(void);

/* 0054ba5e  lib  [eh] */
undefined __stdcall Unwind@0054ba5e(void);

/* 0054ba6c  lib  [eh] */
undefined __stdcall Unwind@0054ba6c(void);

/* 0054ba7a  lib  [eh] */
undefined __stdcall Unwind@0054ba7a(void);

/* 0054ba88  lib  [eh] */
undefined __stdcall Unwind@0054ba88(void);

/* 0054ba96  lib  [eh] */
undefined __stdcall Unwind@0054ba96(void);

/* 0054baa4  lib  [eh] */
undefined __stdcall Unwind@0054baa4(void);

/* 0054bab2  lib  [eh] */
undefined __stdcall Unwind@0054bab2(void);

/* 0054bae0  lib  [eh] */
undefined __stdcall Unwind@0054bae0(void);

/* 0054bb10  lib  [eh] */
undefined __stdcall Unwind@0054bb10(void);

/* 0054bb18  lib  [eh] */
undefined __stdcall Unwind@0054bb18(void);

/* 0054bb40  lib  [eh] */
undefined __stdcall Unwind@0054bb40(void);

/* 0054bb70  lib  [eh] */
undefined __stdcall Unwind@0054bb70(void);

/* 0054bb7b  lib  [eh] */
undefined __stdcall Unwind@0054bb7b(void);

/* 0054bbc0  lib  [eh] */
undefined __stdcall Unwind@0054bbc0(void);

/* 0054bc10  lib  [eh] */
undefined __stdcall Unwind@0054bc10(void);

/* 0054bc80  lib  [eh] */
undefined __stdcall Unwind@0054bc80(void);

/* 0054bc8b  lib  [eh] */
undefined __stdcall Unwind@0054bc8b(void);

/* 0054bc96  lib  [eh] */
undefined __stdcall Unwind@0054bc96(void);

/* 0054bca1  lib  [eh] */
undefined __stdcall Unwind@0054bca1(void);

/* 0054bcd0  lib  [eh] */
undefined __stdcall Unwind@0054bcd0(void);

/* 0054bd00  lib  [eh] */
undefined __stdcall Unwind@0054bd00(void);

/* 0054bd0b  lib  [eh] */
undefined __stdcall Unwind@0054bd0b(void);

/* 0054bd16  lib  [eh] */
undefined __stdcall Unwind@0054bd16(void);

/* 0054bd21  lib  [eh] */
undefined __stdcall Unwind@0054bd21(void);

/* 0054bd2c  lib  [eh] */
undefined __stdcall Unwind@0054bd2c(void);

/* 0054bd60  lib  [eh] */
undefined __stdcall Unwind@0054bd60(void);

/* 0054bd90  lib  [eh] */
undefined __stdcall Unwind@0054bd90(void);

/* 0054bd98  lib  [eh] */
undefined __stdcall Unwind@0054bd98(void);

/* 0054bda3  lib  [eh] */
undefined __stdcall Unwind@0054bda3(void);

/* 0054bdab  lib  [eh] */
undefined __stdcall Unwind@0054bdab(void);

/* 0054bdb6  lib  [eh] */
undefined __stdcall Unwind@0054bdb6(void);

/* 0054bdc1  lib  [eh] */
undefined __stdcall Unwind@0054bdc1(void);

/* 0054bdcc  lib  [eh] */
undefined __stdcall Unwind@0054bdcc(void);

/* 0054bdd4  lib  [eh] */
undefined __stdcall Unwind@0054bdd4(void);

/* 0054bddf  lib  [eh] */
undefined __stdcall Unwind@0054bddf(void);

/* 0054bdea  lib  [eh] */
undefined __stdcall Unwind@0054bdea(void);

/* 0054be40  lib  [eh] */
undefined __stdcall Unwind@0054be40(void);

/* 0054be80  lib  [eh] */
undefined __stdcall Unwind@0054be80(void);

/* 0054beb0  lib  [eh] */
undefined __stdcall Unwind@0054beb0(void);

/* 0054bee0  lib  [eh] */
undefined __stdcall Unwind@0054bee0(void);

/* 0054c010  lib  [eh] */
undefined __stdcall Unwind@0054c010(void);

/* 0054c01b  lib  [eh] */
undefined __stdcall Unwind@0054c01b(void);

/* 0054c090  lib  [eh] */
undefined __stdcall Unwind@0054c090(void);

/* 0054c0c0  lib  [eh] */
undefined __stdcall Unwind@0054c0c0(void);

/* 0054c0f0  lib  [eh] */
undefined __stdcall Unwind@0054c0f0(void);

/* 0054c3c0  lib  [eh] */
undefined __stdcall Unwind@0054c3c0(void);

/* 0054c3f0  lib  [eh] */
undefined __stdcall Unwind@0054c3f0(void);

/* 0054c420  lib  [eh] */
undefined __stdcall Unwind@0054c420(void);

/* 0054c450  lib  [eh] */
undefined __stdcall Unwind@0054c450(void);

/* 0054c480  lib  [eh] */
undefined __stdcall Unwind@0054c480(void);

/* 0054c4b0  lib  [eh] */
undefined __stdcall Unwind@0054c4b0(void);

/* 0054c4e0  lib  [eh] */
undefined __stdcall Unwind@0054c4e0(void);

/* 0054c510  lib  [eh] */
undefined __stdcall Unwind@0054c510(void);

/* 0054c540  lib  [eh] */
undefined __stdcall Unwind@0054c540(void);

