// eh_funclets_03 (_library) -- server. 200 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0054dfce  lib  [eh] */
undefined __stdcall Unwind@0054dfce(void);

/* 0054dfd9  lib  [eh] */
undefined __stdcall Unwind@0054dfd9(void);

/* 0054dfe4  lib  [eh] */
undefined __stdcall Unwind@0054dfe4(void);

/* 0054dfef  lib  [eh] */
undefined __stdcall Unwind@0054dfef(void);

/* 0054dffa  lib  [eh] */
undefined __stdcall Unwind@0054dffa(void);

/* 0054e005  lib  [eh] */
undefined __stdcall Unwind@0054e005(void);

/* 0054e010  lib  [eh] */
undefined __stdcall Unwind@0054e010(void);

/* 0054e01b  lib  [eh] */
undefined __stdcall Unwind@0054e01b(void);

/* 0054e026  lib  [eh] */
undefined __stdcall Unwind@0054e026(void);

/* 0054e031  lib  [eh] */
undefined __stdcall Unwind@0054e031(void);

/* 0054e03c  lib  [eh] */
undefined __stdcall Unwind@0054e03c(void);

/* 0054e047  lib  [eh] */
undefined __stdcall Unwind@0054e047(void);

/* 0054e052  lib  [eh] */
undefined __stdcall Unwind@0054e052(void);

/* 0054e05d  lib  [eh] */
undefined __stdcall Unwind@0054e05d(void);

/* 0054e068  lib  [eh] */
undefined __stdcall Unwind@0054e068(void);

/* 0054e073  lib  [eh] */
undefined __stdcall Unwind@0054e073(void);

/* 0054e07e  lib  [eh] */
undefined __stdcall Unwind@0054e07e(void);

/* 0054e089  lib  [eh] */
undefined __stdcall Unwind@0054e089(void);

/* 0054e094  lib  [eh] */
undefined __stdcall Unwind@0054e094(void);

/* 0054e09f  lib  [eh] */
undefined __stdcall Unwind@0054e09f(void);

/* 0054e0aa  lib  [eh] */
undefined __stdcall Unwind@0054e0aa(void);

/* 0054e0b5  lib  [eh] */
undefined __stdcall Unwind@0054e0b5(void);

/* 0054e0c0  lib  [eh] */
undefined __stdcall Unwind@0054e0c0(void);

/* 0054e0cb  lib  [eh] */
undefined __stdcall Unwind@0054e0cb(void);

/* 0054e0d6  lib  [eh] */
undefined __stdcall Unwind@0054e0d6(void);

/* 0054e0e1  lib  [eh] */
undefined __stdcall Unwind@0054e0e1(void);

/* 0054e0ec  lib  [eh] */
undefined __stdcall Unwind@0054e0ec(void);

/* 0054e0f7  lib  [eh] */
undefined __stdcall Unwind@0054e0f7(void);

/* 0054e102  lib  [eh] */
undefined __stdcall Unwind@0054e102(void);

/* 0054e10d  lib  [eh] */
undefined __stdcall Unwind@0054e10d(void);

/* 0054e118  lib  [eh] */
undefined __stdcall Unwind@0054e118(void);

/* 0054e123  lib  [eh] */
undefined __stdcall Unwind@0054e123(void);

/* 0054e12e  lib  [eh] */
undefined __stdcall Unwind@0054e12e(void);

/* 0054e139  lib  [eh] */
undefined __stdcall Unwind@0054e139(void);

/* 0054e144  lib  [eh] */
undefined __stdcall Unwind@0054e144(void);

/* 0054e14f  lib  [eh] */
undefined __stdcall Unwind@0054e14f(void);

/* 0054e15a  lib  [eh] */
undefined __stdcall Unwind@0054e15a(void);

/* 0054e165  lib  [eh] */
undefined __stdcall Unwind@0054e165(void);

/* 0054e170  lib  [eh] */
undefined __stdcall Unwind@0054e170(void);

/* 0054e17b  lib  [eh] */
undefined __stdcall Unwind@0054e17b(void);

/* 0054e186  lib  [eh] */
undefined __stdcall Unwind@0054e186(void);

/* 0054e191  lib  [eh] */
undefined __stdcall Unwind@0054e191(void);

/* 0054e19c  lib  [eh] */
undefined __stdcall Unwind@0054e19c(void);

/* 0054e1a7  lib  [eh] */
undefined __stdcall Unwind@0054e1a7(void);

/* 0054e1b2  lib  [eh] */
undefined __stdcall Unwind@0054e1b2(void);

/* 0054e1bd  lib  [eh] */
undefined __stdcall Unwind@0054e1bd(void);

/* 0054e1c8  lib  [eh] */
undefined __stdcall Unwind@0054e1c8(void);

/* 0054e1d3  lib  [eh] */
undefined __stdcall Unwind@0054e1d3(void);

/* 0054e1de  lib  [eh] */
undefined __stdcall Unwind@0054e1de(void);

/* 0054e1e9  lib  [eh] */
undefined __stdcall Unwind@0054e1e9(void);

/* 0054e1f4  lib  [eh] */
undefined __stdcall Unwind@0054e1f4(void);

/* 0054e1ff  lib  [eh] */
undefined __stdcall Unwind@0054e1ff(void);

/* 0054e20a  lib  [eh] */
undefined __stdcall Unwind@0054e20a(void);

/* 0054e215  lib  [eh] */
undefined __stdcall Unwind@0054e215(void);

/* 0054e220  lib  [eh] */
undefined __stdcall Unwind@0054e220(void);

/* 0054e22b  lib  [eh] */
undefined __stdcall Unwind@0054e22b(void);

/* 0054e236  lib  [eh] */
undefined __stdcall Unwind@0054e236(void);

/* 0054e241  lib  [eh] */
undefined __stdcall Unwind@0054e241(void);

/* 0054e24c  lib  [eh] */
undefined __stdcall Unwind@0054e24c(void);

/* 0054e257  lib  [eh] */
undefined __stdcall Unwind@0054e257(void);

/* 0054e262  lib  [eh] */
undefined __stdcall Unwind@0054e262(void);

/* 0054e26d  lib  [eh] */
undefined __stdcall Unwind@0054e26d(void);

/* 0054e278  lib  [eh] */
undefined __stdcall Unwind@0054e278(void);

/* 0054e283  lib  [eh] */
undefined __stdcall Unwind@0054e283(void);

/* 0054e28e  lib  [eh] */
undefined __stdcall Unwind@0054e28e(void);

/* 0054e299  lib  [eh] */
undefined __stdcall Unwind@0054e299(void);

/* 0054e2a4  lib  [eh] */
undefined __stdcall Unwind@0054e2a4(void);

/* 0054e2af  lib  [eh] */
undefined __stdcall Unwind@0054e2af(void);

/* 0054e2ba  lib  [eh] */
undefined __stdcall Unwind@0054e2ba(void);

/* 0054e2c5  lib  [eh] */
undefined __stdcall Unwind@0054e2c5(void);

/* 0054e2d0  lib  [eh] */
undefined __stdcall Unwind@0054e2d0(void);

/* 0054e2db  lib  [eh] */
undefined __stdcall Unwind@0054e2db(void);

/* 0054e2e6  lib  [eh] */
undefined __stdcall Unwind@0054e2e6(void);

/* 0054e2f1  lib  [eh] */
undefined __stdcall Unwind@0054e2f1(void);

/* 0054e2fc  lib  [eh] */
undefined __stdcall Unwind@0054e2fc(void);

/* 0054e307  lib  [eh] */
undefined __stdcall Unwind@0054e307(void);

/* 0054e312  lib  [eh] */
undefined __stdcall Unwind@0054e312(void);

/* 0054e31d  lib  [eh] */
undefined __stdcall Unwind@0054e31d(void);

/* 0054e328  lib  [eh] */
undefined __stdcall Unwind@0054e328(void);

/* 0054e333  lib  [eh] */
undefined __stdcall Unwind@0054e333(void);

/* 0054e33e  lib  [eh] */
undefined __stdcall Unwind@0054e33e(void);

/* 0054e349  lib  [eh] */
undefined __stdcall Unwind@0054e349(void);

/* 0054e354  lib  [eh] */
undefined __stdcall Unwind@0054e354(void);

/* 0054e35f  lib  [eh] */
undefined __stdcall Unwind@0054e35f(void);

/* 0054e36a  lib  [eh] */
undefined __stdcall Unwind@0054e36a(void);

/* 0054e375  lib  [eh] */
undefined __stdcall Unwind@0054e375(void);

/* 0054e380  lib  [eh] */
undefined __stdcall Unwind@0054e380(void);

/* 0054e38b  lib  [eh] */
undefined __stdcall Unwind@0054e38b(void);

/* 0054e396  lib  [eh] */
undefined __stdcall Unwind@0054e396(void);

/* 0054e3a1  lib  [eh] */
undefined __stdcall Unwind@0054e3a1(void);

/* 0054e3ac  lib  [eh] */
undefined __stdcall Unwind@0054e3ac(void);

/* 0054e3b7  lib  [eh] */
undefined __stdcall Unwind@0054e3b7(void);

/* 0054e3c2  lib  [eh] */
undefined __stdcall Unwind@0054e3c2(void);

/* 0054e3cd  lib  [eh] */
undefined __stdcall Unwind@0054e3cd(void);

/* 0054e3d8  lib  [eh] */
undefined __stdcall Unwind@0054e3d8(void);

/* 0054e3e3  lib  [eh] */
undefined __stdcall Unwind@0054e3e3(void);

/* 0054e3ee  lib  [eh] */
undefined __stdcall Unwind@0054e3ee(void);

/* 0054e3f9  lib  [eh] */
undefined __stdcall Unwind@0054e3f9(void);

/* 0054e404  lib  [eh] */
undefined __stdcall Unwind@0054e404(void);

/* 0054e40f  lib  [eh] */
undefined __stdcall Unwind@0054e40f(void);

/* 0054e41a  lib  [eh] */
undefined __stdcall Unwind@0054e41a(void);

/* 0054e425  lib  [eh] */
undefined __stdcall Unwind@0054e425(void);

/* 0054e430  lib  [eh] */
undefined __stdcall Unwind@0054e430(void);

/* 0054e43b  lib  [eh] */
undefined __stdcall Unwind@0054e43b(void);

/* 0054e446  lib  [eh] */
undefined __stdcall Unwind@0054e446(void);

/* 0054e451  lib  [eh] */
undefined __stdcall Unwind@0054e451(void);

/* 0054e45c  lib  [eh] */
undefined __stdcall Unwind@0054e45c(void);

/* 0054e467  lib  [eh] */
undefined __stdcall Unwind@0054e467(void);

/* 0054e472  lib  [eh] */
undefined __stdcall Unwind@0054e472(void);

/* 0054e47d  lib  [eh] */
undefined __stdcall Unwind@0054e47d(void);

/* 0054e488  lib  [eh] */
undefined __stdcall Unwind@0054e488(void);

/* 0054e493  lib  [eh] */
undefined __stdcall Unwind@0054e493(void);

/* 0054e49e  lib  [eh] */
undefined __stdcall Unwind@0054e49e(void);

/* 0054e4a9  lib  [eh] */
undefined __stdcall Unwind@0054e4a9(void);

/* 0054e4b4  lib  [eh] */
undefined __stdcall Unwind@0054e4b4(void);

/* 0054e4bf  lib  [eh] */
undefined __stdcall Unwind@0054e4bf(void);

/* 0054e4ca  lib  [eh] */
undefined __stdcall Unwind@0054e4ca(void);

/* 0054e4d5  lib  [eh] */
undefined __stdcall Unwind@0054e4d5(void);

/* 0054e4e0  lib  [eh] */
undefined __stdcall Unwind@0054e4e0(void);

/* 0054e4eb  lib  [eh] */
undefined __stdcall Unwind@0054e4eb(void);

/* 0054e4f6  lib  [eh] */
undefined __stdcall Unwind@0054e4f6(void);

/* 0054e501  lib  [eh] */
undefined __stdcall Unwind@0054e501(void);

/* 0054e50c  lib  [eh] */
undefined __stdcall Unwind@0054e50c(void);

/* 0054e517  lib  [eh] */
undefined __stdcall Unwind@0054e517(void);

/* 0054e522  lib  [eh] */
undefined __stdcall Unwind@0054e522(void);

/* 0054e52d  lib  [eh] */
undefined __stdcall Unwind@0054e52d(void);

/* 0054e538  lib  [eh] */
undefined __stdcall Unwind@0054e538(void);

/* 0054e543  lib  [eh] */
undefined __stdcall Unwind@0054e543(void);

/* 0054e54e  lib  [eh] */
undefined __stdcall Unwind@0054e54e(void);

/* 0054e559  lib  [eh] */
undefined __stdcall Unwind@0054e559(void);

/* 0054e564  lib  [eh] */
undefined __stdcall Unwind@0054e564(void);

/* 0054e56f  lib  [eh] */
undefined __stdcall Unwind@0054e56f(void);

/* 0054e57a  lib  [eh] */
undefined __stdcall Unwind@0054e57a(void);

/* 0054e585  lib  [eh] */
undefined __stdcall Unwind@0054e585(void);

/* 0054e590  lib  [eh] */
undefined __stdcall Unwind@0054e590(void);

/* 0054e59b  lib  [eh] */
undefined __stdcall Unwind@0054e59b(void);

/* 0054e5a6  lib  [eh] */
undefined __stdcall Unwind@0054e5a6(void);

/* 0054e5b1  lib  [eh] */
undefined __stdcall Unwind@0054e5b1(void);

/* 0054e5bc  lib  [eh] */
undefined __stdcall Unwind@0054e5bc(void);

/* 0054e5c7  lib  [eh] */
undefined __stdcall Unwind@0054e5c7(void);

/* 0054e5d2  lib  [eh] */
undefined __stdcall Unwind@0054e5d2(void);

/* 0054e5dd  lib  [eh] */
undefined __stdcall Unwind@0054e5dd(void);

/* 0054e5e8  lib  [eh] */
undefined __stdcall Unwind@0054e5e8(void);

/* 0054e5f3  lib  [eh] */
undefined __stdcall Unwind@0054e5f3(void);

/* 0054e5fe  lib  [eh] */
undefined __stdcall Unwind@0054e5fe(void);

/* 0054e609  lib  [eh] */
undefined __stdcall Unwind@0054e609(void);

/* 0054e614  lib  [eh] */
undefined __stdcall Unwind@0054e614(void);

/* 0054e61f  lib  [eh] */
undefined __stdcall Unwind@0054e61f(void);

/* 0054e62a  lib  [eh] */
undefined __stdcall Unwind@0054e62a(void);

/* 0054e635  lib  [eh] */
undefined __stdcall Unwind@0054e635(void);

/* 0054e640  lib  [eh] */
undefined __stdcall Unwind@0054e640(void);

/* 0054e64b  lib  [eh] */
undefined __stdcall Unwind@0054e64b(void);

/* 0054e656  lib  [eh] */
undefined __stdcall Unwind@0054e656(void);

/* 0054e661  lib  [eh] */
undefined __stdcall Unwind@0054e661(void);

/* 0054e66c  lib  [eh] */
undefined __stdcall Unwind@0054e66c(void);

/* 0054e677  lib  [eh] */
undefined __stdcall Unwind@0054e677(void);

/* 0054e682  lib  [eh] */
undefined __stdcall Unwind@0054e682(void);

/* 0054e68d  lib  [eh] */
undefined __stdcall Unwind@0054e68d(void);

/* 0054e698  lib  [eh] */
undefined __stdcall Unwind@0054e698(void);

/* 0054e6a3  lib  [eh] */
undefined __stdcall Unwind@0054e6a3(void);

/* 0054e6ae  lib  [eh] */
undefined __stdcall Unwind@0054e6ae(void);

/* 0054e6b9  lib  [eh] */
undefined __stdcall Unwind@0054e6b9(void);

/* 0054e6c4  lib  [eh] */
undefined __stdcall Unwind@0054e6c4(void);

/* 0054e6cf  lib  [eh] */
undefined __stdcall Unwind@0054e6cf(void);

/* 0054e6da  lib  [eh] */
undefined __stdcall Unwind@0054e6da(void);

/* 0054e6e5  lib  [eh] */
undefined __stdcall Unwind@0054e6e5(void);

/* 0054e6f0  lib  [eh] */
undefined __stdcall Unwind@0054e6f0(void);

/* 0054e6fb  lib  [eh] */
undefined __stdcall Unwind@0054e6fb(void);

/* 0054e706  lib  [eh] */
undefined __stdcall Unwind@0054e706(void);

/* 0054e711  lib  [eh] */
undefined __stdcall Unwind@0054e711(void);

/* 0054e71c  lib  [eh] */
undefined __stdcall Unwind@0054e71c(void);

/* 0054e727  lib  [eh] */
undefined __stdcall Unwind@0054e727(void);

/* 0054e732  lib  [eh] */
undefined __stdcall Unwind@0054e732(void);

/* 0054e73d  lib  [eh] */
undefined __stdcall Unwind@0054e73d(void);

/* 0054e748  lib  [eh] */
undefined __stdcall Unwind@0054e748(void);

/* 0054e753  lib  [eh] */
undefined __stdcall Unwind@0054e753(void);

/* 0054e75e  lib  [eh] */
undefined __stdcall Unwind@0054e75e(void);

/* 0054e769  lib  [eh] */
undefined __stdcall Unwind@0054e769(void);

/* 0054e774  lib  [eh] */
undefined __stdcall Unwind@0054e774(void);

/* 0054e77f  lib  [eh] */
undefined __stdcall Unwind@0054e77f(void);

/* 0054e78a  lib  [eh] */
undefined __stdcall Unwind@0054e78a(void);

/* 0054e795  lib  [eh] */
undefined __stdcall Unwind@0054e795(void);

/* 0054e7a0  lib  [eh] */
undefined __stdcall Unwind@0054e7a0(void);

/* 0054e7ab  lib  [eh] */
undefined __stdcall Unwind@0054e7ab(void);

/* 0054e7b6  lib  [eh] */
undefined __stdcall Unwind@0054e7b6(void);

/* 0054e7c1  lib  [eh] */
undefined __stdcall Unwind@0054e7c1(void);

/* 0054e7cc  lib  [eh] */
undefined __stdcall Unwind@0054e7cc(void);

/* 0054e7d7  lib  [eh] */
undefined __stdcall Unwind@0054e7d7(void);

/* 0054e7e2  lib  [eh] */
undefined __stdcall Unwind@0054e7e2(void);

/* 0054e7ed  lib  [eh] */
undefined __stdcall Unwind@0054e7ed(void);

/* 0054e7f8  lib  [eh] */
undefined __stdcall Unwind@0054e7f8(void);

/* 0054e803  lib  [eh] */
undefined __stdcall Unwind@0054e803(void);

/* 0054e80e  lib  [eh] */
undefined __stdcall Unwind@0054e80e(void);

/* 0054e819  lib  [eh] */
undefined __stdcall Unwind@0054e819(void);

/* 0054e824  lib  [eh] */
undefined __stdcall Unwind@0054e824(void);

/* 0054e82f  lib  [eh] */
undefined __stdcall Unwind@0054e82f(void);

/* 0054e83a  lib  [eh] */
undefined __stdcall Unwind@0054e83a(void);

/* 0054e845  lib  [eh] */
undefined __stdcall Unwind@0054e845(void);

/* 0054e850  lib  [eh] */
undefined __stdcall Unwind@0054e850(void);

/* 0054e85b  lib  [eh] */
undefined __stdcall Unwind@0054e85b(void);

