// imports (_library) -- server. 92 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00416940  lib  [import-ns] */
void __cdecl free(void * _Memory);

/* 0054a512  lib  [import-ns] */
undefined inflate(void);

/* 0054a518  lib  [import-ns] */
undefined inflateEnd(void);

/* 0054a51e  lib  [import-ns] */
undefined compress(void);

/* 0054a524  lib  [import-ns] */
undefined inflateInit_(void);

/* 0054a52a  lib  [import-ns] */
int __stdcall recv(SOCKET s, char * buf, int len, int flags);

/* 0054a530  lib  [import-ns] */
int __stdcall send(SOCKET s, char * buf, int len, int flags);

/* 0054a536  lib  [import-ns] */
SOCKET __stdcall accept(SOCKET s, sockaddr * addr, int * addrlen);

/* 0054a53c  lib  [import-ns] */
int __stdcall bind(SOCKET s, sockaddr * addr, int namelen);

/* 0054a542  lib  [import-ns] */
int __stdcall closesocket(SOCKET s);

/* 0054a548  lib  [import-ns] */
u_short __stdcall htons(u_short hostshort);

/* 0054a54e  lib  [import-ns] */
int __stdcall listen(SOCKET s, int backlog);

/* 0054a554  lib  [import-ns] */
SOCKET __stdcall socket(int af, int type, int protocol);

/* 0054a55a  lib  [import-ns] */
int __stdcall WSAStartup(WORD wVersionRequired, LPWSADATA lpWSAData);

/* 0054a560  lib  [import-ns] */
int __stdcall WSACleanup(void);

/* 0054a56c  lib  [import-ns] */
void __stdcall Sleep(DWORD dwMilliseconds);

/* 0054a572  lib  [import-ns] */
BOOL __stdcall DeleteFileA(LPCSTR lpFileName);

/* 0054a578  lib  [import-ns] */
BOOL __stdcall AreFileApisANSI(void);

/* 0054a57e  lib  [import-ns] */
void __stdcall GetSystemTime(LPSYSTEMTIME lpSystemTime);

/* 0054a584  lib  [import-ns] */
HLOCAL __stdcall LocalFree(HLOCAL hMem);

/* 0054a58a  lib  [import-ns] */
DWORD __stdcall GetTempPathA(DWORD nBufferLength, LPSTR lpBuffer);

/* 0054a590  lib  [import-ns] */
DWORD __stdcall GetCurrentProcessId(void);

/* 0054a596  lib  [import-ns] */
BOOL __stdcall DeleteFileW(LPCWSTR lpFileName);

/* 0054a59c  lib  [import-ns] */
BOOL __stdcall CloseHandle(HANDLE hObject);

/* 0054a5a2  lib  [import-ns] */
BOOL __stdcall GetVersionExA(LPOSVERSIONINFOA lpVersionInformation);

/* 0054a5ae  lib  [import-ns] */
BOOL __stdcall GetFileAttributesExW(LPCWSTR lpFileName, GET_FILEEX_INFO_LEVELS fInfoLevelId, LPVOID lpFileInformation);

/* 0054a5b4  lib  [import-ns] */
void __stdcall GetSystemInfo(LPSYSTEM_INFO lpSystemInfo);

/* 0054a5c0  lib  [import-ns] */
HANDLE __stdcall CreateFileMappingW(HANDLE hFile, LPSECURITY_ATTRIBUTES lpFileMappingAttributes, DWORD flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPCWSTR lpName);

/* 0054a5cc  lib  [import-ns] */
HMODULE __stdcall LoadLibraryA(LPCSTR lpLibFileName);

/* 0054a5d8  lib  [import-ns] */
BOOL __stdcall LockFileEx(HANDLE hFile, DWORD dwFlags, DWORD dwReserved, DWORD nNumberOfBytesToLockLow, DWORD nNumberOfBytesToLockHigh, LPOVERLAPPED lpOverlapped);

/* 0054a5e4  lib  [import-ns] */
FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName);

/* 0054a5ea  lib  [import-ns] */
DWORD __stdcall GetLastError(void);

/* 0054a5f0  lib  [import-ns] */
DWORD __stdcall GetTempPathW(DWORD nBufferLength, LPWSTR lpBuffer);

/* 0054a5f6  lib  [import-ns] */
BOOL __stdcall FlushFileBuffers(HANDLE hFile);

/* 0054a5fc  lib  [import-ns] */
int __stdcall MultiByteToWideChar(UINT CodePage, DWORD dwFlags, LPCSTR lpMultiByteStr, int cbMultiByte, LPWSTR lpWideCharStr, int cchWideChar);

/* 0054a602  lib  [import-ns] */
HANDLE __stdcall CreateFileW(LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);

/* 0054a608  lib  [import-ns] */
BOOL __stdcall ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);

/* 0054a60e  lib  [import-ns] */
DWORD __stdcall GetFileAttributesW(LPCWSTR lpFileName);

/* 0054a620  lib  [import-ns] */
DWORD __stdcall GetFileAttributesA(LPCSTR lpFileName);

/* 0054a62c  lib  [import-ns] */
DWORD __stdcall FormatMessageW(DWORD dwFlags, LPCVOID lpSource, DWORD dwMessageId, DWORD dwLanguageId, LPWSTR lpBuffer, DWORD nSize, va_list * Arguments);

/* 0054a632  lib  [import-ns] */
HMODULE __stdcall LoadLibraryW(LPCWSTR lpLibFileName);

/* 0054a638  lib  [import-ns] */
int __stdcall WideCharToMultiByte(UINT CodePage, DWORD dwFlags, LPCWSTR lpWideCharStr, int cchWideChar, LPSTR lpMultiByteStr, int cbMultiByte, LPCSTR lpDefaultChar, LPBOOL lpUsedDefaultChar);

/* 0054a63e  lib  [import-ns] */
BOOL __stdcall WriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);

/* 0054a644  lib  [import-ns] */
DWORD __stdcall FormatMessageA(DWORD dwFlags, LPCVOID lpSource, DWORD dwMessageId, DWORD dwLanguageId, LPSTR lpBuffer, DWORD nSize, va_list * Arguments);

/* 0054a64a  lib  [import-ns] */
void __stdcall GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime);

/* 0054a656  lib  [import-ns] */
BOOL __stdcall UnlockFileEx(HANDLE hFile, DWORD dwReserved, DWORD nNumberOfBytesToUnlockLow, DWORD nNumberOfBytesToUnlockHigh, LPOVERLAPPED lpOverlapped);

/* 0054a65c  lib  [import-ns] */
DWORD __stdcall GetTickCount(void);

/* 0054a668  lib  [import-ns] */
BOOL __stdcall LockFile(HANDLE hFile, DWORD dwFileOffsetLow, DWORD dwFileOffsetHigh, DWORD nNumberOfBytesToLockLow, DWORD nNumberOfBytesToLockHigh);

/* 0054a66e  lib  [import-ns] */
BOOL __stdcall UnlockFile(HANDLE hFile, DWORD dwFileOffsetLow, DWORD dwFileOffsetHigh, DWORD nNumberOfBytesToUnlockLow, DWORD nNumberOfBytesToUnlockHigh);

/* 0054a67a  lib  [import-ns] */
BOOL __stdcall QueryPerformanceCounter(LARGE_INTEGER * lpPerformanceCount);

/* 0054a68c  lib  [import-ns] */
BOOL __stdcall FreeLibrary(HMODULE hLibModule);

/* 0054a692  lib  [import-ns] */
BOOL __stdcall SetEndOfFile(HANDLE hFile);

/* 0054a698  lib  [import-ns] */
BOOL __stdcall UnmapViewOfFile(LPCVOID lpBaseAddress);

/* 0054a69e  lib  [import-ns] */
LPVOID __stdcall MapViewOfFile(HANDLE hFileMappingObject, DWORD dwDesiredAccess, DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow, SIZE_T dwNumberOfBytesToMap);

/* 0054a6a4  lib  [import-ns] */
DWORD __stdcall SetFilePointer(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod);

/* 0054a6b0  lib  [import-ns] */
DWORD __stdcall GetFileSize(HANDLE hFile, LPDWORD lpFileSizeHigh);

/* 0054a6b6  lib  [import-ns] */
HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);

/* 0054a6c2  lib  [import-ns] */
DWORD __stdcall GetFullPathNameA(LPCSTR lpFileName, DWORD nBufferLength, LPSTR lpBuffer, LPSTR * lpFilePart);

/* 0054a6c8  lib  [import-ns] */
DWORD __stdcall GetFullPathNameW(LPCWSTR lpFileName, DWORD nBufferLength, LPWSTR lpBuffer, LPWSTR * lpFilePart);

/* 0054a7b0  lib  [import-ns] */
undefined __cdecl purecall(void);

/* 0054a7b6  lib  [import-ns] */
void * __cdecl operator_new(uint param_1);

/* 0054a7bc  lib  [import-ns] */
void __cdecl operator_delete(void * param_1);

/* 0054a8c8  lib  [import-ns] */
noreturn void __stdcall _CxxThrowException(void * pExceptionObject, ThrowInfo * pThrowInfo);

/* 0054a8ce  lib  [import-ns] */
noreturn undefined __CxxFrameHandler3(void);

/* 0054a9bc  lib  [import-ns] */
undefined __cdecl libm_sse2_asin_precise(void);

/* 0054a9c2  lib  [import-ns] */
undefined __cdecl libm_sse2_cos_precise(void);

/* 0054a9c8  lib  [import-ns] */
undefined __cdecl libm_sse2_sin_precise(void);

/* 0054a9ce  lib  [import-ns] */
undefined __cdecl libm_sse2_sqrt_precise(void);

/* 0054a9d4  lib  [import-ns] */
void * __cdecl memcpy(void * _Dst, void * _Src, size_t _Size);

/* 0054ab14  lib  [import-ns] */
undefined __cdecl libm_sse2_pow_precise(void);

/* 0054ab1a  lib  [import-ns] */
void * __cdecl memset(void * _Dst, int _Val, size_t _Size);

/* 0054ab20  lib  [import-ns] */
undefined __cdecl setjmp3(void);

/* 0054ad3c  lib  [import-ns] */
void __cdecl operator_delete[](void * param_1);

/* 0054b1d6  lib  [import-ns] */
undefined __cdecl libm_sse2_acos_precise(void);

/* 0054b1dc  lib  [import-ns] */
undefined __cdecl libm_sse2_exp_precise(void);

/* 0054b456  lib  [import-ns] */
void __cdecl _lock(int _File);

/* 0054b45c  lib  [import-ns] */
void __cdecl _unlock(int _File);

/* 0054b462  lib  [import-ns] */
undefined __dllonexit(void);

/* 0054b626  lib  [import-ns] */
void __thiscall ~type_info(type_info * this);

/* 0054b62c  lib  [import-ns] */
void __cdecl _crt_debugger_hook(int param_1);

/* 0054b632  lib  [import-ns] */
LONG __cdecl __crtUnhandledException(EXCEPTION_POINTERS * exceptionInfo);

/* 0054b638  lib  [import-ns] */
void __cdecl __crtTerminateProcess(UINT uExitCode);

/* 0054b63e  lib  [import-ns] */
noreturn void __cdecl terminate(void);

/* 0054b694  lib  [import-ns] */
int __cdecl _XcptFilter(ulong _ExceptionNum, _EXCEPTION_POINTERS * _ExceptionPtr);

/* 0054b69a  lib  [import-ns] */
void __cdecl _amsg_exit(int param_1);

/* 0054b8f2  lib  [import-ns] */
undefined __cdecl initterm_e(void);

/* 0054b8f8  lib  [import-ns] */
undefined __cdecl initterm(void);

/* 0054b8fe  lib  [import-ns] */
undefined __cdecl except_handler4_common(void);

/* 0054b904  lib  [import-ns] */
void __cdecl __crtSetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER exceptionFilter);

/* 0054b90a  lib  [import-ns] */
noreturn void __cdecl _invoke_watson(wchar_t * param_1, wchar_t * param_2, wchar_t * param_3, uint param_4, uintptr_t param_5);

/* 0054b910  lib  [import-ns] */
errno_t __cdecl _controlfp_s(uint * _CurrentState, uint _NewValue, uint _Mask);

/* 0054b916  lib  [import-ns] */
BOOL __stdcall IsProcessorFeaturePresent(DWORD ProcessorFeature);

