// sqlite_00 (_library) -- server. 200 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00413010  lib  [lib-string] */
undefined4 __thiscall FUN_00413010(void * this, int * param_1);

/* 0045f250  lib  [lib-island] */
ulonglong __cdecl FUN_0045f250(int param_1);

/* 0045fb30  lib  [lib-string] */
undefined __cdecl FUN_0045fb30(int param_1, uint param_2);

/* 0045fc30  lib  [lib-island] */
undefined __cdecl FUN_0045fc30(int param_1, undefined4 param_2, undefined4 param_3);

/* 0045fc90  lib  [lib-island] */
undefined __cdecl FUN_0045fc90(int param_1);

/* 00460d50  lib  [lib-string] */
undefined __cdecl FUN_00460d50(int param_1, undefined4 param_2, undefined4 * param_3);

/* 00462d70  lib  [lib-string] */
undefined4 __cdecl FUN_00462d70(byte * param_1);

/* 00462e80  lib  [lib-island] */
undefined * __cdecl FUN_00462e80(uint param_1);

/* 00463120  lib  [lib-island] */
uint __cdecl FUN_00463120(int param_1, byte * param_2, undefined * param_3, undefined4 param_4, int * param_5);

/* 004636f0  lib  [lib-island] */
undefined __cdecl FUN_004636f0(int param_1);

/* 00464420  lib  [lib-string] */
uint __cdecl FUN_00464420(uint param_1, byte * param_2, byte * param_3, byte * param_4, int param_5, int param_6, int param_7, undefined4 * param_8);

/* 00464e80  lib  [lib-island] */
int __cdecl FUN_00464e80(byte * param_1);

/* 004650e0  lib  [lib-island] */
undefined __cdecl FUN_004650e0(int param_1);

/* 00465120  lib  [lib-island] */
undefined __cdecl FUN_00465120(int param_1);

/* 00465320  lib  [lib-island] */
undefined4 __cdecl FUN_00465320(int param_1, byte * param_2, int param_3, undefined4 * param_4);

/* 00466210  lib  [lib-island] */
undefined4 __cdecl FUN_00466210(int param_1, int param_2);

/* 004666d0  lib  [lib-island] */
undefined4 __cdecl FUN_004666d0(byte * param_1);

/* 00466700  lib  [lib-island] */
undefined __cdecl FUN_00466700(byte * param_1, double * param_2);

/* 00466a80  lib  [lib-island] */
undefined __cdecl FUN_00466a80(int param_1, undefined4 param_2, byte * param_3);

/* 00466dd0  lib  [lib-island] */
undefined __cdecl FUN_00466dd0(int param_1);

/* 00466fa0  lib  [lib-island] */
undefined __cdecl FUN_00466fa0(int param_1, undefined1 * param_2);

/* 004673c0  lib  [lib-island] */
uint __cdecl FUN_004673c0(int * param_1, int param_2);

/* 00467dc0  lib  [lib-island] */
int __cdecl FUN_00467dc0(int * param_1);

/* 00468070  lib  [lib-island] */
undefined __cdecl FUN_00468070(int param_1, undefined4 param_2, int * param_3);

/* 00468380  lib  [lib-island] */
int __cdecl FUN_00468380(byte * param_1, byte * param_2, int param_3);

/* 004683f0  lib  [lib-island] */
undefined __cdecl FUN_004683f0(undefined4 param_1, undefined4 param_2);

/* 00468600  lib  [lib-island] */
undefined4 __cdecl FUN_00468600(int param_1, int param_2);

/* 00468670  lib  [lib-island] */
uint __cdecl FUN_00468670(int param_1);

/* 004687f0  lib  [lib-string] */
char * __cdecl FUN_004687f0(int param_1);

/* 00469a30  lib  [lib-island] */
int __cdecl FUN_00469a30(int * param_1, int param_2);

/* 00469cb0  lib  [lib-island] */
uint __cdecl FUN_00469cb0(uint * param_1);

/* 0046aa30  lib  [lib-island] */
uint __cdecl FUN_0046aa30(int * param_1);

/* 0046aab0  lib  [lib-island] */
uint __cdecl FUN_0046aab0(int * param_1);

/* 0046b2f0  lib  [lib-island] */
uint __cdecl FUN_0046b2f0(int param_1, uint param_2, size_t param_3, void * param_4, int param_5);

/* 0046b630  lib  [lib-island] */
char * __cdecl FUN_0046b630(undefined1 param_1);

/* 0046b680  lib  [lib-island] */
undefined __cdecl FUN_0046b680(int * param_1);

/* 0046b6f0  lib  [lib-island] */
undefined __cdecl FUN_0046b6f0(int param_1, int param_2, undefined4 * param_3);

/* 0046b780  lib  [lib-island] */
uint __cdecl FUN_0046b780(int param_1, uint param_2);

/* 0046b9f0  lib  [lib-island] */
undefined __cdecl FUN_0046b9f0(int * param_1, int param_2, int param_3, uint param_4, int param_5, uint param_6, int param_7, undefined4 * param_8);

/* 0046bae0  lib  [lib-island] */
uint __cdecl FUN_0046bae0(int * param_1, int * param_2, uint * param_3, undefined4 * param_4, char param_5);

/* 0046c260  lib  [lib-island] */
undefined4 * __cdecl FUN_0046c260(int * param_1, int param_2, int param_3, undefined4 param_4, int param_5);

/* 0046c340  lib  [lib-string] */
int * __cdecl FUN_0046c340(undefined4 * param_1);

/* 0046c4b0  lib  [lib-island] */
int __cdecl FUN_0046c4b0(uint param_1, int param_2, int * param_3);

/* 0046c6a0  lib  [lib-island] */
undefined __cdecl FUN_0046c6a0(int param_1);

/* 0046ca90  lib  [lib-island] */
undefined __cdecl FUN_0046ca90(int * param_1, int param_2);

/* 0046cc20  lib  [lib-island] */
undefined __cdecl FUN_0046cc20(int * param_1, int * param_2, undefined4 * param_3, undefined4 param_4, int param_5);

/* 0046dec0  lib  [lib-island] */
undefined __cdecl FUN_0046dec0(int * param_1, int * param_2, int * param_3);

/* 0046dfa0  lib  [lib-island] */
undefined __cdecl FUN_0046dfa0(int param_1);

/* 0046e020  lib  [lib-island] */
undefined __cdecl FUN_0046e020(int param_1, int param_2, int param_3, int param_4);

/* 0046e0c0  lib  [lib-island] */
int __cdecl FUN_0046e0c0(int * param_1, int param_2, int param_3);

/* 0046e140  lib  [lib-island] */
undefined __cdecl FUN_0046e140(int param_1, int param_2, undefined4 param_3);

/* 0046e160  lib  [lib-island] */
uint __cdecl FUN_0046e160(int * param_1);

/* 0046e390  lib  [lib-island] */
uint __cdecl FUN_0046e390(int param_1, undefined4 * param_2, int param_3);

/* 0046e520  lib  [lib-island] */
undefined __cdecl FUN_0046e520(int param_1);

/* 0046e6b0  lib  [lib-island] */
int * __cdecl FUN_0046e6b0(int * param_1, undefined4 * param_2);

/* 0046e7e0  lib  [lib-island] */
undefined __cdecl FUN_0046e7e0(char * param_1, undefined1 * param_2, int param_3, int param_4, int param_5);

/* 0046f6f0  lib  [lib-island] */
uint __cdecl FUN_0046f6f0(uint param_1, uint param_2, undefined1 * param_3);

/* 004709a0  lib  [lib-island] */
undefined __cdecl FUN_004709a0(int * param_1, char * param_2, undefined1 * param_3, undefined1 param_4);

/* 00470ba0  lib  [lib-island] */
uint __cdecl FUN_00470ba0(int param_1, undefined4 param_2, undefined4 param_3, undefined4 * param_4);

/* 00470d20  lib  [lib-island] */
char * __cdecl FUN_00470d20(undefined4 * param_1, undefined4 * param_2, byte param_3);

/* 00470f80  lib  [lib-island] */
undefined4 __cdecl FUN_00470f80(int param_1, int param_2, int param_3, int param_4, int * param_5);

/* 00471000  lib  [lib-island] */
uint __cdecl FUN_00471000(undefined4 * param_1, char * param_2, uint * param_3);

/* 00471200  lib  [lib-island] */
undefined __cdecl FUN_00471200(int * param_1);

/* 004712c0  lib  [lib-island] */
int __cdecl FUN_004712c0(int * param_1, uint param_2, int * param_3, int param_4);

/* 00471320  lib  [lib-island] */
undefined4 __cdecl FUN_00471320(char * param_1);

/* 004715a0  lib  [lib-island] */
undefined __cdecl FUN_004715a0(int * param_1, byte * param_2, uint param_3, int param_4, int param_5, uint * param_6);

/* 004716b0  lib  [lib-island] */
int __cdecl FUN_004716b0(int * param_1, int param_2);

/* 00471710  lib  [lib-island] */
undefined __cdecl FUN_00471710(int param_1, uint param_2, uint * param_3);

/* 00471850  lib  [lib-island] */
int __cdecl FUN_00471850(int * param_1);

/* 004718a0  lib  [lib-island] */
uint __cdecl FUN_004718a0(int param_1, uint param_2);

/* 00471910  lib  [lib-island] */
undefined __cdecl FUN_00471910(int param_1, undefined4 param_2, char * param_3);

/* 00471aa0  lib  [lib-island] */
uint __cdecl FUN_00471aa0(uint param_1, int param_2);

/* 00471b70  lib  [lib-island] */
undefined4 __cdecl FUN_00471b70(int * param_1, byte * param_2);

/* 00471c20  lib  [lib-island] */
undefined __cdecl FUN_00471c20(int param_1, char * param_2, byte * param_3);

/* 00471c90  lib  [lib-island] */
undefined4 __cdecl FUN_00471c90(undefined4 * param_1, int * param_2);

/* 00471d80  lib  [lib-island] */
undefined __cdecl FUN_00471d80(int * param_1, int param_2, undefined4 * param_3, int param_4, char * param_5);

/* 00471f80  lib  [lib-island] */
undefined __cdecl FUN_00471f80(undefined4 * param_1, undefined4 * param_2, byte param_3, int param_4, char * param_5);

/* 00472010  lib  [lib-island] */
undefined4 __cdecl FUN_00472010(int param_1, uint param_2, char * param_3);

/* 00472090  lib  [lib-island] */
undefined __cdecl FUN_00472090(int * param_1, uint param_2, char * param_3, uint * param_4, uint * param_5);

/* 00472880  lib  [lib-island] */
undefined __cdecl FUN_00472880(int param_1);

/* 00472980  lib  [lib-island] */
uint __cdecl FUN_00472980(undefined1 * param_1, uint param_2);

/* 00472b70  lib  [lib-island] */
uint __cdecl FUN_00472b70(int * param_1, uint param_2, int param_3, int * param_4);

/* 00472d10  lib  [lib-island] */
undefined __cdecl FUN_00472d10(int param_1, undefined4 * param_2);

/* 00472d90  lib  [lib-island] */
undefined __cdecl FUN_00472d90(int * param_1);

/* 00473230  lib  [lib-island] */
undefined __cdecl FUN_00473230(int * param_1, int param_2, int * param_3, char * param_4, byte * param_5, byte * param_6, byte * param_7);

/* 004733e0  lib  [lib-island] */
int __cdecl FUN_004733e0(int * param_1, char * param_2, char * param_3, undefined1 param_4, undefined4 param_5, undefined4 param_6, undefined4 param_7, byte param_8);

/* 00473550  lib  [lib-island] */
undefined __cdecl FUN_00473550(int param_1, undefined4 param_2, undefined4 param_3, int * param_4, undefined4 param_5);

/* 00473790  lib  [lib-island] */
undefined __cdecl FUN_00473790(int param_1, int param_2, int param_3, undefined4 param_4);

/* 00473870  lib  [lib-island] */
undefined __cdecl FUN_00473870(int * param_1, int param_2, int param_3);

/* 00474a90  lib  [lib-island] */
undefined __cdecl FUN_00474a90(int * param_1, byte * param_2, int param_3, undefined4 param_4);

/* 00474bc0  lib  [lib-island] */
undefined __cdecl FUN_00474bc0(int * param_1);

/* 00474d00  lib  [lib-island] */
undefined __cdecl FUN_00474d00(int * param_1, char * param_2, int param_3);

/* 00474ee0  lib  [lib-island] */
undefined4 __cdecl FUN_00474ee0(byte * param_1, int param_2);

/* 00474f60  lib  [lib-island] */
int __cdecl FUN_00474f60(int param_1, byte * param_2);

/* 00474fe0  lib  [lib-island] */
undefined __cdecl FUN_00474fe0(int * param_1);

/* 00475040  lib  [lib-island] */
undefined * __cdecl FUN_00475040(int * param_1, int param_2);

/* 004750b0  lib  [lib-island] */
char * __cdecl FUN_004750b0(int * param_1, char * param_2, undefined4 * param_3, undefined4 * param_4, undefined4 * param_5);

/* 00475250  lib  [lib-island] */
char __cdecl FUN_00475250(int param_1);

/* 004754f0  lib  [lib-island] */
undefined __cdecl FUN_004754f0(int * param_1, int param_2, undefined4 param_3);

/* 004757a0  lib  [lib-island] */
undefined4 __cdecl FUN_004757a0(int param_1);

/* 00476130  lib  [lib-island] */
undefined __cdecl FUN_00476130(int param_1, char * param_2, uint * param_3);

/* 004761f0  lib  [lib-island] */
uint __cdecl FUN_004761f0(void * param_1, void * param_2, size_t param_3, int param_4, undefined4 * param_5);

/* 00476240  lib  [lib-string] */
undefined __cdecl FUN_00476240(int * param_1, undefined4 param_2, int param_3);

/* 004765c0  lib  [lib-string] */
char * __cdecl FUN_004765c0(int param_1, undefined4 * param_2);

/* 00476810  lib  [lib-island] */
undefined4 __cdecl FUN_00476810(int param_1, uint param_2);

/* 004768b0  lib  [lib-island] */
undefined4 __cdecl FUN_004768b0(uint param_1);

/* 00476a70  lib  [lib-string] */
undefined __cdecl FUN_00476a70(int * param_1, undefined4 param_2, undefined4 param_3);

/* 00476b80  lib  [lib-island] */
undefined __cdecl FUN_00476b80(int * param_1, int param_2);

/* 00476d20  lib  [lib-island] */
char * __cdecl FUN_00476d20(int param_1, char * param_2, int param_3);

/* 00476ff0  lib  [lib-island] */
int __cdecl FUN_00476ff0(int param_1);

/* 00477080  lib  [lib-island] */
ulonglong __cdecl FUN_00477080(double param_1);

/* 004770f0  lib  [lib-island] */
undefined __cdecl FUN_004770f0(int param_1, int param_2, size_t param_3, int * param_4);

/* 004771d0  lib  [lib-island] */
uint __cdecl FUN_004771d0(int param_1, uint param_2);

/* 00477240  lib  [lib-island] */
uint __cdecl FUN_00477240(int param_1, uint param_2);

/* 004773d0  lib  [lib-island] */
uint __cdecl FUN_004773d0(int param_1, int * param_2, void * param_3);

/* 00477530  lib  [lib-island] */
uint __cdecl FUN_00477530(int param_1, int * param_2, int * param_3);

/* 004775b0  lib  [lib-island] */
undefined __cdecl FUN_004775b0(int * param_1);

/* 00477b20  lib  [lib-island] */
undefined __cdecl FUN_00477b20(int * param_1);

/* 00477c30  lib  [lib-island] */
undefined __cdecl FUN_00477c30(int * param_1);

/* 00477d20  lib  [lib-island] */
bool __cdecl FUN_00477d20(char * param_1);

/* 00477d60  lib  [lib-island] */
undefined __cdecl FUN_00477d60(undefined4 param_1, undefined4 * param_2, int param_3);

/* 00478460  lib  [lib-island] */
undefined __cdecl FUN_00478460(undefined4 param_1, undefined4 * param_2, int param_3);

/* 004789f0  lib  [lib-island] */
undefined __cdecl FUN_004789f0(int param_1, int param_2, undefined4 param_3, int param_4, undefined4 param_5);

/* 00478b30  lib  [lib-island] */
undefined __cdecl FUN_00478b30(int * param_1, byte * param_2);

/* 00478bb0  lib  [lib-island] */
undefined4 * __cdecl FUN_00478bb0(int param_1, undefined4 * param_2, uint param_3, int * param_4);

/* 00478de0  lib  [lib-island] */
undefined8 __cdecl FUN_00478de0(undefined4 param_1, int * param_2);

/* 00478f40  lib  [lib-island] */
undefined8 __cdecl FUN_00478f40(undefined4 param_1, undefined4 * param_2);

/* 004790b0  lib  [lib-island] */
undefined __cdecl FUN_004790b0(int param_1);

/* 004791b0  lib  [lib-island] */
ulonglong __cdecl FUN_004791b0(int * param_1, char * param_2);

/* 00479240  lib  [lib-island] */
int __cdecl FUN_00479240(int param_1, uint * param_2, int param_3);

/* 004792d0  lib  [lib-island] */
int __cdecl FUN_004792d0(int param_1, int * param_2, int * param_3);

/* 00479360  lib  [lib-island] */
undefined __cdecl FUN_00479360(int param_1, undefined4 param_2, undefined8 * param_3, uint param_4, uint param_5);

/* 004793f0  lib  [lib-island] */
undefined __cdecl FUN_004793f0(int * param_1, int param_2, size_t param_3);

/* 004794b0  lib  [lib-island] */
uint * __cdecl FUN_004794b0(size_t param_1, uint * param_2, void * param_3, uint param_4, uint param_5, void * param_6, size_t param_7, size_t param_8, uint * param_9);

/* 00479800  lib  [lib-island] */
undefined __cdecl FUN_00479800(int param_1, int param_2);

/* 00479910  lib  [lib-string] */
undefined4 __cdecl FUN_00479910(int param_1, int param_2, byte * param_3);

/* 004799f0  lib  [lib-island] */
int * __cdecl FUN_004799f0(int param_1, byte * param_2, int param_3);

/* 00479af0  lib  [lib-island] */
undefined4 * __cdecl FUN_00479af0(int param_1, byte * param_2, int param_3, int param_4);

/* 00479b90  lib  [lib-island] */
int __cdecl FUN_00479b90(int * param_1, int * param_2, int param_3, int param_4, int param_5);

/* 00479c50  lib  [lib-island] */
int * __cdecl FUN_00479c50(undefined4 * param_1, int param_2, int param_3, uint param_4, uint param_5, ushort param_6, int param_7);

/* 00479db0  lib  [lib-string] */
uint * __cdecl FUN_00479db0(int * param_1, int param_2, int * param_3, int param_4);

/* 0047a7a0  lib  [lib-string] */
undefined __cdecl FUN_0047a7a0(int * param_1, int param_2, int * param_3, int param_4, int * param_5, int * param_6, int param_7, int param_8, int param_9);

/* 0047b540  lib  [lib-island] */
undefined __cdecl FUN_0047b540(int param_1, undefined4 * param_2);

/* 0047b5a0  lib  [lib-island] */
undefined4 __cdecl FUN_0047b5a0(int * param_1, byte * param_2, byte * param_3);

/* 0047b730  lib  [lib-island] */
undefined4 __cdecl FUN_0047b730(int * param_1, undefined4 * param_2, int param_3, int param_4, int param_5);

/* 0047bc80  lib  [lib-island] */
undefined __cdecl FUN_0047bc80(int param_1, undefined4 param_2, int * param_3);

/* 0047bd90  lib  [lib-island] */
undefined __cdecl FUN_0047bd90(undefined1 * param_1, uint * param_2);

/* 0047bdc0  lib  [lib-island] */
uint __cdecl FUN_0047bdc0(int * param_1, undefined1 * param_2, uint param_3);

/* 0047c0e0  lib  [lib-island] */
undefined4 __cdecl FUN_0047c0e0(int param_1, int param_2, size_t param_3);

/* 0047c340  lib  [lib-island] */
undefined __cdecl FUN_0047c340(int param_1);

/* 0047c360  lib  [lib-island] */
undefined __cdecl FUN_0047c360(int param_1, int param_2);

/* 0047c390  lib  [lib-island] */
int __cdecl FUN_0047c390(int param_1, int param_2, byte * param_3, int param_4);

/* 0047c420  lib  [lib-island] */
undefined __cdecl FUN_0047c420(int * param_1, short * param_2, int * param_3);

/* 0047c5d0  lib  [lib-island] */
undefined __cdecl FUN_0047c5d0(int param_1, int param_2, int * param_3);

/* 0047ca50  lib  [lib-island] */
undefined __cdecl FUN_0047ca50(int param_1, int param_2, int * param_3, int param_4, char * param_5);

/* 0047d000  lib  [lib-island] */
int __cdecl FUN_0047d000(int * param_1, uint param_2, int * param_3);

/* 0047d090  lib  [lib-island] */
uint __cdecl FUN_0047d090(byte * param_1);

/* 0047d150  lib  [lib-island] */
undefined __cdecl FUN_0047d150(int param_1);

/* 0047d3d0  lib  [lib-island] */
undefined4 __cdecl FUN_0047d3d0(byte * param_1);

/* 0047d410  lib  [lib-island] */
undefined8 __cdecl FUN_0047d410(int * param_1, int param_2);

/* 0047d460  lib  [lib-island] */
int __cdecl FUN_0047d460(int * param_1, undefined4 * param_2, int * param_3, undefined4 * param_4);

/* 0047d6f0  lib  [lib-island] */
int * __cdecl FUN_0047d6f0(int * param_1, int * param_2, int param_3, int param_4);

/* 0047da70  lib  [lib-island] */
uint __cdecl FUN_0047da70(byte * param_1, int param_2, byte param_3);

/* 0047de10  lib  [lib-island] */
undefined4 __cdecl FUN_0047de10(int * param_1);

/* 0047de90  lib  [lib-island] */
undefined4 __cdecl FUN_0047de90(int param_1);

/* 0047df00  lib  [lib-island] */
int __cdecl FUN_0047df00(int * param_1, uint * param_2);

/* 0047e090  lib  [lib-island] */
undefined __cdecl FUN_0047e090(int * param_1, int * param_2);

/* 0047e0d0  lib  [lib-island] */
undefined __cdecl FUN_0047e0d0(undefined4 * param_1, int * param_2);

/* 0047e150  lib  [lib-island] */
undefined __cdecl FUN_0047e150(int param_1, int * param_2, byte * param_3);

/* 0047e200  lib  [lib-island] */
undefined __cdecl FUN_0047e200(int * param_1, int param_2);

/* 0047e2a0  lib  [lib-island] */
undefined __cdecl FUN_0047e2a0(int param_1, int param_2);

/* 0047e2e0  lib  [lib-island] */
uint __cdecl FUN_0047e2e0(int * param_1, undefined4 * param_2, char * param_3);

/* 0047e6f0  lib  [lib-island] */
undefined __cdecl FUN_0047e6f0(uint param_1, int param_2, undefined1 * param_3, int param_4, undefined1 * param_5, int param_6, uint * param_7);

/* 0047e8a0  lib  [lib-island] */
undefined __cdecl FUN_0047e8a0(int param_1, int * param_2, int * param_3);

/* 0047e910  lib  [lib-island] */
undefined4 __cdecl FUN_0047e910(int * param_1);

/* 0047ea40  lib  [lib-island] */
bool __cdecl FUN_0047ea40(int * param_1);

/* 0047ed50  lib  [lib-island] */
undefined4 __cdecl FUN_0047ed50(int * param_1, short * param_2, undefined4 * param_3, int * param_4);

/* 0047ee40  lib  [lib-island] */
bool __cdecl FUN_0047ee40(int * param_1, char * param_2, int * param_3, int * param_4, uint * param_5);

/* 0047f140  lib  [lib-island] */
int __cdecl FUN_0047f140(int * param_1, int param_2);

/* 0047f4f0  lib  [lib-string] */
undefined4 __cdecl FUN_0047f4f0(int * param_1, byte * param_2);

/* 0047f590  lib  [lib-island] */
longlong __cdecl FUN_0047f590(int param_1);

/* 0047f5f0  lib  [lib-island] */
int * __cdecl FUN_0047f5f0(int * param_1, uint * param_2);

/* 0047f6a0  lib  [lib-island] */
undefined1 __cdecl FUN_0047f6a0(byte * param_1, uint param_2);

/* 0047f9a0  lib  [lib-island] */
undefined4 __cdecl FUN_0047f9a0(int * param_1, int param_2, int param_3, int * param_4, undefined4 * param_5);

/* 0047fa9a  lib  [lib-string] */
undefined4 __fastcall FUN_0047fa9a(undefined4 param_1, int param_2);

/* 0047fc00  lib  [lib-island] */
uint __cdecl FUN_0047fc00(int * param_1);

/* 0047ff80  lib  [lib-string] */
undefined4 __cdecl FUN_0047ff80(int * param_1, byte * param_2, byte * param_3, byte * param_4, int param_5, char * param_6);

/* 00480650  lib  [lib-island] */
uint __cdecl FUN_00480650(int param_1, int * param_2);

/* 004807d0  lib  [lib-island] */
char __cdecl FUN_004807d0(int * param_1);

/* 00480840  lib  [lib-island] */
undefined4 __cdecl FUN_00480840(char * param_1, int param_2, undefined4 param_3, char param_4);

/* 00480a70  lib  [lib-island] */
int __cdecl FUN_00480a70(int param_1, uint param_2);

/* 00480b10  lib  [lib-island] */
int __cdecl FUN_00480b10(int param_1);

/* 00480b90  lib  [lib-island] */
undefined __cdecl FUN_00480b90(int param_1);

/* 00480be0  lib  [lib-island] */
int __cdecl FUN_00480be0(int param_1);

/* 00480c70  lib  [lib-island] */
int __cdecl FUN_00480c70(int * param_1);

/* 00480e10  lib  [lib-island] */
undefined __cdecl FUN_00480e10(int * param_1, int * param_2, char * param_3);

/* 004815e0  lib  [lib-island] */
uint __cdecl FUN_004815e0(int * param_1, undefined4 * param_2, int param_3);

/* 00481630  lib  [lib-island] */
undefined __cdecl FUN_00481630(int * param_1, int * param_2, char * param_3);

/* 004832f0  lib  [lib-island] */
undefined4 __cdecl FUN_004832f0(undefined4 * param_1, byte * param_2);

/* 00483380  lib  [lib-island] */
uint __cdecl FUN_00483380(int param_1);

