// sqlite_01 (_library) -- server. 200 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00483490  lib  [lib-island] */
undefined8 __cdecl FUN_00483490(int param_1);

/* 00483950  lib  [lib-string] */
undefined __cdecl FUN_00483950(int * param_1, int param_2, undefined4 param_3, int param_4);

/* 00483b10  lib  [lib-island] */
undefined4 __cdecl FUN_00483b10(int * param_1);

/* 00483b70  lib  [lib-island] */
short __cdecl FUN_00483b70(int param_1);

/* 00483bd0  lib  [lib-island] */
int __cdecl FUN_00483bd0(int param_1);

/* 00483c40  lib  [lib-island] */
int __cdecl FUN_00483c40(int param_1);

/* 00483ca0  lib  [lib-island] */
int __cdecl FUN_00483ca0(int param_1, int param_2);

/* 00483cf0  lib  [lib-island] */
undefined __cdecl FUN_00483cf0(int * param_1);

/* 00483d40  lib  [lib-island] */
undefined __cdecl FUN_00483d40(int * param_1);

/* 00483dd0  lib  [lib-island] */
int __cdecl FUN_00483dd0(int param_1, uint * param_2);

/* 00483e60  lib  [lib-island] */
uint __cdecl FUN_00483e60(undefined4 * param_1, uint * param_2);

/* 00484120  lib  [lib-island] */
int __cdecl FUN_00484120(int param_1);

/* 00484260  lib  [lib-island] */
undefined __cdecl FUN_00484260(int param_1);

/* 004842a0  lib  [lib-island] */
int __cdecl FUN_004842a0(int param_1, int param_2);

/* 00484370  lib  [lib-island] */
undefined __cdecl FUN_00484370(uint * param_1);

/* 004843d0  lib  [lib-island] */
undefined4 __cdecl FUN_004843d0(int param_1, undefined4 param_2);

/* 00484410  lib  [lib-island] */
int __cdecl FUN_00484410(int param_1, uint * param_2, uint param_3, int param_4);

/* 004844b0  lib  [lib-island] */
int __cdecl FUN_004844b0(int param_1, int param_2);

/* 00484530  lib  [lib-island] */
int __cdecl FUN_00484530(int * param_1, byte * param_2);

/* 00484760  lib  [lib-island] */
int __cdecl FUN_00484760(int * param_1, int param_2);

/* 00484930  lib  [lib-island] */
uint __cdecl FUN_00484930(int param_1, uint param_2);

/* 00484960  lib  [lib-island] */
uint __cdecl FUN_00484960(uint * param_1);

/* 00484ae0  lib  [lib-island] */
undefined4 __cdecl FUN_00484ae0(int param_1, int param_2);

/* 00484b10  lib  [lib-island] */
int __cdecl FUN_00484b10(int * param_1);

/* 00484c20  lib  [lib-island] */
uint __cdecl FUN_00484c20(uint * param_1, int param_2);

/* 00484f60  lib  [lib-island] */
uint __cdecl FUN_00484f60(undefined4 * param_1, uint * param_2, uint * param_3, int param_4, int param_5);

/* 00485250  lib  [lib-island] */
undefined __cdecl FUN_00485250(int param_1);

/* 00485280  lib  [lib-island] */
int __cdecl FUN_00485280(int param_1, uint param_2);

/* 00485380  lib  [lib-island] */
undefined __cdecl FUN_00485380(int param_1);

/* 004854a0  lib  [lib-island] */
int __cdecl FUN_004854a0(int param_1, int param_2);

/* 00485520  lib  [lib-island] */
uint __cdecl FUN_00485520(int param_1);

/* 004856d0  lib  [lib-island] */
undefined __cdecl FUN_004856d0(int param_1);

/* 00485750  lib  [lib-island] */
int __cdecl FUN_00485750(int * param_1, int param_2);

/* 004868a0  lib  [lib-island] */
undefined4 * __cdecl FUN_004868a0(int param_1);

/* 00486af0  lib  [lib-island] */
int __cdecl FUN_00486af0(undefined4 * param_1);

/* 00486ed0  lib  [lib-island] */
undefined __cdecl FUN_00486ed0(int param_1);

/* 00486f40  lib  [lib-island] */
int __cdecl FUN_00486f40(int * param_1, undefined4 * param_2, byte * param_3, undefined4 * param_4);

/* 00487070  lib  [lib-island] */
int __cdecl FUN_00487070(int param_1, uint param_2);

/* 004870c0  lib  [lib-island] */
undefined __cdecl FUN_004870c0(int * param_1, uint param_2, char param_3, int param_4, uint * param_5);

/* 004871d0  lib  [lib-island] */
undefined __cdecl FUN_004871d0(int param_1, uint param_2, uint * param_3);

/* 00487240  lib  [lib-island] */
undefined __cdecl FUN_00487240(int param_1, int * param_2, int param_3, int param_4);

/* 00487510  lib  [lib-island] */
undefined4 __cdecl FUN_00487510(int param_1, int param_2, char param_3);

/* 00487580  lib  [lib-island] */
undefined __stdcall FUN_00487580(void);

/* 00487690  lib  [lib-island] */
int __cdecl FUN_00487690(int * param_1, undefined4 param_2, undefined4 param_3, uint * param_4);

/* 004876e0  lib  [lib-island] */
int __cdecl FUN_004876e0(int param_1);

/* 004877e0  lib  [lib-island] */
undefined __cdecl FUN_004877e0(int param_1, int param_2, uint param_3, int param_4, uint * param_5, uint * param_6);

/* 00487a00  lib  [lib-island] */
undefined __cdecl FUN_00487a00(int * param_1, undefined1 * param_2, uint param_3);

/* 00487b40  lib  [lib-island] */
undefined4 __cdecl FUN_00487b40(int * param_1, int param_2, int param_3, int param_4);

/* 00487c30  lib  [lib-island] */
undefined4 __cdecl FUN_00487c30(uint * param_1, uint param_2);

/* 00487d80  lib  [lib-island] */
undefined __cdecl FUN_00487d80(int * param_1, byte * param_2);

/* 00487e80  lib  [lib-island] */
undefined __cdecl FUN_00487e80(int * param_1, int param_2, byte * param_3);

/* 00487f30  lib  [lib-island] */
undefined __cdecl FUN_00487f30(int param_1);

/* 00487fb0  lib  [lib-island] */
undefined __cdecl FUN_00487fb0(int * param_1, int param_2);

/* 004880a0  lib  [lib-island] */
undefined __cdecl FUN_004880a0(int param_1);

/* 004880e0  lib  [lib-island] */
undefined __cdecl FUN_004880e0(int * param_1, undefined4 * param_2);

/* 00488380  lib  [lib-island] */
uint __cdecl FUN_00488380(int * param_1, char * param_2, undefined4 param_3, uint param_4, uint param_5, int param_6);

/* 004884b0  lib  [lib-island] */
undefined __cdecl FUN_004884b0(undefined4 * param_1, int * param_2, int param_3);

/* 00488510  lib  [lib-island] */
undefined4 __cdecl FUN_00488510(int param_1);

/* 004885a0  lib  [lib-island] */
undefined __cdecl FUN_004885a0(undefined4 param_1, undefined4 param_2, undefined4 param_3);

/* 00488640  lib  [lib-island] */
undefined __cdecl FUN_00488640(int * param_1, int param_2);

/* 00488860  lib  [lib-island] */
undefined __cdecl FUN_00488860(int * param_1, int param_2, int param_3, char * param_4, char * param_5, int param_6);

/* 004889f0  lib  [lib-island] */
int __cdecl FUN_004889f0(undefined4 param_1, int * param_2, char * param_3);

/* 00488a90  lib  [lib-island] */
int __cdecl FUN_00488a90(int * param_1, char * param_2);

/* 00488b10  lib  [lib-island] */
undefined4 __cdecl FUN_00488b10(int * param_1, undefined4 * param_2);

/* 00488dd0  lib  [lib-string] */
undefined4 __cdecl FUN_00488dd0(int param_1, char * param_2);

/* 00489140  lib  [lib-island] */
int __cdecl FUN_00489140(int * param_1, undefined4 * param_2, char * param_3);

/* 00489330  lib  [lib-island] */
undefined __cdecl FUN_00489330(int * param_1, uint * param_2);

/* 00489750  lib  [lib-island] */
undefined __cdecl FUN_00489750(int * param_1, void * param_2, int param_3, int param_4);

/* 004898d0  lib  [lib-island] */
undefined4 __cdecl FUN_004898d0(uint * param_1, uint * param_2);

/* 00489940  lib  [lib-island] */
undefined __cdecl FUN_00489940(uint * param_1);

/* 00489a60  lib  [lib-island] */
int __cdecl FUN_00489a60(int param_1);

/* 00489b10  lib  [lib-island] */
int __cdecl FUN_00489b10(int * param_1, int param_2);

/* 00489b70  lib  [lib-island] */
undefined __cdecl FUN_00489b70(int param_1, int * param_2, int * param_3);

/* 00489bc0  lib  [lib-island] */
uint __cdecl FUN_00489bc0(int param_1, int param_2, uint param_3);

/* 00489c10  lib  [lib-island] */
uint __cdecl FUN_00489c10(uint param_1);

/* 00489d30  lib  [lib-island] */
undefined __cdecl FUN_00489d30(int * param_1);

/* 0048a080  lib  [lib-island] */
undefined __cdecl FUN_0048a080(int * param_1, int param_2, int param_3, int * param_4);

/* 0048a240  lib  [lib-island] */
undefined4 __cdecl FUN_0048a240(int * param_1, int * param_2, undefined2 * param_3, undefined4 * param_4);

/* 0048a4d0  lib  [lib-string] */
undefined4 __cdecl FUN_0048a4d0(byte * param_1, int * param_2);

/* 0048abe0  lib  [lib-island] */
undefined __cdecl FUN_0048abe0(int * param_1, int param_2, int * param_3, undefined4 param_4, int * param_5, int * param_6, int param_7, char * param_8, int param_9, undefined4 param_10);

/* 0048b2e0  lib  [lib-island] */
char * __cdecl FUN_0048b2e0(int param_1);

/* 0048b310  lib  [lib-island] */
uint __cdecl FUN_0048b310(char * param_1);

/* 0048b500  lib  [lib-island] */
undefined __cdecl FUN_0048b500(int param_1, undefined4 param_2);

/* 0048b530  lib  [lib-island] */
undefined __cdecl FUN_0048b530(int param_1);

/* 0048b5a0  lib  [lib-island] */
undefined4 __cdecl FUN_0048b5a0(undefined8 * param_1, int param_2, byte param_3);

/* 0048b780  lib  [lib-island] */
undefined __cdecl FUN_0048b780(undefined4 * param_1, int * param_2, int param_3, undefined4 * param_4, undefined4 * param_5);

/* 0048b7c0  lib  [lib-island] */
undefined __cdecl FUN_0048b7c0(undefined4 * param_1, int * param_2, int param_3, int * param_4);

/* 0048b820  lib  [lib-island] */
undefined __cdecl FUN_0048b820(undefined4 * param_1, int * param_2, undefined1 param_3, undefined4 * param_4, int * param_5);

/* 0048b8b0  lib  [lib-island] */
undefined __cdecl FUN_0048b8b0(undefined4 * param_1, int * param_2, undefined1 param_3, undefined4 * param_4, undefined4 * param_5);

/* 0048b940  lib  [lib-island] */
int __cdecl FUN_0048b940(int param_1);

/* 0048b960  lib  [lib-island] */
undefined __cdecl FUN_0048b960(int * param_1, undefined4 * param_2);

/* 0048b9c0  lib  [lib-island] */
undefined __cdecl FUN_0048b9c0(int * param_1, undefined4 * param_2);

/* 0048ba50  lib  [lib-island] */
undefined __cdecl FUN_0048ba50(int * param_1, undefined4 * param_2);

/* 0048bb90  lib  [lib-island] */
undefined __cdecl FUN_0048bb90(int * param_1, undefined4 * param_2);

/* 0048bbe0  lib  [lib-island] */
undefined __cdecl FUN_0048bbe0(int * param_1, int * param_2);

/* 0048bce0  lib  [lib-island] */
undefined4 __cdecl FUN_0048bce0(uint * param_1, uint param_2, int param_3);

/* 0048bd80  lib  [lib-island] */
undefined __cdecl FUN_0048bd80(int * param_1, uint * param_2, int param_3, int param_4, int param_5);

/* 0048bf70  lib  [lib-island] */
char __cdecl FUN_0048bf70(byte * param_1);

/* 0048c030  lib  [lib-string] */
undefined __cdecl FUN_0048c030(int * param_1, short * param_2);

/* 0048c240  lib  [lib-string] */
undefined __cdecl FUN_0048c240(int * param_1, undefined4 * param_2);

/* 0048c460  lib  [lib-string] */
undefined __stdcall FUN_0048c460(void);

/* 0048c4f0  lib  [lib-string] */
undefined __cdecl FUN_0048c4f0(int * param_1, short * param_2, undefined4 * param_3);

/* 0048c830  lib  [lib-island] */
uint __cdecl FUN_0048c830(int param_1, int param_2);

/* 0048c85a  lib  [lib-string] */
uint __stdcall FUN_0048c85a(void);

/* 0048c930  lib  [lib-island] */
undefined __thiscall FUN_0048c930(void * this, int * param_1, undefined4 * param_2, int param_3);

/* 0048ca70  lib  [lib-island] */
uint __cdecl FUN_0048ca70(int param_1, uint param_2);

/* 0048cac0  lib  [lib-island] */
undefined __cdecl FUN_0048cac0(int * param_1, uint param_2);

/* 0048cc10  lib  [lib-island] */
undefined4 * __cdecl FUN_0048cc10(int param_1, undefined4 * param_2, size_t param_3, uint * param_4, uint * param_5);

/* 0048cc90  lib  [lib-island] */
undefined4 __cdecl FUN_0048cc90(byte * param_1, double * param_2, uint param_3, char param_4);

/* 0048d2d0  lib  [lib-island] */
uint __cdecl FUN_0048d2d0(char * param_1);

/* 0048d300  lib  [lib-island] */
undefined4 __cdecl FUN_0048d300(byte * param_1, uint * param_2, int param_3, char param_4);

/* 0048d4b0  lib  [lib-island] */
int __cdecl FUN_0048d4b0(int * param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5);

/* 0048d540  lib  [lib-island] */
undefined __cdecl FUN_0048d540(int * param_1, char * param_2, int param_3, short * param_4);

/* 0048d620  lib  [lib-island] */
int __cdecl FUN_0048d620(int * param_1, undefined4 param_2, undefined4 param_3, int param_4);

/* 0048d7c0  lib  [lib-island] */
undefined __cdecl FUN_0048d7c0(int * param_1);

/* 0048dbc0  lib  [lib-island] */
undefined __cdecl FUN_0048dbc0(int * param_1);

/* 0048e040  lib  [lib-island] */
undefined __cdecl FUN_0048e040(int * param_1, undefined4 * param_2, int param_3);

/* 0048e0b0  lib  [lib-string] */
undefined __cdecl FUN_0048e0b0(int * param_1, int param_2);

/* 0048e1f0  lib  [lib-string] */
undefined __cdecl FUN_0048e1f0(byte * param_1, byte * param_2, int param_3, int param_4, undefined1 param_5, int * param_6, short * param_7, undefined4 * param_8, int param_9, int param_10);

/* 0048e5e0  lib  [lib-island] */
undefined __cdecl FUN_0048e5e0(int * param_1, byte param_2, int param_3);

/* 0048e620  lib  [lib-island] */
undefined __cdecl FUN_0048e620(int * param_1, char * param_2, char * param_3);

/* 0048e8c0  lib  [lib-island] */
undefined __cdecl FUN_0048e8c0(uint * param_1, int param_2, uint * param_3);

/* 0048e9a0  lib  [lib-island] */
undefined __cdecl FUN_0048e9a0(int param_1);

/* 0048ea60  lib  [lib-island] */
uint __cdecl FUN_0048ea60(uint * param_1, uint param_2);

/* 0048ec40  lib  [lib-island] */
bool __cdecl FUN_0048ec40(uint * param_1, uint param_2);

/* 0048ed00  lib  [lib-island] */
undefined4 __cdecl FUN_0048ed00(undefined4 * param_1, int param_2);

/* 0048ed50  lib  [lib-island] */
uint __cdecl FUN_0048ed50(int * param_1, int param_2);

/* 0048efd0  lib  [lib-island] */
undefined __cdecl FUN_0048efd0(int param_1);

/* 0048eff0  lib  [lib-island] */
uint __cdecl FUN_0048eff0(undefined4 * param_1, uint param_2, int * param_3);

/* 0048f070  lib  [lib-island] */
undefined4 __cdecl FUN_0048f070(int * param_1);

/* 0048f150  lib  [lib-island] */
undefined4 __cdecl FUN_0048f150(undefined4 * param_1);

/* 0048f290  lib  [lib-island] */
uint __cdecl FUN_0048f290(int * param_1);

/* 0048f2f0  lib  [lib-island] */
uint __cdecl FUN_0048f2f0(undefined4 * param_1, char * param_2);

/* 0048f390  lib  [lib-island] */
int __cdecl FUN_0048f390(int * param_1, int param_2);

/* 0048f420  lib  [lib-island] */
int __cdecl FUN_0048f420(undefined4 * param_1, undefined4 * param_2);

/* 0048f530  lib  [lib-island] */
int __cdecl FUN_0048f530(int * param_1, uint * param_2);

/* 0048f740  lib  [lib-island] */
char * __cdecl FUN_0048f740(undefined4 * param_1, undefined4 * param_2, byte param_3);

/* 0048f790  lib  [lib-island] */
undefined4 __cdecl FUN_0048f790(undefined4 * param_1, int param_2, int param_3, int param_4, int * param_5);

/* 0048f7e0  lib  [lib-island] */
int __cdecl FUN_0048f7e0(int * param_1, undefined4 * param_2);

/* 0048f870  lib  [lib-island] */
uint __cdecl FUN_0048f870(int * param_1, uint param_2, size_t param_3, void * param_4);

/* 0048f8b0  lib  [lib-island] */
int __cdecl FUN_0048f8b0(int param_1, uint * param_2);

/* 0048f8d0  lib  [lib-island] */
undefined4 __cdecl FUN_0048f8d0(int param_1, undefined4 * param_2);

/* 0048f930  lib  [lib-island] */
uint __cdecl FUN_0048f930(uint * param_1);

/* 0048fb70  lib  [lib-island] */
uint __cdecl FUN_0048fb70(undefined4 * param_1, char * param_2, uint * param_3);

/* 0048fbc0  lib  [lib-island] */
undefined __cdecl FUN_0048fbc0(undefined4 * param_1);

/* 0048fca0  lib  [lib-island] */
undefined __cdecl FUN_0048fca0(int param_1);

/* 0048fdc0  lib  [lib-island] */
undefined __cdecl FUN_0048fdc0(int * param_1, undefined4 * param_2);

/* 0048fe00  lib  [lib-island] */
char __cdecl FUN_0048fe00(undefined4 * param_1);

/* 0048fe50  lib  [lib-island] */
undefined1 * __cdecl FUN_0048fe50(int param_1);

/* 0048fe70  lib  [lib-island] */
undefined __cdecl FUN_0048fe70(undefined4 * param_1, int param_2, undefined4 * param_3);

/* 0048fee0  lib  [lib-island] */
int __cdecl FUN_0048fee0(undefined4 * param_1);

/* 0048ff20  lib  [lib-island] */
uint __cdecl FUN_0048ff20(undefined4 * param_1);

/* 0048ffe0  lib  [lib-island] */
uint * __cdecl FUN_0048ffe0(uint * param_1, byte * param_2, uint param_3, uint param_4, void * param_5, size_t param_6, size_t param_7, int param_8, uint * param_9);

/* 004901e0  lib  [lib-island] */
undefined __cdecl FUN_004901e0(undefined4 * param_1, int param_2, int param_3, int param_4, int * param_5);

/* 00490640  lib  [lib-island] */
int __cdecl FUN_00490640(int param_1, uint * param_2);

/* 004906b0  lib  [lib-island] */
undefined4 __cdecl FUN_004906b0(int param_1, undefined4 * param_2);

/* 004906f0  lib  [lib-island] */
int __cdecl FUN_004906f0(int * param_1, undefined4 * param_2);

/* 00490750  lib  [lib-island] */
undefined __cdecl FUN_00490750(int param_1);

/* 00490780  lib  [lib-island] */
undefined __cdecl FUN_00490780(int param_1);

/* 00490810  lib  [lib-island] */
int __cdecl FUN_00490810(undefined8 * param_1, int param_2, char param_3);

/* 00490880  lib  [lib-island] */
undefined4 __cdecl FUN_00490880(undefined4 * param_1, int param_2);

/* 004908e0  lib  [lib-island] */
uint __cdecl FUN_004908e0(int * param_1, int * param_2, uint param_3, int param_4, int param_5, uint * param_6);

/* 00490c90  lib  [lib-island] */
int __cdecl FUN_00490c90(int * param_1, undefined4 * param_2);

/* 00490e00  lib  [lib-island] */
undefined __cdecl FUN_00490e00(undefined * param_1, byte * param_2, int param_3, undefined4 * param_4, byte param_5, uint param_6);

/* 00491450  lib  [lib-island] */
int __cdecl FUN_00491450(int * param_1, undefined4 * param_2);

/* 004916b0  lib  [lib-island] */
uint __cdecl FUN_004916b0(int * param_1, uint param_2);

/* 00491910  lib  [lib-island] */
uint __cdecl FUN_00491910(undefined4 * param_1, int param_2, int param_3);

/* 004919c0  lib  [lib-island] */
undefined4 __cdecl FUN_004919c0(undefined4 * param_1);

/* 00491a40  lib  [lib-island] */
ushort __cdecl FUN_00491a40(undefined4 * param_1, int param_2);

/* 00491ab0  lib  [lib-island] */
undefined4 __cdecl FUN_00491ab0(undefined4 * param_1, char param_2);

/* 00491b30  lib  [lib-island] */
undefined4 __cdecl FUN_00491b30(undefined4 * param_1, uint param_2);

/* 00491bc0  lib  [lib-island] */
undefined __cdecl FUN_00491bc0(int param_1, undefined4 param_2, undefined4 param_3);

/* 00491c00  lib  [lib-island] */
int __cdecl FUN_00491c00(undefined4 * param_1, uint param_2, uint param_3, int param_4);

/* 00491ce0  lib  [lib-island] */
undefined4 __cdecl FUN_00491ce0(undefined4 * param_1, int param_2, int param_3, int param_4);

/* 00491d30  lib  [lib-island] */
uint __cdecl FUN_00491d30(int * param_1, int param_2);

/* 00491f60  lib  [lib-island] */
undefined __cdecl FUN_00491f60(undefined4 * param_1, undefined4 param_2);

/* 00492040  lib  [lib-island] */
uint __cdecl FUN_00492040(undefined4 * param_1, int param_2, undefined4 param_3);

/* 004920e0  lib  [lib-island] */
undefined4 __stdcall FUN_004920e0(void);

/* 00492110  lib  [lib-island] */
undefined __cdecl FUN_00492110(int * param_1, int param_2);

/* 00492220  lib  [lib-string] */
undefined4 __cdecl FUN_00492220(int * param_1, byte * param_2);

/* 00492280  lib  [lib-island] */
int __cdecl FUN_00492280(int param_1, int param_2, int param_3, undefined4 * param_4, undefined4 * param_5);

/* 004923a0  lib  [lib-string] */
undefined __cdecl FUN_004923a0(int * param_1, int param_2);

/* 00492710  lib  [lib-island] */
undefined __cdecl FUN_00492710(int param_1);

/* 004927e0  lib  [lib-island] */
int __cdecl FUN_004927e0(int * param_1, int * param_2, byte * param_3);

/* 00492a10  lib  [lib-string] */
undefined __cdecl FUN_00492a10(int * param_1, undefined4 * param_2, int param_3, int param_4);

/* 00492ce0  lib  [lib-island] */
int __cdecl FUN_00492ce0(int * param_1);

/* 00492d70  lib  [lib-island] */
undefined __cdecl FUN_00492d70(int * param_1, int * param_2, uint param_3, int * param_4, uint param_5, undefined4 param_6, undefined4 param_7, undefined4 param_8, undefined4 param_9);

/* 00492dd0  lib  [lib-island] */
undefined __cdecl FUN_00492dd0(int * param_1, int * param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6);

/* 00492f00  lib  [lib-island] */
undefined __cdecl FUN_00492f00(int * param_1, char * param_2, int param_3, int param_4);

/* 00493360  lib  [lib-island] */
undefined __cdecl FUN_00493360(int * param_1, byte * param_2);

/* 00493400  lib  [lib-island] */
undefined __cdecl FUN_00493400(int * param_1, int param_2);

/* 004934c0  lib  [lib-island] */
undefined __cdecl FUN_004934c0(int param_1);

/* 00493630  lib  [lib-island] */
undefined __cdecl FUN_00493630(int * param_1, int * param_2, int param_3, int param_4);

/* 004936f0  lib  [lib-string] */
undefined __cdecl FUN_004936f0(int * param_1);

/* 00493750  lib  [lib-island] */
int __cdecl FUN_00493750(char * param_1, char param_2);

/* 00493790  lib  [lib-island] */
undefined __cdecl FUN_00493790(int * param_1, undefined4 * param_2, int param_3, int param_4, int param_5, int param_6, int param_7, int param_8);

/* 00493af0  lib  [lib-island] */
undefined4 __stdcall FUN_00493af0(void);

/* 00493b20  lib  [lib-island] */
undefined4 * __cdecl FUN_00493b20(int param_1, int param_2, int param_3, uint param_4);

/* 00493bd0  lib  [lib-string] */
undefined __cdecl FUN_00493bd0(int * param_1, int * param_2, undefined4 * param_3, int * param_4, undefined4 param_5);

/* 00493f20  lib  [lib-island] */
int __cdecl FUN_00493f20(int param_1, byte * param_2, int param_3, uint param_4, undefined4 param_5, int param_6, int param_7, int param_8, int * param_9);

