// crt_stl (_library) -- cube. 10 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0055dc30  lib  [crt-name] */
void * __cdecl operator_new[](uint param_1, FILL param_2);

/* 0068d6b0  lib  [crt-name] */
undefined __onexit(void);

/* 0068d788  lib  [crt-name] */
undefined __fastcall __security_check_cookie(void);

/* 0068d8e0  lib  [crt-name] */
undefined __alloca_probe(void);

/* 0068dbab  lib  [crt-name] */
noreturn void __cdecl ___report_gsfailure(void);

/* 0068e3d0  lib  [crt-name] */
undefined __alloca_probe_16(void);

/* 0068e3e6  lib  [crt-name] */
undefined __alloca_probe_8(void);

/* 0068e430  lib  [crt-name] */
undefined __SEH_prolog4(void);

/* 0068e475  lib  [crt-name] */
undefined __SEH_epilog4(void);

/* 0068e7a1  lib  [crt-name] */
void __cdecl ___security_init_cookie(void);

