// eh_funclets_35 (_library) -- cube. 5 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 006f92f0  lib  [eh] */
undefined Unwind@006f92f0(void);

/* 006f9320  lib  [eh] */
undefined Unwind@006f9320(void);

/* 006f9350  lib  [eh] */
undefined Unwind@006f9350(void);

/* 006f9380  lib  [eh] */
undefined Unwind@006f9380(void);

/* 006f93b0  lib  [eh] */
undefined Unwind@006f93b0(void);

