// freetype (_library) -- cube. 1 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0068f110  lib  [lib-string] */
undefined FUN_0068f110(void);

