// sqlite (_library) -- cube. 56 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004497b0  lib  [lib-string] */
undefined FUN_004497b0(void);

/* 0051d170  lib  [lib-string] */
undefined FUN_0051d170(void);

/* 0051e390  lib  [lib-string] */
undefined FUN_0051e390(void);

/* 005203c0  lib  [lib-string] */
undefined FUN_005203c0(void);

/* 00521a60  lib  [lib-string] */
undefined FUN_00521a60(void);

/* 00525e30  lib  [lib-string] */
undefined FUN_00525e30(void);

/* 00529970  lib  [lib-string] */
undefined FUN_00529970(void);

/* 005338d0  lib  [lib-string] */
undefined FUN_005338d0(void);

/* 00533c50  lib  [lib-string] */
undefined FUN_00533c50(void);

/* 00534100  lib  [lib-string] */
undefined FUN_00534100(void);

/* 00536fb0  lib  [lib-string] */
undefined FUN_00536fb0(void);

/* 00537450  lib  [lib-string] */
undefined FUN_00537450(void);

/* 00537e40  lib  [lib-string] */
undefined FUN_00537e40(void);

/* 0053cb90  lib  [lib-string] */
undefined FUN_0053cb90(void);

/* 0053d040  lib  [lib-string] */
undefined FUN_0053d040(void);

/* 0053d620  lib  [lib-string] */
undefined FUN_0053d620(void);

/* 00540ff0  lib  [lib-string] */
undefined FUN_00540ff0(void);

/* 00547b70  lib  [lib-string] */
undefined FUN_00547b70(void);

/* 005496d0  lib  [lib-string] */
undefined FUN_005496d0(void);

/* 005498e0  lib  [lib-string] */
undefined FUN_005498e0(void);

/* 00549b00  lib  [lib-string] */
undefined FUN_00549b00(void);

/* 00549b90  lib  [lib-string] */
undefined FUN_00549b90(void);

/* 00549ed0  lib  [lib-string] */
undefined FUN_00549ed0(void);

/* 0054b750  lib  [lib-string] */
undefined FUN_0054b750(void);

/* 0054b890  lib  [lib-string] */
undefined FUN_0054b890(void);

/* 0054f8c0  lib  [lib-string] */
undefined FUN_0054f8c0(void);

/* 0054fa40  lib  [lib-string] */
undefined FUN_0054fa40(void);

/* 005500b0  lib  [lib-string] */
undefined FUN_005500b0(void);

/* 00550d90  lib  [lib-string] */
undefined FUN_00550d90(void);

/* 00551270  lib  [lib-string] */
undefined FUN_00551270(void);

/* 00551790  lib  [lib-string] */
undefined FUN_00551790(void);

/* 00552ca0  lib  [lib-string] */
undefined FUN_00552ca0(void);

/* 00552e90  lib  [lib-string] */
undefined FUN_00552e90(void);

/* 00553260  lib  [lib-string] */
undefined FUN_00553260(void);

/* 00553490  lib  [lib-string] */
undefined FUN_00553490(void);

/* 00553860  lib  [lib-string] */
undefined FUN_00553860(void);

/* 00554e20  lib  [lib-string] */
undefined FUN_00554e20(void);

/* 005576f0  lib  [lib-string] */
undefined FUN_005576f0(void);

/* 005582f0  lib  [lib-string] */
undefined FUN_005582f0(void);

/* 0055a020  lib  [lib-string] */
undefined FUN_0055a020(void);

/* 0055b3c0  lib  [lib-string] */
undefined FUN_0055b3c0(void);

/* 0055b540  lib  [lib-string] */
undefined FUN_0055b540(void);

/* 0055b750  lib  [lib-string] */
undefined FUN_0055b750(void);

/* 0055d490  lib  [lib-string] */
undefined FUN_0055d490(void);

/* 0055d730  lib  [lib-string] */
undefined FUN_0055d730(void);

/* 0055e4f0  lib  [lib-string] */
undefined FUN_0055e4f0(void);

/* 00564420  lib  [lib-string] */
undefined FUN_00564420(void);

/* 00564bb0  lib  [lib-string] */
undefined FUN_00564bb0(void);

/* 00567880  lib  [lib-string] */
undefined FUN_00567880(void);

/* 00568b40  lib  [lib-string] */
undefined FUN_00568b40(void);

/* 0056c500  lib  [lib-string] */
undefined FUN_0056c500(void);

/* 0056c9c0  lib  [lib-string] */
undefined FUN_0056c9c0(void);

/* 00573740  lib  [lib-string] */
undefined FUN_00573740(void);

/* 005771f0  lib  [lib-string] */
undefined FUN_005771f0(void);

/* 00579e10  lib  [lib-string] */
undefined FUN_00579e10(void);

/* 0057d440  lib  [lib-string] */
undefined FUN_0057d440(void);

