// zlib (_library) -- cube. 1 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 006ceb90  lib  [lib-string] */
undefined FUN_006ceb90(void);

