// Helpers (entity) -- cube. 25 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0040eaf0  gamemisc  [caller-vote] */
undefined FUN_0040eaf0(void);

/* 00411e50  gamemisc  [caller-vote] */
undefined FUN_00411e50(void);

/* 00412170  gamemisc  [caller-vote] */
undefined FUN_00412170(void);

/* 00424170  gamemisc  [caller-vote] */
undefined FUN_00424170(void);

/* 004241b0  gamemisc  [caller-vote] */
undefined FUN_004241b0(void);

/* 004243d0  gamemisc  [caller-vote] */
undefined FUN_004243d0(void);

/* 004244f0  gamemisc  [caller-vote] */
undefined FUN_004244f0(void);

/* 0043c100  gamemisc  [caller-vote] */
undefined FUN_0043c100(void);

/* 0043c8a0  gamemisc  [caller-vote] */
undefined FUN_0043c8a0(void);

/* 0046ea70  gamemisc  [caller-vote] */
undefined FUN_0046ea70(void);

/* 0046fac0  gamemisc  [caller-vote] */
undefined FUN_0046fac0(void);

/* 004e1830  gamemisc  [caller-vote] */
undefined FUN_004e1830(void);

/* 004e34b0  gamemisc  [caller-vote] */
undefined FUN_004e34b0(void);

/* 004e35d0  gamemisc  [caller-vote] */
undefined FUN_004e35d0(void);

/* 004e36e0  gamemisc  [caller-vote] */
undefined FUN_004e36e0(void);

/* 004e3840  gamemisc  [caller-vote] */
undefined FUN_004e3840(void);

/* 004e3900  gamemisc  [caller-vote] */
undefined FUN_004e3900(void);

/* 004e3f40  gamemisc  [caller-vote] */
undefined FUN_004e3f40(void);

/* 004e4000  gamemisc  [caller-vote] */
undefined FUN_004e4000(void);

/* 004e65a0  gamemisc  [caller-vote] */
undefined FUN_004e65a0(void);

/* 004e6c60  gamemisc  [caller-vote] */
undefined FUN_004e6c60(void);

/* 004e6e60  gamemisc  [caller-vote] */
undefined FUN_004e6e60(void);

/* 004e6f20  gamemisc  [caller-vote] */
undefined FUN_004e6f20(void);

/* 005eeee0  gamemisc  [caller-vote] */
undefined FUN_005eeee0(void);

/* 005eefa0  gamemisc  [caller-vote] */
undefined FUN_005eefa0(void);

