// Proven (entity) -- cube. 11 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004128f0  game  [ledger]  ~Creature_drawModel */
undefined FUN_004128f0(void);

/* 004709c0  game  [ledger]  ~GameController_onItemPickup */
undefined FUN_004709c0(void);

/* 00477e10  game  [ledger]  ~findNearestEntityInGrid */
undefined FUN_00477e10(void);

/* 004889e0  game  [ledger]  ~GameController_updateSelectedEntity */
undefined FUN_004889e0(void);

/* 004c6a90  gamemisc  [ledger]  ~item_computeBlockValue */
undefined FUN_004c6a90(void);

/* 004c6e10  gamemisc  [ledger]  ~item_computeValue */
undefined FUN_004c6e10(void);

/* 004c70b0  gamemisc  [ledger]  ~item_computeStat_armor */
undefined FUN_004c70b0(void);

/* 004c76e0  game  [ledger]  ~item_valueByType */
undefined FUN_004c76e0(void);

/* 004c78c0  game  [ledger]  ~Item_compute_value */
undefined FUN_004c78c0(void);

/* 004c7af0  gamemisc  [ledger]  ~item_computeStat_variant2 */
undefined FUN_004c7af0(void);

/* 004c7f60  game  [ledger]  ~item_weaponDamage */
undefined FUN_004c7f60(void);

