// SpeechWidget (entity) -- cube. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004e5ec0  game  [rtti] */
void __thiscall ~SpeechWidget(SpeechWidget * this);

/* 004e5f60  game  [rtti] */
SpeechWidget * __thiscall deleting_destructor_for_NamedObject(SpeechWidget * this, byte param_1);

/* 004e5f90  game  [rtti] */
void __thiscall vfunction2_for_NamedObject(SpeechWidget * this);

