// Proven (render) -- server. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004010b0  gamemisc  [ledger]  ~vec4_store_f32 */
undefined4 * __thiscall FUN_004010b0(void * this, undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);

/* 00402990  gamemisc  [ledger]  ~vec3_store */
undefined4 * __thiscall FUN_00402990(void * this, undefined4 param_1, undefined4 param_2, undefined4 param_3);

/* 004e1200  gamemisc  [ledger]  ~vec4_f32_to_i32 */
int * __thiscall FUN_004e1200(void * this, int param_1);

