// XAudio2Engine (audio) -- cube. 11 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00622da0  game  [rtti] */
void __thiscall XAudio2Engine(XAudio2Engine * this);

/* 00622ef0  game  [rtti] */
void __thiscall ~XAudio2Engine(XAudio2Engine * this);

/* 006230d0  game  [rtti] */
XAudio2Engine * __thiscall deleting_destructor(XAudio2Engine * this, byte param_1);

/* 00623410  game  [rtti] */
void __thiscall vfunction1(XAudio2Engine * this);

/* 00623600  game  [rtti] */
undefined4 __thiscall vfunction5(XAudio2Engine * this);

/* 00623610  game  [rtti] */
void __thiscall vfunction7(XAudio2Engine * this, int * param_1, float param_2, undefined4 param_3, undefined4 param_4);

/* 00623980  game  [rtti] */
void __thiscall vfunction2(XAudio2Engine * this, undefined4 param_1, int param_2, undefined4 param_3);

/* 00623a00  game  [rtti] */
void __thiscall vfunction6(XAudio2Engine * this, undefined4 param_1, undefined4 param_2);

/* 00623a60  game  [rtti] */
void __thiscall deleting_destructor(XAudio2Engine * this, undefined4 * param_1);

/* 00623e60  game  [rtti] */
void __thiscall vfunction4(XAudio2Engine * this);

/* 006240b0  game  [rtti] */
void __thiscall vfunction3(void);

