// helpers_dtor_like_00 (game_misc) -- cube. 200 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004022f0  gamemisc  [role:dtor-like] */
undefined FUN_004022f0(void);

/* 00402f80  gamemisc  [role:dtor-like] */
undefined FUN_00402f80(void);

/* 00402fd0  gamemisc  [role:dtor-like] */
undefined FUN_00402fd0(void);

/* 00403030  gamemisc  [role:dtor-like] */
undefined FUN_00403030(void);

/* 004044f0  gamemisc  [role:dtor-like] */
undefined FUN_004044f0(void);

/* 00404570  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_00404570(void * this);

/* 00404650  gamemisc  [role:dtor-like] */
undefined FUN_00404650(void);

/* 00404760  gamemisc  [role:dtor-like] */
undefined FUN_00404760(void);

/* 00404890  gamemisc  [role:dtor-like] */
undefined FUN_00404890(void);

/* 004049a0  gamemisc  [role:dtor-like] */
undefined FUN_004049a0(void);

/* 00404ab0  gamemisc  [role:dtor-like] */
undefined FUN_00404ab0(void);

/* 00404be0  gamemisc  [role:dtor-like] */
undefined FUN_00404be0(void);

/* 00404cf0  gamemisc  [role:dtor-like] */
undefined FUN_00404cf0(void);

/* 00404e00  gamemisc  [role:dtor-like] */
undefined FUN_00404e00(void);

/* 00404f10  gamemisc  [role:dtor-like] */
undefined FUN_00404f10(void);

/* 00405640  gamemisc  [role:dtor-like] */
undefined FUN_00405640(void);

/* 00405700  gamemisc  [role:dtor-like] */
undefined FUN_00405700(void);

/* 00405850  gamemisc  [role:dtor-like] */
undefined FUN_00405850(void);

/* 00405960  gamemisc  [role:dtor-like] */
undefined FUN_00405960(void);

/* 00405a70  gamemisc  [role:dtor-like] */
undefined FUN_00405a70(void);

/* 00405ba0  gamemisc  [role:dtor-like] */
undefined FUN_00405ba0(void);

/* 00405e70  gamemisc  [role:dtor-like] */
undefined FUN_00405e70(void);

/* 00405f90  gamemisc  [role:dtor-like] */
undefined FUN_00405f90(void);

/* 004060b0  gamemisc  [role:dtor-like] */
undefined FUN_004060b0(void);

/* 004061e0  gamemisc  [role:dtor-like] */
undefined FUN_004061e0(void);

/* 00406300  gamemisc  [role:dtor-like] */
undefined FUN_00406300(void);

/* 00406420  gamemisc  [role:dtor-like] */
undefined FUN_00406420(void);

/* 00406540  gamemisc  [role:dtor-like] */
undefined FUN_00406540(void);

/* 00406660  gamemisc  [role:dtor-like] */
undefined FUN_00406660(void);

/* 004066f0  gamemisc  [role:dtor-like] */
undefined FUN_004066f0(void);

/* 004067c0  gamemisc  [role:dtor-like] */
undefined FUN_004067c0(void);

/* 004068b0  gamemisc  [role:dtor-like] */
undefined FUN_004068b0(void);

/* 004069e0  gamemisc  [role:dtor-like] */
undefined FUN_004069e0(void);

/* 00406b00  gamemisc  [role:dtor-like] */
undefined FUN_00406b00(void);

/* 00406c30  gamemisc  [role:dtor-like] */
undefined FUN_00406c30(void);

/* 00406f30  gamemisc  [role:dtor-like] */
undefined FUN_00406f30(void);

/* 00407040  gamemisc  [role:dtor-like] */
undefined FUN_00407040(void);

/* 00407170  gamemisc  [role:dtor-like] */
undefined FUN_00407170(void);

/* 00407290  gamemisc  [role:dtor-like] */
undefined FUN_00407290(void);

/* 004073d0  gamemisc  [role:dtor-like] */
undefined FUN_004073d0(void);

/* 00407570  gamemisc  [role:dtor-like] */
undefined FUN_00407570(void);

/* 004076d0  gamemisc  [role:dtor-like] */
undefined FUN_004076d0(void);

/* 004077f0  gamemisc  [role:dtor-like] */
undefined FUN_004077f0(void);

/* 00407910  gamemisc  [role:dtor-like] */
undefined FUN_00407910(void);

/* 00407a50  gamemisc  [role:dtor-like] */
undefined FUN_00407a50(void);

/* 00407c40  gamemisc  [role:dtor-like] */
undefined FUN_00407c40(void);

/* 00407e30  gamemisc  [role:dtor-like] */
undefined FUN_00407e30(void);

/* 00407f80  gamemisc  [role:dtor-like] */
undefined FUN_00407f80(void);

/* 00408080  gamemisc  [role:dtor-like] */
undefined FUN_00408080(void);

/* 00408230  gamemisc  [role:dtor-like] */
undefined FUN_00408230(void);

/* 00408280  gamemisc  [role:dtor-like] */
undefined FUN_00408280(void);

/* 004082f0  gamemisc  [role:dtor-like] */
undefined FUN_004082f0(void);

/* 00408350  gamemisc  [role:dtor-like] */
undefined FUN_00408350(void);

/* 004083f0  gamemisc  [role:dtor-like] */
undefined FUN_004083f0(void);

/* 00408460  gamemisc  [role:dtor-like] */
undefined FUN_00408460(void);

/* 00408a00  gamemisc  [role:dtor-like] */
undefined FUN_00408a00(void);

/* 00408b10  gamemisc  [role:dtor-like] */
undefined FUN_00408b10(void);

/* 00408c20  gamemisc  [role:dtor-like] */
undefined FUN_00408c20(void);

/* 00408d50  gamemisc  [role:dtor-like] */
undefined FUN_00408d50(void);

/* 00408eb0  gamemisc  [role:dtor-like] */
undefined FUN_00408eb0(void);

/* 004090b0  gamemisc  [role:dtor-like] */
undefined FUN_004090b0(void);

/* 004091c0  gamemisc  [role:dtor-like] */
undefined FUN_004091c0(void);

/* 004092e0  gamemisc  [role:dtor-like] */
undefined FUN_004092e0(void);

/* 004093e0  gamemisc  [role:dtor-like] */
undefined FUN_004093e0(void);

/* 00409500  gamemisc  [role:dtor-like] */
undefined FUN_00409500(void);

/* 00409620  gamemisc  [role:dtor-like] */
undefined FUN_00409620(void);

/* 00409730  gamemisc  [role:dtor-like] */
undefined FUN_00409730(void);

/* 00409860  gamemisc  [role:dtor-like] */
undefined FUN_00409860(void);

/* 00409970  gamemisc  [role:dtor-like] */
undefined FUN_00409970(void);

/* 00409a80  gamemisc  [role:dtor-like] */
undefined FUN_00409a80(void);

/* 00409b50  gamemisc  [role:dtor-like] */
undefined FUN_00409b50(void);

/* 00409c20  gamemisc  [role:dtor-like] */
undefined FUN_00409c20(void);

/* 00409cf0  gamemisc  [role:dtor-like] */
undefined FUN_00409cf0(void);

/* 00409de0  gamemisc  [role:dtor-like] */
undefined FUN_00409de0(void);

/* 00409eb0  gamemisc  [role:dtor-like] */
undefined FUN_00409eb0(void);

/* 00409fc0  gamemisc  [role:dtor-like] */
undefined FUN_00409fc0(void);

/* 0040a0e0  gamemisc  [role:dtor-like] */
undefined FUN_0040a0e0(void);

/* 0040a200  gamemisc  [role:dtor-like] */
undefined FUN_0040a200(void);

/* 0040a350  gamemisc  [role:dtor-like] */
undefined FUN_0040a350(void);

/* 0040a3a0  gamemisc  [role:dtor-like] */
undefined FUN_0040a3a0(void);

/* 0040a4c0  gamemisc  [role:dtor-like] */
undefined FUN_0040a4c0(void);

/* 0040a560  gamemisc  [role:dtor-like] */
undefined FUN_0040a560(void);

/* 0040a600  gamemisc  [role:dtor-like] */
undefined FUN_0040a600(void);

/* 0040a690  gamemisc  [role:dtor-like] */
undefined FUN_0040a690(void);

/* 0040a740  gamemisc  [role:dtor-like] */
undefined FUN_0040a740(void);

/* 0040a860  gamemisc  [role:dtor-like] */
undefined FUN_0040a860(void);

/* 0040a9c0  gamemisc  [role:dtor-like] */
undefined FUN_0040a9c0(void);

/* 0040aa50  gamemisc  [role:dtor-like] */
undefined FUN_0040aa50(void);

/* 0040ab10  gamemisc  [role:dtor-like] */
undefined FUN_0040ab10(void);

/* 0040abf0  gamemisc  [role:dtor-like] */
undefined FUN_0040abf0(void);

/* 0040ac80  gamemisc  [role:dtor-like] */
undefined FUN_0040ac80(void);

/* 0040b270  gamemisc  [role:dtor-like] */
undefined FUN_0040b270(void);

/* 0040b390  gamemisc  [role:dtor-like] */
undefined FUN_0040b390(void);

/* 0040b550  gamemisc  [role:dtor-like] */
undefined FUN_0040b550(void);

/* 0040b5e0  gamemisc  [role:dtor-like] */
undefined FUN_0040b5e0(void);

/* 0040b680  gamemisc  [role:dtor-like] */
undefined FUN_0040b680(void);

/* 0040b730  gamemisc  [role:dtor-like] */
undefined FUN_0040b730(void);

/* 0040b9f0  gamemisc  [role:dtor-like] */
undefined FUN_0040b9f0(void);

/* 0040bd50  gamemisc  [role:dtor-like] */
undefined FUN_0040bd50(void);

/* 0040be60  gamemisc  [role:dtor-like] */
undefined FUN_0040be60(void);

/* 0040c390  gamemisc  [role:dtor-like] */
undefined FUN_0040c390(void);

/* 0040d860  gamemisc  [role:dtor-like] */
undefined FUN_0040d860(void);

/* 00411ad0  gamemisc  [role:dtor-like] */
undefined FUN_00411ad0(void);

/* 0042ef10  gamemisc  [role:dtor-like] */
undefined FUN_0042ef10(void);

/* 0043c920  gamemisc  [role:dtor-like] */
undefined FUN_0043c920(void);

/* 0044b920  gamemisc  [role:dtor-like] */
undefined FUN_0044b920(void);

/* 00450e00  gamemisc  [role:dtor-like] */
undefined FUN_00450e00(void);

/* 00452600  gamemisc  [role:dtor-like] */
undefined FUN_00452600(void);

/* 004538c0  gamemisc  [role:dtor-like] */
undefined FUN_004538c0(void);

/* 00453b40  gamemisc  [role:dtor-like] */
undefined FUN_00453b40(void);

/* 00453c90  gamemisc  [role:dtor-like] */
undefined FUN_00453c90(void);

/* 00454ef0  gamemisc  [role:dtor-like] */
undefined FUN_00454ef0(void);

/* 00455760  gamemisc  [role:dtor-like] */
undefined FUN_00455760(void);

/* 00458c10  gamemisc  [role:dtor-like] */
undefined FUN_00458c10(void);

/* 00466b40  gamemisc  [role:dtor-like] */
undefined FUN_00466b40(void);

/* 00466be0  gamemisc  [role:dtor-like] */
undefined thunk_FUN_0046ea70(void);

/* 00467bcb  gamemisc  [role:dtor-like] */
undefined __stdcall FUN_00467bcb(void);

/* 0046db10  gamemisc  [role:dtor-like] */
undefined FUN_0046db10(void);

/* 0046e150  gamemisc  [role:dtor-like] */
undefined FUN_0046e150(void);

/* 0046e250  gamemisc  [role:dtor-like] */
undefined FUN_0046e250(void);

/* 0046e430  gamemisc  [role:dtor-like] */
undefined FUN_0046e430(void);

/* 0046eb20  gamemisc  [role:dtor-like] */
undefined FUN_0046eb20(void);

/* 0046f8b0  gamemisc  [role:dtor-like] */
undefined FUN_0046f8b0(void);

/* 0046f990  gamemisc  [role:dtor-like] */
undefined FUN_0046f990(void);

/* 0046f9f0  gamemisc  [role:dtor-like] */
undefined FUN_0046f9f0(void);

/* 00477d20  gamemisc  [role:dtor-like] */
undefined FUN_00477d20(void);

/* 004815e0  gamemisc  [role:dtor-like] */
undefined FUN_004815e0(void);

/* 00484230  gamemisc  [role:dtor-like] */
undefined FUN_00484230(void);

/* 00487ea0  gamemisc  [role:dtor-like] */
undefined FUN_00487ea0(void);

/* 004abdb0  gamemisc  [role:dtor-like] */
undefined FUN_004abdb0(void);

/* 004c6840  gamemisc  [role:dtor-like] */
undefined FUN_004c6840(void);

/* 004cb220  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_004cb220(void * this);

/* 004cb2c0  gamemisc  [role:dtor-like] */
undefined FUN_004cb2c0(void);

/* 004ce460  gamemisc  [role:dtor-like] */
undefined FUN_004ce460(void);

/* 004e3630  gamemisc  [role:dtor-like] */
undefined FUN_004e3630(void);

/* 004e6d00  gamemisc  [role:dtor-like] */
undefined FUN_004e6d00(void);

/* 00522ca0  gamemisc  [role:dtor-like] */
undefined FUN_00522ca0(void);

/* 00526fb0  gamemisc  [role:dtor-like] */
undefined FUN_00526fb0(void);

/* 0057fb10  gamemisc  [role:dtor-like] */
undefined FUN_0057fb10(void);

/* 00585760  gamemisc  [role:dtor-like] */
undefined FUN_00585760(void);

/* 005866a0  gamemisc  [role:dtor-like] */
undefined FUN_005866a0(void);

/* 00586730  gamemisc  [role:dtor-like] */
undefined FUN_00586730(void);

/* 00586980  gamemisc  [role:dtor-like] */
undefined FUN_00586980(void);

/* 00586a80  gamemisc  [role:dtor-like] */
undefined FUN_00586a80(void);

/* 00587020  gamemisc  [role:dtor-like] */
undefined FUN_00587020(void);

/* 00587180  gamemisc  [role:dtor-like] */
undefined FUN_00587180(void);

/* 005871f0  gamemisc  [role:dtor-like] */
undefined FUN_005871f0(void);

/* 00587290  gamemisc  [role:dtor-like] */
undefined FUN_00587290(void);

/* 00587350  gamemisc  [role:dtor-like] */
undefined FUN_00587350(void);

/* 005947e0  gamemisc  [role:dtor-like] */
undefined FUN_005947e0(void);

/* 005a9ca0  gamemisc  [role:dtor-like] */
undefined FUN_005a9ca0(void);

/* 005ae9f0  gamemisc  [role:dtor-like] */
undefined FUN_005ae9f0(void);

/* 005dc644  gamemisc  [role:dtor-like] */
undefined __stdcall FUN_005dc644(void);

/* 005fae00  gamemisc  [role:dtor-like] */
undefined FUN_005fae00(void);

/* 00605a20  gamemisc  [role:dtor-like] */
undefined FUN_00605a20(void);

/* 00609320  gamemisc  [role:dtor-like] */
undefined FUN_00609320(void);

/* 006290d0  gamemisc  [role:dtor-like] */
undefined FUN_006290d0(void);

/* 0062ba50  gamemisc  [role:dtor-like] */
undefined FUN_0062ba50(void);

/* 00630a80  gamemisc  [role:dtor-like] */
undefined FUN_00630a80(void);

/* 00630b60  gamemisc  [role:dtor-like] */
undefined FUN_00630b60(void);

/* 00636870  gamemisc  [role:dtor-like] */
undefined FUN_00636870(void);

/* 00636c40  gamemisc  [role:dtor-like] */
undefined FUN_00636c40(void);

/* 00637260  gamemisc  [role:dtor-like] */
undefined FUN_00637260(void);

/* 00639300  gamemisc  [role:dtor-like] */
undefined FUN_00639300(void);

/* 00639cf0  gamemisc  [role:dtor-like] */
undefined FUN_00639cf0(void);

/* 0063a690  gamemisc  [role:dtor-like] */
undefined FUN_0063a690(void);

/* 0063c680  gamemisc  [role:dtor-like] */
undefined FUN_0063c680(void);

/* 0063c700  gamemisc  [role:dtor-like] */
undefined FUN_0063c700(void);

/* 0063d9c0  gamemisc  [role:dtor-like] */
undefined FUN_0063d9c0(void);

/* 0063da20  gamemisc  [role:dtor-like] */
undefined FUN_0063da20(void);

/* 00641180  gamemisc  [role:dtor-like] */
undefined FUN_00641180(void);

/* 00650890  gamemisc  [role:dtor-like] */
undefined FUN_00650890(void);

/* 006508f0  gamemisc  [role:dtor-like] */
undefined FUN_006508f0(void);

/* 00659670  gamemisc  [role:dtor-like] */
undefined FUN_00659670(void);

/* 0065b180  gamemisc  [role:dtor-like] */
undefined FUN_0065b180(void);

/* 00663510  gamemisc  [role:dtor-like] */
undefined FUN_00663510(void);

/* 0066dcb0  gamemisc  [role:dtor-like] */
undefined FUN_0066dcb0(void);

/* 0066dd80  gamemisc  [role:dtor-like] */
undefined FUN_0066dd80(void);

/* 0066de00  gamemisc  [role:dtor-like] */
undefined FUN_0066de00(void);

/* 0066de80  gamemisc  [role:dtor-like] */
undefined FUN_0066de80(void);

/* 0066df00  gamemisc  [role:dtor-like] */
undefined FUN_0066df00(void);

/* 0066e970  gamemisc  [role:dtor-like] */
undefined FUN_0066e970(void);

/* 00672e80  gamemisc  [role:dtor-like] */
undefined FUN_00672e80(void);

/* 00681840  gamemisc  [role:dtor-like] */
undefined FUN_00681840(void);

/* 00681890  gamemisc  [role:dtor-like] */
undefined FUN_00681890(void);

/* 00681a70  gamemisc  [role:dtor-like] */
undefined FUN_00681a70(void);

/* 00683750  gamemisc  [role:dtor-like] */
undefined FUN_00683750(void);

/* 00683de0  gamemisc  [role:dtor-like] */
undefined FUN_00683de0(void);

/* 00687440  gamemisc  [role:dtor-like] */
undefined FUN_00687440(void);

/* 0068e6b0  gamemisc  [role:dtor-like] */
BOOL __cdecl __IsNonwritableInCurrentImage(PBYTE pTarget);

/* 006a4a40  gamemisc  [role:dtor-like] */
undefined FUN_006a4a40(void);

/* 006a59f0  gamemisc  [role:dtor-like] */
undefined FUN_006a59f0(void);

/* 006a5b70  gamemisc  [role:dtor-like] */
undefined FUN_006a5b70(void);

/* 006a5c00  gamemisc  [role:dtor-like] */
undefined FUN_006a5c00(void);

/* 006bf9f0  gamemisc  [role:dtor-like] */
undefined FUN_006bf9f0(void);

/* 006c2810  gamemisc  [role:dtor-like] */
undefined FUN_006c2810(void);

/* 006c63d0  gamemisc  [role:dtor-like] */
undefined FUN_006c63d0(void);

/* 006ce050  gamemisc  [role:dtor-like] */
undefined FUN_006ce050(void);

/* 006cf530  gamemisc  [role:dtor-like] */
undefined FUN_006cf530(void);

/* 006fb150  gamemisc  [role:dtor-like] */
undefined FUN_006fb150(void);

