// helpers_identity (game_misc) -- cube. 1 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0058e9e0  gamemisc  [role:identity]  ~identity_58e9e0 */
undefined FUN_0058e9e0(void);

