// helpers_dtor_like (game_misc) -- cube. 97 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004022f0  gamemisc  [role:dtor-like] */
undefined FUN_004022f0(void);

/* 00402f80  gamemisc  [role:dtor-like] */
undefined FUN_00402f80(void);

/* 00402fd0  gamemisc  [role:dtor-like] */
undefined FUN_00402fd0(void);

/* 00403030  gamemisc  [role:dtor-like] */
undefined FUN_00403030(void);

/* 004044f0  gamemisc  [role:dtor-like] */
undefined FUN_004044f0(void);

/* 00404570  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_00404570(void * this);

/* 0040b9f0  gamemisc  [role:dtor-like] */
undefined FUN_0040b9f0(void);

/* 0040bd50  gamemisc  [role:dtor-like] */
undefined FUN_0040bd50(void);

/* 0040be60  gamemisc  [role:dtor-like] */
undefined FUN_0040be60(void);

/* 0040c390  gamemisc  [role:dtor-like] */
undefined FUN_0040c390(void);

/* 0040d860  gamemisc  [role:dtor-like] */
undefined FUN_0040d860(void);

/* 00411ad0  gamemisc  [role:dtor-like] */
undefined FUN_00411ad0(void);

/* 0042ef10  gamemisc  [role:dtor-like] */
undefined FUN_0042ef10(void);

/* 0043c920  gamemisc  [role:dtor-like] */
undefined FUN_0043c920(void);

/* 0044b920  gamemisc  [role:dtor-like] */
undefined FUN_0044b920(void);

/* 00452600  gamemisc  [role:dtor-like] */
undefined FUN_00452600(void);

/* 004538c0  gamemisc  [role:dtor-like] */
undefined FUN_004538c0(void);

/* 00453b40  gamemisc  [role:dtor-like] */
undefined FUN_00453b40(void);

/* 00453c90  gamemisc  [role:dtor-like] */
undefined FUN_00453c90(void);

/* 00454ef0  gamemisc  [role:dtor-like] */
undefined FUN_00454ef0(void);

/* 00455760  gamemisc  [role:dtor-like] */
undefined FUN_00455760(void);

/* 00458c10  gamemisc  [role:dtor-like] */
undefined FUN_00458c10(void);

/* 00466b40  gamemisc  [role:dtor-like] */
undefined FUN_00466b40(void);

/* 00466be0  gamemisc  [role:dtor-like] */
undefined thunk_FUN_0046ea70(void);

/* 00467bcb  gamemisc  [role:dtor-like] */
undefined __stdcall FUN_00467bcb(void);

/* 0046db10  gamemisc  [role:dtor-like] */
undefined FUN_0046db10(void);

/* 0046e150  gamemisc  [role:dtor-like] */
undefined FUN_0046e150(void);

/* 0046e250  gamemisc  [role:dtor-like] */
undefined FUN_0046e250(void);

/* 0046e430  gamemisc  [role:dtor-like] */
undefined FUN_0046e430(void);

/* 0046eb20  gamemisc  [role:dtor-like] */
undefined FUN_0046eb20(void);

/* 0046f8b0  gamemisc  [role:dtor-like] */
undefined FUN_0046f8b0(void);

/* 0046f990  gamemisc  [role:dtor-like] */
undefined FUN_0046f990(void);

/* 0046f9f0  gamemisc  [role:dtor-like] */
undefined FUN_0046f9f0(void);

/* 00477d20  gamemisc  [role:dtor-like] */
undefined FUN_00477d20(void);

/* 00487ea0  gamemisc  [role:dtor-like] */
undefined FUN_00487ea0(void);

/* 004abdb0  gamemisc  [role:dtor-like] */
undefined FUN_004abdb0(void);

/* 004c6840  gamemisc  [role:dtor-like] */
undefined FUN_004c6840(void);

/* 004cb220  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_004cb220(void * this);

/* 004cb2c0  gamemisc  [role:dtor-like] */
undefined FUN_004cb2c0(void);

/* 004ce460  gamemisc  [role:dtor-like] */
undefined FUN_004ce460(void);

/* 004e3630  gamemisc  [role:dtor-like] */
undefined FUN_004e3630(void);

/* 004e6d00  gamemisc  [role:dtor-like] */
undefined FUN_004e6d00(void);

/* 00526fb0  gamemisc  [role:dtor-like] */
undefined FUN_00526fb0(void);

/* 0057fb10  gamemisc  [role:dtor-like] */
undefined FUN_0057fb10(void);

/* 00585760  gamemisc  [role:dtor-like] */
undefined FUN_00585760(void);

/* 005947e0  gamemisc  [role:dtor-like] */
undefined FUN_005947e0(void);

/* 005a9ca0  gamemisc  [role:dtor-like] */
undefined FUN_005a9ca0(void);

/* 005ae9f0  gamemisc  [role:dtor-like] */
undefined FUN_005ae9f0(void);

/* 005dc644  gamemisc  [role:dtor-like] */
undefined __stdcall FUN_005dc644(void);

/* 005fae00  gamemisc  [role:dtor-like] */
undefined FUN_005fae00(void);

/* 00605a20  gamemisc  [role:dtor-like] */
undefined FUN_00605a20(void);

/* 00609320  gamemisc  [role:dtor-like] */
undefined FUN_00609320(void);

/* 006290d0  gamemisc  [role:dtor-like] */
undefined FUN_006290d0(void);

/* 0062ba50  gamemisc  [role:dtor-like] */
undefined FUN_0062ba50(void);

/* 00630a80  gamemisc  [role:dtor-like] */
undefined FUN_00630a80(void);

/* 00630b60  gamemisc  [role:dtor-like] */
undefined FUN_00630b60(void);

/* 00636870  gamemisc  [role:dtor-like] */
undefined FUN_00636870(void);

/* 00636c40  gamemisc  [role:dtor-like] */
undefined FUN_00636c40(void);

/* 00637260  gamemisc  [role:dtor-like] */
undefined FUN_00637260(void);

/* 00639300  gamemisc  [role:dtor-like] */
undefined FUN_00639300(void);

/* 00639cf0  gamemisc  [role:dtor-like] */
undefined FUN_00639cf0(void);

/* 0063a690  gamemisc  [role:dtor-like] */
undefined FUN_0063a690(void);

/* 0063c680  gamemisc  [role:dtor-like] */
undefined FUN_0063c680(void);

/* 0063d9c0  gamemisc  [role:dtor-like] */
undefined FUN_0063d9c0(void);

/* 0063da20  gamemisc  [role:dtor-like] */
undefined FUN_0063da20(void);

/* 00641180  gamemisc  [role:dtor-like] */
undefined FUN_00641180(void);

/* 00650890  gamemisc  [role:dtor-like] */
undefined FUN_00650890(void);

/* 006508f0  gamemisc  [role:dtor-like] */
undefined FUN_006508f0(void);

/* 00659670  gamemisc  [role:dtor-like] */
undefined FUN_00659670(void);

/* 0065b180  gamemisc  [role:dtor-like] */
undefined FUN_0065b180(void);

/* 00663510  gamemisc  [role:dtor-like] */
undefined FUN_00663510(void);

/* 0066dcb0  gamemisc  [role:dtor-like] */
undefined FUN_0066dcb0(void);

/* 0066dd80  gamemisc  [role:dtor-like] */
undefined FUN_0066dd80(void);

/* 0066de00  gamemisc  [role:dtor-like] */
undefined FUN_0066de00(void);

/* 0066de80  gamemisc  [role:dtor-like] */
undefined FUN_0066de80(void);

/* 0066df00  gamemisc  [role:dtor-like] */
undefined FUN_0066df00(void);

/* 0066e970  gamemisc  [role:dtor-like] */
undefined FUN_0066e970(void);

/* 00672e80  gamemisc  [role:dtor-like] */
undefined FUN_00672e80(void);

/* 00681840  gamemisc  [role:dtor-like] */
undefined FUN_00681840(void);

/* 00681890  gamemisc  [role:dtor-like] */
undefined FUN_00681890(void);

/* 00681a70  gamemisc  [role:dtor-like] */
undefined FUN_00681a70(void);

/* 00683750  gamemisc  [role:dtor-like] */
undefined FUN_00683750(void);

/* 00683de0  gamemisc  [role:dtor-like] */
undefined FUN_00683de0(void);

/* 00687440  gamemisc  [role:dtor-like] */
undefined FUN_00687440(void);

/* 0068e6b0  gamemisc  [role:dtor-like] */
BOOL __cdecl __IsNonwritableInCurrentImage(PBYTE pTarget);

/* 006a4a40  gamemisc  [role:dtor-like] */
undefined FUN_006a4a40(void);

/* 006a59f0  gamemisc  [role:dtor-like] */
undefined FUN_006a59f0(void);

/* 006a5b70  gamemisc  [role:dtor-like] */
undefined FUN_006a5b70(void);

/* 006a5c00  gamemisc  [role:dtor-like] */
undefined FUN_006a5c00(void);

/* 006bf9f0  gamemisc  [role:dtor-like] */
undefined FUN_006bf9f0(void);

/* 006c2810  gamemisc  [role:dtor-like] */
undefined FUN_006c2810(void);

/* 006ce050  gamemisc  [role:dtor-like] */
undefined FUN_006ce050(void);

/* 006cf530  gamemisc  [role:dtor-like] */
undefined FUN_006cf530(void);

/* 006fb150  gamemisc  [role:dtor-like] */
undefined FUN_006fb150(void);

/* 006fb1b0  gamemisc  [role:dtor-like] */
undefined FUN_006fb1b0(void);

/* 006fb5f0  gamemisc  [role:dtor-like] */
undefined FUN_006fb5f0(void);

/* 006fb9f0  gamemisc  [role:dtor-like] */
undefined FUN_006fb9f0(void);

