// helpers_wrapper_01 (game_misc) -- cube. 14 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 006cc890  gamemisc  [role:wrapper] */
undefined FUN_006cc890(void);

/* 006ccab0  gamemisc  [role:wrapper] */
undefined FUN_006ccab0(void);

/* 006cce10  gamemisc  [role:wrapper] */
undefined FUN_006cce10(void);

/* 006cce80  gamemisc  [role:wrapper] */
undefined FUN_006cce80(void);

/* 006ccec0  gamemisc  [role:wrapper] */
undefined FUN_006ccec0(void);

/* 006cd030  gamemisc  [role:wrapper] */
undefined FUN_006cd030(void);

/* 006ceb10  gamemisc  [role:wrapper] */
undefined FUN_006ceb10(void);

/* 006cf260  gamemisc  [role:wrapper] */
undefined FUN_006cf260(void);

/* 006d2140  gamemisc  [role:wrapper] */
undefined FUN_006d2140(void);

/* 006d3800  gamemisc  [role:wrapper] */
undefined FUN_006d3800(void);

/* 006d6e60  gamemisc  [role:wrapper] */
undefined FUN_006d6e60(void);

/* 006d8870  gamemisc  [role:wrapper] */
undefined FUN_006d8870(void);

/* 006f9430  gamemisc  [role:wrapper] */
undefined __stdcall FUN_006f9430(void);

/* 006fb0f0  gamemisc  [role:wrapper] */
undefined __stdcall FUN_006fb0f0(void);

