// indirect_dispatch_target_00 (game_misc) -- cube. 200 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00412810  gamemisc  [role:dispatch-target] */
undefined FUN_00412810(void);

/* 0046b8be  gamemisc  [role:dispatch-target] */
undefined __thiscall FUN_0046b8be(void * this);

/* 00488d00  gamemisc  [role:dispatch-target] */
undefined FUN_00488d00(void);

/* 0049be00  gamemisc  [role:dispatch-target] */
undefined __stdcall FUN_0049be00(void);

/* 0049be73  gamemisc  [role:dispatch-target] */
undefined __stdcall FUN_0049be73(void);

/* 0051ce10  gamemisc  [role:dispatch-target] */
undefined FUN_0051ce10(void);

/* 0051d400  gamemisc  [role:dispatch-target] */
undefined FUN_0051d400(void);

/* 0051d5e0  gamemisc  [role:dispatch-target] */
undefined FUN_0051d5e0(void);

/* 0051da30  gamemisc  [role:dispatch-target] */
undefined FUN_0051da30(void);

/* 005201b0  gamemisc  [role:dispatch-target] */
undefined FUN_005201b0(void);

/* 00520640  gamemisc  [role:dispatch-target] */
undefined FUN_00520640(void);

/* 00520e20  gamemisc  [role:dispatch-target] */
undefined FUN_00520e20(void);

/* 00520ea0  gamemisc  [role:dispatch-target] */
undefined FUN_00520ea0(void);

/* 005211c0  gamemisc  [role:dispatch-target] */
undefined FUN_005211c0(void);

/* 005212c0  gamemisc  [role:dispatch-target] */
undefined FUN_005212c0(void);

/* 00521390  gamemisc  [role:dispatch-target] */
undefined FUN_00521390(void);

/* 005214d0  gamemisc  [role:dispatch-target] */
undefined FUN_005214d0(void);

/* 00521820  gamemisc  [role:dispatch-target] */
undefined FUN_00521820(void);

/* 005218b0  gamemisc  [role:dispatch-target] */
undefined FUN_005218b0(void);

/* 00521950  gamemisc  [role:dispatch-target] */
undefined FUN_00521950(void);

/* 005223b0  gamemisc  [role:dispatch-target] */
undefined FUN_005223b0(void);

/* 00522760  gamemisc  [role:dispatch-target] */
undefined FUN_00522760(void);

/* 00522ddd  gamemisc  [role:dispatch-target] */
undefined __stdcall FUN_00522ddd(void);

/* 00522e32  gamemisc  [role:dispatch-target] */
undefined __stdcall FUN_00522e32(void);

/* 00528350  gamemisc  [role:dispatch-target] */
undefined FUN_00528350(void);

/* 0054bd10  gamemisc  [role:dispatch-target] */
undefined FUN_0054bd10(void);

/* 0063d930  gamemisc  [role:dispatch-target] */
undefined FUN_0063d930(void);

/* 0063d960  gamemisc  [role:dispatch-target] */
undefined FUN_0063d960(void);

/* 0063d990  gamemisc  [role:dispatch-target] */
undefined FUN_0063d990(void);

/* 0068e195  gamemisc  [role:dispatch-target] */
undefined __stdcall FUN_0068e195(void);

/* 0068e1e0  gamemisc  [role:dispatch-target] */
undefined entry(void);

/* 0068eb30  gamemisc  [role:dispatch-target] */
undefined FUN_0068eb30(void);

/* 0068ed60  gamemisc  [role:dispatch-target] */
undefined FUN_0068ed60(void);

/* 006903a0  gamemisc  [role:dispatch-target] */
undefined FUN_006903a0(void);

/* 006938e0  gamemisc  [role:dispatch-target] */
undefined FUN_006938e0(void);

/* 00693940  gamemisc  [role:dispatch-target] */
undefined FUN_00693940(void);

/* 00698060  gamemisc  [role:dispatch-target] */
undefined FUN_00698060(void);

/* 00698500  gamemisc  [role:dispatch-target] */
undefined FUN_00698500(void);

/* 0069a900  gamemisc  [role:dispatch-target] */
undefined FUN_0069a900(void);

/* 0069adb0  gamemisc  [role:dispatch-target] */
undefined FUN_0069adb0(void);

/* 0069af60  gamemisc  [role:dispatch-target] */
undefined FUN_0069af60(void);

/* 0069bc10  gamemisc  [role:dispatch-target] */
undefined FUN_0069bc10(void);

/* 0069fb90  gamemisc  [role:dispatch-target] */
undefined FUN_0069fb90(void);

/* 0069ff50  gamemisc  [role:dispatch-target] */
undefined FUN_0069ff50(void);

/* 0069ffe0  gamemisc  [role:dispatch-target] */
undefined FUN_0069ffe0(void);

/* 006a0dd0  gamemisc  [role:dispatch-target] */
undefined FUN_006a0dd0(void);

/* 006a1820  gamemisc  [role:dispatch-target] */
undefined FUN_006a1820(void);

/* 006a31d0  gamemisc  [role:dispatch-target] */
undefined FUN_006a31d0(void);

/* 006a3840  gamemisc  [role:dispatch-target] */
undefined FUN_006a3840(void);

/* 006a66a0  gamemisc  [role:dispatch-target] */
undefined FUN_006a66a0(void);

/* 006a6c10  gamemisc  [role:dispatch-target] */
undefined FUN_006a6c10(void);

/* 006a6c90  gamemisc  [role:dispatch-target] */
undefined FUN_006a6c90(void);

/* 006a75c0  gamemisc  [role:dispatch-target] */
undefined FUN_006a75c0(void);

/* 006a7610  gamemisc  [role:dispatch-target] */
undefined FUN_006a7610(void);

/* 006a7890  gamemisc  [role:dispatch-target] */
undefined FUN_006a7890(void);

/* 006a7b70  gamemisc  [role:dispatch-target] */
undefined FUN_006a7b70(void);

/* 006a7cc0  gamemisc  [role:dispatch-target] */
undefined FUN_006a7cc0(void);

/* 006a7dd0  gamemisc  [role:dispatch-target] */
undefined FUN_006a7dd0(void);

/* 006a7e80  gamemisc  [role:dispatch-target] */
undefined FUN_006a7e80(void);

/* 006a8090  gamemisc  [role:dispatch-target] */
undefined FUN_006a8090(void);

/* 006a84c0  gamemisc  [role:dispatch-target] */
undefined FUN_006a84c0(void);

/* 006a84f0  gamemisc  [role:dispatch-target] */
undefined FUN_006a84f0(void);

/* 006a8c20  gamemisc  [role:dispatch-target] */
undefined FUN_006a8c20(void);

/* 006a8d00  gamemisc  [role:dispatch-target] */
undefined FUN_006a8d00(void);

/* 006a94c0  gamemisc  [role:dispatch-target] */
undefined FUN_006a94c0(void);

/* 006a95f0  gamemisc  [role:dispatch-target] */
undefined FUN_006a95f0(void);

/* 006a98e0  gamemisc  [role:dispatch-target] */
undefined FUN_006a98e0(void);

/* 006a99a0  gamemisc  [role:dispatch-target] */
undefined FUN_006a99a0(void);

/* 006a9f00  gamemisc  [role:dispatch-target] */
undefined FUN_006a9f00(void);

/* 006aa260  gamemisc  [role:dispatch-target] */
undefined FUN_006aa260(void);

/* 006aa9f0  gamemisc  [role:dispatch-target] */
undefined FUN_006aa9f0(void);

/* 006aabd0  gamemisc  [role:dispatch-target] */
undefined FUN_006aabd0(void);

/* 006ac110  gamemisc  [role:dispatch-target] */
undefined FUN_006ac110(void);

/* 006ac4e0  gamemisc  [role:dispatch-target] */
undefined FUN_006ac4e0(void);

/* 006ac520  gamemisc  [role:dispatch-target] */
undefined FUN_006ac520(void);

/* 006ac550  gamemisc  [role:dispatch-target] */
undefined FUN_006ac550(void);

/* 006b4ba0  gamemisc  [role:dispatch-target] */
undefined FUN_006b4ba0(void);

/* 006b4c60  gamemisc  [role:dispatch-target] */
undefined FUN_006b4c60(void);

/* 006b7030  gamemisc  [role:dispatch-target] */
undefined FUN_006b7030(void);

/* 006b75d0  gamemisc  [role:dispatch-target] */
undefined FUN_006b75d0(void);

/* 006b7b10  gamemisc  [role:dispatch-target] */
undefined FUN_006b7b10(void);

/* 006bdf90  gamemisc  [role:dispatch-target] */
undefined FUN_006bdf90(void);

/* 006bed90  gamemisc  [role:dispatch-target] */
undefined FUN_006bed90(void);

/* 006bee10  gamemisc  [role:dispatch-target] */
undefined FUN_006bee10(void);

/* 006c1070  gamemisc  [role:dispatch-target] */
undefined FUN_006c1070(void);

/* 006c1110  gamemisc  [role:dispatch-target] */
undefined FUN_006c1110(void);

/* 006c1780  gamemisc  [role:dispatch-target] */
undefined FUN_006c1780(void);

/* 006c1810  gamemisc  [role:dispatch-target] */
undefined FUN_006c1810(void);

/* 006c1d20  gamemisc  [role:dispatch-target] */
undefined FUN_006c1d20(void);

/* 006c1dd0  gamemisc  [role:dispatch-target] */
undefined FUN_006c1dd0(void);

/* 006c1e80  gamemisc  [role:dispatch-target] */
undefined FUN_006c1e80(void);

/* 006c1ed0  gamemisc  [role:dispatch-target] */
undefined FUN_006c1ed0(void);

/* 006c1f00  gamemisc  [role:dispatch-target] */
undefined FUN_006c1f00(void);

/* 006c1fc0  gamemisc  [role:dispatch-target] */
undefined FUN_006c1fc0(void);

/* 006c2010  gamemisc  [role:dispatch-target] */
undefined FUN_006c2010(void);

/* 006c20d0  gamemisc  [role:dispatch-target] */
undefined FUN_006c20d0(void);

/* 006c21a0  gamemisc  [role:dispatch-target] */
undefined FUN_006c21a0(void);

/* 006c2260  gamemisc  [role:dispatch-target] */
undefined FUN_006c2260(void);

/* 006c22d0  gamemisc  [role:dispatch-target] */
undefined FUN_006c22d0(void);

/* 006c2340  gamemisc  [role:dispatch-target] */
undefined FUN_006c2340(void);

/* 006c23a0  gamemisc  [role:dispatch-target] */
undefined FUN_006c23a0(void);

/* 006c2400  gamemisc  [role:dispatch-target] */
undefined FUN_006c2400(void);

/* 006c2470  gamemisc  [role:dispatch-target] */
undefined FUN_006c2470(void);

/* 006c24f0  gamemisc  [role:dispatch-target] */
undefined FUN_006c24f0(void);

/* 006c25f0  gamemisc  [role:dispatch-target] */
undefined FUN_006c25f0(void);

/* 006c26a0  gamemisc  [role:dispatch-target] */
undefined FUN_006c26a0(void);

/* 006c26f0  gamemisc  [role:dispatch-target] */
undefined FUN_006c26f0(void);

/* 006c2740  gamemisc  [role:dispatch-target] */
undefined FUN_006c2740(void);

/* 006c2790  gamemisc  [role:dispatch-target] */
undefined FUN_006c2790(void);

/* 006c2850  gamemisc  [role:dispatch-target] */
undefined FUN_006c2850(void);

/* 006c2910  gamemisc  [role:dispatch-target] */
undefined FUN_006c2910(void);

/* 006c2920  gamemisc  [role:dispatch-target] */
undefined FUN_006c2920(void);

/* 006c29a0  gamemisc  [role:dispatch-target] */
undefined FUN_006c29a0(void);

/* 006c29f0  gamemisc  [role:dispatch-target] */
undefined FUN_006c29f0(void);

/* 006c2b80  gamemisc  [role:dispatch-target] */
undefined FUN_006c2b80(void);

/* 006c2c30  gamemisc  [role:dispatch-target] */
undefined FUN_006c2c30(void);

/* 006c2d30  gamemisc  [role:dispatch-target] */
undefined FUN_006c2d30(void);

/* 006c2e00  gamemisc  [role:dispatch-target] */
undefined FUN_006c2e00(void);

/* 006c2eb0  gamemisc  [role:dispatch-target] */
undefined FUN_006c2eb0(void);

/* 006c2fb0  gamemisc  [role:dispatch-target] */
undefined FUN_006c2fb0(void);

/* 006c3030  gamemisc  [role:dispatch-target] */
undefined FUN_006c3030(void);

/* 006c3140  gamemisc  [role:dispatch-target] */
undefined FUN_006c3140(void);

/* 006c3320  gamemisc  [role:dispatch-target] */
undefined FUN_006c3320(void);

/* 006c3550  gamemisc  [role:dispatch-target] */
undefined FUN_006c3550(void);

/* 006c3620  gamemisc  [role:dispatch-target] */
undefined FUN_006c3620(void);

/* 006c3850  gamemisc  [role:dispatch-target] */
undefined FUN_006c3850(void);

/* 006c38e0  gamemisc  [role:dispatch-target] */
undefined FUN_006c38e0(void);

/* 006c3b00  gamemisc  [role:dispatch-target] */
undefined FUN_006c3b00(void);

/* 006c3cc0  gamemisc  [role:dispatch-target] */
undefined FUN_006c3cc0(void);

/* 006c3e60  gamemisc  [role:dispatch-target] */
undefined FUN_006c3e60(void);

/* 006c3f50  gamemisc  [role:dispatch-target] */
undefined FUN_006c3f50(void);

/* 006c4040  gamemisc  [role:dispatch-target] */
undefined FUN_006c4040(void);

/* 006c4090  gamemisc  [role:dispatch-target] */
undefined FUN_006c4090(void);

/* 006c8020  gamemisc  [role:dispatch-target] */
undefined FUN_006c8020(void);

/* 006cb7b0  gamemisc  [role:dispatch-target] */
undefined FUN_006cb7b0(void);

/* 006cc7e0  gamemisc  [role:dispatch-target] */
undefined FUN_006cc7e0(void);

/* 006ccf70  gamemisc  [role:dispatch-target] */
undefined FUN_006ccf70(void);

/* 006cd620  gamemisc  [role:dispatch-target] */
undefined FUN_006cd620(void);

/* 006cd6c0  gamemisc  [role:dispatch-target] */
undefined FUN_006cd6c0(void);

/* 006cd850  gamemisc  [role:dispatch-target] */
undefined FUN_006cd850(void);

/* 006cd9a0  gamemisc  [role:dispatch-target] */
undefined FUN_006cd9a0(void);

/* 006dc0f0  gamemisc  [role:dispatch-target] */
undefined FUN_006dc0f0(void);

/* 006dd730  gamemisc  [role:dispatch-target] */
undefined FUN_006dd730(void);

/* 006f9450  gamemisc  [role:dispatch-target] */
undefined FUN_006f9450(void);

/* 006f9480  gamemisc  [role:dispatch-target] */
undefined FUN_006f9480(void);

/* 006f94b0  gamemisc  [role:dispatch-target] */
undefined FUN_006f94b0(void);

/* 006f94e0  gamemisc  [role:dispatch-target] */
undefined FUN_006f94e0(void);

/* 006f9510  gamemisc  [role:dispatch-target] */
undefined FUN_006f9510(void);

/* 006f9540  gamemisc  [role:dispatch-target] */
undefined FUN_006f9540(void);

/* 006f9570  gamemisc  [role:dispatch-target] */
undefined FUN_006f9570(void);

/* 006f95a0  gamemisc  [role:dispatch-target] */
undefined FUN_006f95a0(void);

/* 006f95d0  gamemisc  [role:dispatch-target] */
undefined FUN_006f95d0(void);

/* 006f9600  gamemisc  [role:dispatch-target] */
undefined FUN_006f9600(void);

/* 006f9630  gamemisc  [role:dispatch-target] */
undefined FUN_006f9630(void);

/* 006f9660  gamemisc  [role:dispatch-target] */
undefined FUN_006f9660(void);

/* 006f9690  gamemisc  [role:dispatch-target] */
undefined FUN_006f9690(void);

/* 006f96c0  gamemisc  [role:dispatch-target] */
undefined FUN_006f96c0(void);

/* 006f96f0  gamemisc  [role:dispatch-target] */
undefined FUN_006f96f0(void);

/* 006f9720  gamemisc  [role:dispatch-target] */
undefined FUN_006f9720(void);

/* 006f9750  gamemisc  [role:dispatch-target] */
undefined FUN_006f9750(void);

/* 006f9780  gamemisc  [role:dispatch-target] */
undefined FUN_006f9780(void);

/* 006f97b0  gamemisc  [role:dispatch-target] */
undefined FUN_006f97b0(void);

/* 006f97e0  gamemisc  [role:dispatch-target] */
undefined FUN_006f97e0(void);

/* 006f9810  gamemisc  [role:dispatch-target] */
undefined FUN_006f9810(void);

/* 006f9840  gamemisc  [role:dispatch-target] */
undefined FUN_006f9840(void);

/* 006f9870  gamemisc  [role:dispatch-target] */
undefined FUN_006f9870(void);

/* 006f98a0  gamemisc  [role:dispatch-target] */
undefined FUN_006f98a0(void);

/* 006f98d0  gamemisc  [role:dispatch-target] */
undefined FUN_006f98d0(void);

/* 006f9900  gamemisc  [role:dispatch-target] */
undefined FUN_006f9900(void);

/* 006f9930  gamemisc  [role:dispatch-target] */
undefined FUN_006f9930(void);

/* 006f9960  gamemisc  [role:dispatch-target] */
undefined FUN_006f9960(void);

/* 006f9990  gamemisc  [role:dispatch-target] */
undefined FUN_006f9990(void);

/* 006f99c0  gamemisc  [role:dispatch-target] */
undefined FUN_006f99c0(void);

/* 006f99f0  gamemisc  [role:dispatch-target] */
undefined FUN_006f99f0(void);

/* 006f9a20  gamemisc  [role:dispatch-target] */
undefined FUN_006f9a20(void);

/* 006f9a50  gamemisc  [role:dispatch-target] */
undefined FUN_006f9a50(void);

/* 006f9a80  gamemisc  [role:dispatch-target] */
undefined FUN_006f9a80(void);

/* 006f9ab0  gamemisc  [role:dispatch-target] */
undefined FUN_006f9ab0(void);

/* 006f9ae0  gamemisc  [role:dispatch-target] */
undefined FUN_006f9ae0(void);

/* 006f9b10  gamemisc  [role:dispatch-target] */
undefined FUN_006f9b10(void);

/* 006f9b40  gamemisc  [role:dispatch-target] */
undefined FUN_006f9b40(void);

/* 006f9b70  gamemisc  [role:dispatch-target] */
undefined FUN_006f9b70(void);

/* 006f9ba0  gamemisc  [role:dispatch-target] */
undefined FUN_006f9ba0(void);

/* 006f9bd0  gamemisc  [role:dispatch-target] */
undefined FUN_006f9bd0(void);

/* 006f9c00  gamemisc  [role:dispatch-target] */
undefined FUN_006f9c00(void);

/* 006f9c30  gamemisc  [role:dispatch-target] */
undefined FUN_006f9c30(void);

/* 006f9c60  gamemisc  [role:dispatch-target] */
undefined FUN_006f9c60(void);

/* 006f9c90  gamemisc  [role:dispatch-target] */
undefined FUN_006f9c90(void);

/* 006f9cc0  gamemisc  [role:dispatch-target] */
undefined FUN_006f9cc0(void);

/* 006f9cf0  gamemisc  [role:dispatch-target] */
undefined FUN_006f9cf0(void);

/* 006f9d20  gamemisc  [role:dispatch-target] */
undefined FUN_006f9d20(void);

/* 006f9d50  gamemisc  [role:dispatch-target] */
undefined FUN_006f9d50(void);

/* 006f9d80  gamemisc  [role:dispatch-target] */
undefined FUN_006f9d80(void);

/* 006f9db0  gamemisc  [role:dispatch-target] */
undefined FUN_006f9db0(void);

/* 006f9de0  gamemisc  [role:dispatch-target] */
undefined FUN_006f9de0(void);

/* 006f9e10  gamemisc  [role:dispatch-target] */
undefined FUN_006f9e10(void);

/* 006f9e40  gamemisc  [role:dispatch-target] */
undefined FUN_006f9e40(void);

/* 006f9ee0  gamemisc  [role:dispatch-target] */
undefined FUN_006f9ee0(void);

/* 006f9f20  gamemisc  [role:dispatch-target] */
undefined FUN_006f9f20(void);

/* 006f9f50  gamemisc  [role:dispatch-target] */
undefined FUN_006f9f50(void);

