// Unsorted_004 (game_misc) -- cube. 150 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00697df0  gamemisc  [none] */
undefined FUN_00697df0(void);

/* 00697ea0  gamemisc  [none] */
undefined FUN_00697ea0(void);

/* 00698130  gamemisc  [none] */
undefined FUN_00698130(void);

/* 00698e00  gamemisc  [none] */
undefined FUN_00698e00(void);

/* 00698ff0  gamemisc  [none] */
undefined FUN_00698ff0(void);

/* 00699130  gamemisc  [none] */
undefined FUN_00699130(void);

/* 00699320  gamemisc  [none] */
undefined FUN_00699320(void);

/* 00699f90  gamemisc  [none] */
undefined FUN_00699f90(void);

/* 0069a7f0  gamemisc  [none] */
undefined FUN_0069a7f0(void);

/* 0069a890  gamemisc  [none] */
undefined FUN_0069a890(void);

/* 0069a950  gamemisc  [none] */
undefined FUN_0069a950(void);

/* 0069aac0  gamemisc  [none] */
undefined FUN_0069aac0(void);

/* 0069c020  gamemisc  [none] */
undefined FUN_0069c020(void);

/* 0069c050  gamemisc  [none] */
undefined FUN_0069c050(void);

/* 0069c090  gamemisc  [none] */
undefined FUN_0069c090(void);

/* 0069d190  gamemisc  [none] */
undefined FUN_0069d190(void);

/* 0069d340  gamemisc  [none] */
undefined FUN_0069d340(void);

/* 0069d600  gamemisc  [none] */
undefined FUN_0069d600(void);

/* 0069d750  gamemisc  [none] */
undefined FUN_0069d750(void);

/* 0069f380  gamemisc  [none] */
undefined FUN_0069f380(void);

/* 0069fa90  gamemisc  [none] */
undefined FUN_0069fa90(void);

/* 0069fb00  gamemisc  [none] */
undefined FUN_0069fb00(void);

/* 0069ff10  gamemisc  [none] */
undefined FUN_0069ff10(void);

/* 006a03d0  gamemisc  [none] */
undefined FUN_006a03d0(void);

/* 006a0a80  gamemisc  [none] */
undefined FUN_006a0a80(void);

/* 006a0b70  gamemisc  [none] */
undefined FUN_006a0b70(void);

/* 006a0da0  gamemisc  [none] */
undefined FUN_006a0da0(void);

/* 006a1ab0  gamemisc  [none] */
undefined FUN_006a1ab0(void);

/* 006a1c60  gamemisc  [none] */
undefined FUN_006a1c60(void);

/* 006a1d50  gamemisc  [none] */
undefined FUN_006a1d50(void);

/* 006a22d0  gamemisc  [none] */
undefined FUN_006a22d0(void);

/* 006a23f0  gamemisc  [none] */
undefined FUN_006a23f0(void);

/* 006a2460  gamemisc  [none] */
undefined FUN_006a2460(void);

/* 006a2530  gamemisc  [none] */
undefined FUN_006a2530(void);

/* 006a26f0  gamemisc  [none] */
undefined FUN_006a26f0(void);

/* 006a2820  gamemisc  [none] */
undefined FUN_006a2820(void);

/* 006a2c30  gamemisc  [none] */
undefined FUN_006a2c30(void);

/* 006a2e50  gamemisc  [none] */
undefined FUN_006a2e50(void);

/* 006a2f20  gamemisc  [none] */
undefined FUN_006a2f20(void);

/* 006a30a0  gamemisc  [none] */
undefined FUN_006a30a0(void);

/* 006a3210  gamemisc  [none] */
undefined FUN_006a3210(void);

/* 006a33d0  gamemisc  [none] */
undefined FUN_006a33d0(void);

/* 006a3910  gamemisc  [none] */
undefined FUN_006a3910(void);

/* 006a3970  gamemisc  [none] */
undefined FUN_006a3970(void);

/* 006a3a20  gamemisc  [none] */
undefined FUN_006a3a20(void);

/* 006a3aa0  gamemisc  [none] */
undefined FUN_006a3aa0(void);

/* 006a3b10  gamemisc  [none] */
undefined FUN_006a3b10(void);

/* 006a3bc0  gamemisc  [none] */
undefined FUN_006a3bc0(void);

/* 006a3c20  gamemisc  [none] */
undefined FUN_006a3c20(void);

/* 006a3cb0  gamemisc  [none] */
undefined FUN_006a3cb0(void);

/* 006a3e80  gamemisc  [none] */
undefined FUN_006a3e80(void);

/* 006a3ff0  gamemisc  [none] */
undefined FUN_006a3ff0(void);

/* 006a4060  gamemisc  [none] */
undefined FUN_006a4060(void);

/* 006a41a0  gamemisc  [none] */
undefined FUN_006a41a0(void);

/* 006a4300  gamemisc  [none] */
undefined FUN_006a4300(void);

/* 006a4490  gamemisc  [none] */
undefined FUN_006a4490(void);

/* 006a47f0  gamemisc  [none] */
undefined FUN_006a47f0(void);

/* 006a4920  gamemisc  [none] */
undefined FUN_006a4920(void);

/* 006a4950  gamemisc  [none] */
undefined FUN_006a4950(void);

/* 006a4970  gamemisc  [none] */
undefined FUN_006a4970(void);

/* 006a4eb0  gamemisc  [none] */
undefined FUN_006a4eb0(void);

/* 006a51d0  gamemisc  [none] */
undefined FUN_006a51d0(void);

/* 006a52f0  gamemisc  [none] */
undefined FUN_006a52f0(void);

/* 006a58c0  gamemisc  [none] */
undefined FUN_006a58c0(void);

/* 006a5900  gamemisc  [none] */
undefined FUN_006a5900(void);

/* 006a5970  gamemisc  [none] */
undefined FUN_006a5970(void);

/* 006a59d0  gamemisc  [none] */
undefined FUN_006a59d0(void);

/* 006a5a10  gamemisc  [none] */
undefined FUN_006a5a10(void);

/* 006a5a60  gamemisc  [none] */
undefined FUN_006a5a60(void);

/* 006a5aa0  gamemisc  [none] */
undefined FUN_006a5aa0(void);

/* 006a5ae0  gamemisc  [none] */
undefined FUN_006a5ae0(void);

/* 006a5c60  gamemisc  [none] */
undefined FUN_006a5c60(void);

/* 006a5d80  gamemisc  [none] */
undefined FUN_006a5d80(void);

/* 006a5e10  gamemisc  [none] */
undefined FUN_006a5e10(void);

/* 006a5e20  gamemisc  [none] */
undefined FUN_006a5e20(void);

/* 006a5e90  gamemisc  [none] */
undefined FUN_006a5e90(void);

/* 006a5f50  gamemisc  [none] */
undefined FUN_006a5f50(void);

/* 006a60a0  gamemisc  [none] */
undefined FUN_006a60a0(void);

/* 006a64e0  gamemisc  [none] */
undefined FUN_006a64e0(void);

/* 006a6560  gamemisc  [none] */
undefined FUN_006a6560(void);

/* 006a67e0  gamemisc  [none] */
undefined FUN_006a67e0(void);

/* 006a69c0  gamemisc  [none] */
undefined FUN_006a69c0(void);

/* 006a6cb0  gamemisc  [none] */
undefined FUN_006a6cb0(void);

/* 006a6d10  gamemisc  [none] */
undefined FUN_006a6d10(void);

/* 006a6d30  gamemisc  [none] */
undefined FUN_006a6d30(void);

/* 006a6db0  gamemisc  [none] */
undefined FUN_006a6db0(void);

/* 006a6e00  gamemisc  [none] */
undefined FUN_006a6e00(void);

/* 006a6f10  gamemisc  [none] */
undefined FUN_006a6f10(void);

/* 006a6fd0  gamemisc  [none] */
undefined FUN_006a6fd0(void);

/* 006a7040  gamemisc  [none] */
undefined FUN_006a7040(void);

/* 006a7070  gamemisc  [none] */
undefined FUN_006a7070(void);

/* 006a7340  gamemisc  [none] */
undefined FUN_006a7340(void);

/* 006a7520  gamemisc  [none] */
undefined FUN_006a7520(void);

/* 006a7570  gamemisc  [none] */
undefined FUN_006a7570(void);

/* 006a7990  gamemisc  [none] */
undefined FUN_006a7990(void);

/* 006a8560  gamemisc  [none] */
undefined FUN_006a8560(void);

/* 006a8640  gamemisc  [none] */
undefined FUN_006a8640(void);

/* 006a8770  gamemisc  [none] */
undefined FUN_006a8770(void);

/* 006a87e0  gamemisc  [none] */
undefined FUN_006a87e0(void);

/* 006a8cd0  gamemisc  [none] */
undefined FUN_006a8cd0(void);

/* 006a8ed0  gamemisc  [none] */
undefined FUN_006a8ed0(void);

/* 006a8ef0  gamemisc  [none] */
undefined FUN_006a8ef0(void);

/* 006a8f40  gamemisc  [none] */
undefined FUN_006a8f40(void);

/* 006a9020  gamemisc  [none] */
undefined FUN_006a9020(void);

/* 006a9080  gamemisc  [none] */
undefined FUN_006a9080(void);

/* 006a9190  gamemisc  [none] */
undefined FUN_006a9190(void);

/* 006a92d0  gamemisc  [none] */
undefined FUN_006a92d0(void);

/* 006a9560  gamemisc  [none] */
undefined FUN_006a9560(void);

/* 006a9620  gamemisc  [none] */
undefined FUN_006a9620(void);

/* 006a9700  gamemisc  [none] */
undefined FUN_006a9700(void);

/* 006a9840  gamemisc  [none] */
undefined FUN_006a9840(void);

/* 006a9a00  gamemisc  [none] */
undefined FUN_006a9a00(void);

/* 006a9c50  gamemisc  [none] */
undefined FUN_006a9c50(void);

/* 006a9cc0  gamemisc  [none] */
undefined FUN_006a9cc0(void);

/* 006a9d30  gamemisc  [none] */
undefined FUN_006a9d30(void);

/* 006a9d80  gamemisc  [none] */
undefined FUN_006a9d80(void);

/* 006a9e10  gamemisc  [none] */
undefined FUN_006a9e10(void);

/* 006a9f80  gamemisc  [none] */
undefined FUN_006a9f80(void);

/* 006aa050  gamemisc  [none] */
undefined FUN_006aa050(void);

/* 006aa1c0  gamemisc  [none] */
undefined FUN_006aa1c0(void);

/* 006aa2e0  gamemisc  [none] */
undefined FUN_006aa2e0(void);

/* 006aa3e0  gamemisc  [none] */
undefined FUN_006aa3e0(void);

/* 006abbc0  gamemisc  [none] */
undefined FUN_006abbc0(void);

/* 006abd50  gamemisc  [none] */
undefined FUN_006abd50(void);

/* 006abf20  gamemisc  [none] */
undefined FUN_006abf20(void);

/* 006ac580  gamemisc  [none] */
undefined FUN_006ac580(void);

/* 006ac770  gamemisc  [none] */
undefined FUN_006ac770(void);

/* 006ac800  gamemisc  [none] */
undefined FUN_006ac800(void);

/* 006ac880  gamemisc  [none] */
undefined FUN_006ac880(void);

/* 006ac8a0  gamemisc  [none] */
undefined FUN_006ac8a0(void);

/* 006ac920  gamemisc  [none] */
undefined FUN_006ac920(void);

/* 006acc20  gamemisc  [none] */
undefined FUN_006acc20(void);

/* 006acde0  gamemisc  [none] */
undefined FUN_006acde0(void);

/* 006acfc0  gamemisc  [none] */
undefined FUN_006acfc0(void);

/* 006ad220  gamemisc  [none] */
undefined FUN_006ad220(void);

/* 006ad370  gamemisc  [none] */
undefined FUN_006ad370(void);

/* 006ad550  gamemisc  [none] */
undefined FUN_006ad550(void);

/* 006ad990  gamemisc  [none] */
undefined FUN_006ad990(void);

/* 006adfd0  gamemisc  [none] */
undefined FUN_006adfd0(void);

/* 006ae030  gamemisc  [none] */
undefined FUN_006ae030(void);

/* 006af480  gamemisc  [none] */
undefined FUN_006af480(void);

/* 006b00f0  gamemisc  [none] */
undefined FUN_006b00f0(void);

/* 006b0170  gamemisc  [none] */
undefined FUN_006b0170(void);

/* 006b0500  gamemisc  [none] */
undefined FUN_006b0500(void);

/* 006b0a80  gamemisc  [none] */
undefined FUN_006b0a80(void);

/* 006b0b20  gamemisc  [none] */
undefined FUN_006b0b20(void);

/* 006b0b50  gamemisc  [none] */
undefined FUN_006b0b50(void);

/* 006b1050  gamemisc  [none] */
undefined FUN_006b1050(void);

/* 006b1190  gamemisc  [none] */
undefined FUN_006b1190(void);

/* 006b16c0  gamemisc  [none] */
undefined FUN_006b16c0(void);

