// BlueprintPreviewWidget (ui) -- cube. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0042f5e0  game  [rtti] */
BlueprintPreviewWidget * __thiscall vfunction1_for_NamedObject(BlueprintPreviewWidget * this, byte param_1);

/* 0042f910  game  [rtti] */
undefined __thiscall deleting_destructor_for_NamedObject(BlueprintPreviewWidget * this);

/* 004348f0  game  [rtti] */
void __thiscall vfunction11_for_NamedObject(BlueprintPreviewWidget * this);

