// MapOverlayWidget (ui) -- cube. 1 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004c9680  game  [rtti] */
void __thiscall scalar_deleting_destructor(MapOverlayWidget * this);

