// OptionsWidget (ui) -- cube. 2 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004d0230  game  [rtti] */
void __thiscall deleting_destructor_for_NamedObject(OptionsWidget * this);

/* 004d46d0  game  [rtti] */
void __thiscall vfunction11_for_NamedObject(void);

