// PreviewWidget (ui) -- cube. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004d5010  game  [rtti] */
void __thiscall ~PreviewWidget(PreviewWidget * this);

/* 004d5070  game  [rtti] */
PreviewWidget * __thiscall deleting_destructor_for_NamedObject(PreviewWidget * this, byte param_1);

/* 004d50a0  game  [rtti] */
void __thiscall deleting_destructor_for_NamedObject(PreviewWidget * this);

