// Sprite (entity) -- server. 2 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0042ebb0  game  [rtti] */
Sprite * __thiscall Sprite(Sprite * this, undefined4 param_1);

/* 0042ef80  game  [rtti] */
undefined4 * __thiscall scalar_deleting_destructor(Sprite * this, byte param_1);

