// artifacts_00 (game_misc) -- server. 66 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0041ff9a  gamemisc  [role:artifact] */
undefined __fastcall FUN_0041ff9a(undefined4 param_1, int param_2);

/* 004240ea  gamemisc  [role:artifact] */
undefined __fastcall FUN_004240ea(int param_1);

/* 00428aca  gamemisc  [role:artifact] */
undefined __stdcall FUN_00428aca(void);

/* 0045fce0  gamemisc  [role:artifact] */
undefined __cdecl FUN_0045fce0(undefined4 param_1, undefined4 param_2, int * param_3);

/* 0045fd90  gamemisc  [role:artifact] */
undefined __cdecl FUN_0045fd90(int param_1, undefined4 param_2, undefined4 * param_3);

/* 0045fee0  gamemisc  [role:artifact] */
undefined __cdecl FUN_0045fee0(int param_1, undefined4 param_2, int * param_3);

/* 00460010  gamemisc  [role:artifact] */
undefined __cdecl FUN_00460010(int param_1, undefined4 param_2, undefined4 * param_3);

/* 00460630  gamemisc  [role:artifact] */
undefined __cdecl FUN_00460630(int param_1, undefined4 param_2, undefined4 * param_3);

/* 00460810  gamemisc  [role:artifact] */
undefined __cdecl FUN_00460810(int param_1, undefined4 param_2, int * param_3);

/* 004609b0  gamemisc  [role:artifact] */
undefined __cdecl FUN_004609b0(int param_1, undefined4 param_2, undefined4 * param_3);

/* 00461530  gamemisc  [role:artifact] */
undefined __cdecl FUN_00461530(int param_1, int param_2, undefined4 * param_3);

/* 00461610  gamemisc  [role:artifact] */
undefined __cdecl FUN_00461610(int * param_1, int param_2, undefined4 * param_3);

/* 0046178a  gamemisc  [role:artifact] */
undefined __fastcall FUN_0046178a(int * param_1, int param_2);

/* 00461e80  gamemisc  [role:artifact] */
undefined __cdecl FUN_00461e80(int param_1, undefined4 param_2, undefined4 * param_3);

/* 00462330  gamemisc  [role:artifact] */
undefined __cdecl FUN_00462330(int param_1, int param_2, undefined4 * param_3);

/* 00462eb0  gamemisc  [role:artifact] */
undefined __cdecl FUN_00462eb0(void * param_1, int param_2, undefined4 * param_3);

/* 004662c0  gamemisc  [role:artifact] */
undefined __cdecl FUN_004662c0(int param_1, undefined4 param_2, undefined4 * param_3);

/* 004667da  gamemisc  [role:artifact] */
undefined __fastcall FUN_004667da(int param_1, int param_2);

/* 00466b60  gamemisc  [role:artifact] */
undefined __cdecl FUN_00466b60(int param_1, undefined4 param_2, undefined4 * param_3);

/* 00467060  gamemisc  [role:artifact] */
undefined __cdecl FUN_00467060(int param_1, undefined4 param_2, undefined4 * param_3);

/* 004672d0  gamemisc  [role:artifact] */
undefined __cdecl FUN_004672d0(int param_1, undefined4 param_2, undefined4 * param_3);

/* 00468460  gamemisc  [role:artifact] */
undefined __cdecl FUN_00468460(int param_1, undefined4 param_2, undefined4 * param_3);

/* 00468a90  gamemisc  [role:artifact] */
undefined __cdecl FUN_00468a90(int param_1, int param_2, int * param_3);

/* 004692f0  gamemisc  [role:artifact] */
undefined __cdecl FUN_004692f0(int param_1, int param_2, int * param_3);

/* 00469b10  gamemisc  [role:artifact] */
undefined __cdecl FUN_00469b10(int param_1, undefined4 param_2, undefined4 * param_3);

/* 0046a030  gamemisc  [role:artifact] */
undefined __cdecl FUN_0046a030(int param_1);

/* 0046a7c0  gamemisc  [role:artifact] */
undefined __cdecl FUN_0046a7c0(int param_1, undefined4 param_2, int * param_3);

/* 0046eada  gamemisc  [role:artifact] */
undefined __stdcall FUN_0046eada(void);

/* 0046f5da  gamemisc  [role:artifact] */
undefined __stdcall FUN_0046f5da(void);

/* 004700da  gamemisc  [role:artifact] */
undefined __stdcall FUN_004700da(void);

/* 004721aa  gamemisc  [role:artifact] */
undefined __stdcall FUN_004721aa(void);

/* 0047693a  gamemisc  [role:artifact] */
undefined4 __fastcall FUN_0047693a(int param_1, int param_2);

/* 00476c8a  gamemisc  [role:artifact] */
undefined __fastcall FUN_00476c8a(int param_1, int param_2);

/* 0047700a  gamemisc  [role:artifact] */
undefined4 __fastcall FUN_0047700a(undefined4 param_1);

/* 004816ca  gamemisc  [role:artifact] */
undefined __fastcall FUN_004816ca(undefined4 * param_1);

/* 00485faa  gamemisc  [role:artifact] */
undefined __stdcall FUN_00485faa(void);

/* 0048866a  gamemisc  [role:artifact] */
undefined __fastcall FUN_0048866a(int param_1);

/* 004886ea  gamemisc  [role:artifact] */
undefined __stdcall FUN_004886ea(void);

/* 0048935a  gamemisc  [role:artifact] */
undefined __stdcall FUN_0048935a(void);

/* 0048951a  gamemisc  [role:artifact] */
undefined4 __stdcall FUN_0048951a(void);

/* 00489a0a  gamemisc  [role:artifact] */
undefined __stdcall FUN_00489a0a(void);

/* 0048a3ba  gamemisc  [role:artifact] */
undefined4 __fastcall FUN_0048a3ba(undefined4 param_1, byte * param_2);

/* 0048be0a  gamemisc  [role:artifact] */
undefined __fastcall FUN_0048be0a(int param_1);

/* 0048be3a  gamemisc  [role:artifact] */
undefined __fastcall FUN_0048be3a(byte param_1);

/* 0048fb0a  gamemisc  [role:artifact] */
int __stdcall FUN_0048fb0a(void);

/* 00496e0a  gamemisc  [role:artifact] */
undefined __fastcall FUN_00496e0a(undefined4 * param_1);

/* 00499b6a  gamemisc  [role:artifact] */
int __fastcall FUN_00499b6a(undefined4 param_1, byte * param_2);

/* 00499c9a  gamemisc  [role:artifact] */
int __fastcall FUN_00499c9a(undefined4 param_1, byte * param_2);

/* 0049a9aa  gamemisc  [role:artifact] */
undefined __stdcall FUN_0049a9aa(void);

/* 0049d5fa  gamemisc  [role:artifact] */
undefined __stdcall FUN_0049d5fa(void);

/* 0049fbea  gamemisc  [role:artifact] */
undefined __stdcall FUN_0049fbea(void);

/* 004a2cfa  gamemisc  [role:artifact] */
undefined4 __fastcall FUN_004a2cfa(int param_1);

/* 004a2f1a  gamemisc  [role:artifact] */
undefined4 __fastcall FUN_004a2f1a(int param_1, int param_2);

/* 004a6caa  gamemisc  [role:artifact] */
undefined __fastcall FUN_004a6caa(undefined4 param_1, undefined4 param_2);

/* 004aac4a  gamemisc  [role:artifact] */
undefined4 __fastcall FUN_004aac4a(int param_1);

/* 004bb5da  gamemisc  [role:artifact] */
undefined4 * __fastcall FUN_004bb5da(int param_1, uint param_2);

/* 004bec7a  gamemisc  [role:artifact] */
uint __stdcall FUN_004bec7a(void);

/* 004bedfa  gamemisc  [role:artifact] */
uint __stdcall FUN_004bedfa(void);

/* 004bf0fa  gamemisc  [role:artifact] */
undefined4 __stdcall FUN_004bf0fa(void);

/* 004c166a  gamemisc  [role:artifact] */
undefined __fastcall FUN_004c166a(int param_1, int param_2);

/* 004cd99a  gamemisc  [role:artifact] */
undefined __stdcall FUN_004cd99a(void);

/* 004d863a  gamemisc  [role:artifact] */
undefined __thiscall FUN_004d863a(void * this, undefined4 param_1, undefined4 param_2, char * param_3);

/* 004dcdca  gamemisc  [role:artifact] */
undefined __fastcall FUN_004dcdca(int param_1, int param_2);

/* 004dd9da  gamemisc  [role:artifact] */
undefined __fastcall FUN_004dd9da(int param_1, uint param_2);

/* 004e310a  gamemisc  [role:artifact] */
undefined __stdcall FUN_004e310a(void);

/* 004eaa7a  gamemisc  [role:artifact] */
undefined __fastcall FUN_004eaa7a(int param_1);

