// Game (game_misc) -- server. 24 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004013d0  gamemisc  [ledger]  ~getElemPtr4 */
int __thiscall FUN_004013d0(void * this, int param_1);

/* 00402bb0  gamemisc  [ledger]  ~int_vector_at */
int __thiscall FUN_00402bb0(void * this, int param_1);

/* 004061f0  gamemisc  [ledger]  ~Block_isSolid */
undefined4 __fastcall FUN_004061f0(int param_1);

/* 00413420  gamemisc  [ledger]  ~resize_dword_array */
undefined __thiscall FUN_00413420(void * this, uint param_1, int param_2);

/* 0041fff0  gamemisc  [ledger]  ~int_vector_size */
int __fastcall FUN_0041fff0(int * param_1);

/* 004d23f0  game  [ledger]  ~checked cell read -- GAME */
undefined * __thiscall FUN_004d23f0(void * this, int param_1);

/* 004d83a0  game  [ledger]  ~seedInit */
undefined __thiscall FUN_004d83a0(void * this, uint param_1, int * param_2);

/* 004e28d0  gamemisc  [ledger]  ~int_vector_empty */
bool __fastcall FUN_004e28d0(int * param_1);

/* 004f3630  game  [ledger]  ~unproven ctor -- GAME */
int * __cdecl FUN_004f3630(int * param_1, int * param_2, int param_3);

/* 004f5cc0  gamemisc  [ledger]  ~sort_routine_4f5cc0 */
undefined __cdecl FUN_004f5cc0(float * param_1, float * param_2, int param_3, undefined4 param_4);

/* 004f7490  game  [ledger]  ~StructureMarker_ctor */
undefined4 * __fastcall FUN_004f7490(undefined4 * param_1);

/* 004f7540  gamemisc  [ledger]  ~SpeciesGroup_ctor */
undefined4 * __fastcall FUN_004f7540(undefined4 * param_1);

/* 004f84a0  game  [ledger]  ~grid_cell_accessor -- GAME */
undefined1 * __thiscall FUN_004f84a0(void * this, int param_1, int param_2, int param_3);

/* 005104e0  game  [ledger]  ~camp_populator */
undefined __thiscall FUN_005104e0(void * this, int param_1, uint * param_2, int * param_3);

/* 0051210a  game  [ledger]  ~camp_populator__split_51210a */
undefined __stdcall FUN_0051210a(void);

/* 00522cc0  game  [ledger]  ~dist2_16_16 */
undefined __stdcall FUN_00522cc0(void);

/* 00523380  gamemisc  [ledger]  ~pointSegmentDistanceSq */
float10 __cdecl FUN_00523380(double * param_1, double * param_2, double * param_3);

/* 005284a0  gamemisc  [ledger]  ~StructureMarker_push_back */
undefined __thiscall FUN_005284a0(void * this, undefined4 * param_1);

/* 005285c0  gamemisc  [ledger]  ~SpeciesGroup_push_back */
undefined __thiscall FUN_005285c0(void * this, int * param_1);

/* 005286a0  gamemisc  [ledger]  ~UNRESOLVED_5286a0 */
undefined __thiscall FUN_005286a0(void * this, undefined4 * param_1);

/* 0052bf40  game  [ledger]  ~rarityRoll */
int __stdcall FUN_0052bf40(int param_1, char param_2);

/* 0052dde0  game  [ledger]  ~grid_orient_transform */
undefined __thiscall FUN_0052dde0(void * this, int * param_1, int * param_2);

/* 0054a910  game  [ledger]  ~ftol_helper */
ulonglong __fastcall FUN_0054a910(undefined4 param_1, undefined4 param_2);

/* 0054a946  gamemisc  [ledger]  ~ftol2_round */
ulonglong __stdcall FUN_0054a946(void);

