// helpers_accessor (game_misc) -- server. 15 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00406250  gamemisc  [role:accessor]  ~get_0x1c_406250 */
undefined4 __fastcall FUN_00406250(int param_1);

/* 0041cae0  gamemisc  [role:accessor]  ~get_0x80015c_41cae0 */
undefined4 __fastcall FUN_0041cae0(int param_1);

/* 00428780  gamemisc  [role:accessor]  ~get_4_428780 */
undefined4 __fastcall FUN_00428780(int param_1);

/* 0045f370  gamemisc  [role:accessor]  ~get_0x1e_45f370 */
undefined1 __cdecl FUN_0045f370(int param_1);

/* 0045f860  gamemisc  [role:accessor]  ~get_8_45f860 */
undefined4 __cdecl FUN_0045f860(int param_1);

/* 004607e0  gamemisc  [role:accessor]  ~get_0x36_4607e0 */
undefined1 __cdecl FUN_004607e0(int param_1);

/* 00465200  gamemisc  [role:accessor]  ~get_0xc_465200 */
undefined4 __cdecl FUN_00465200(int param_1);

/* 00465c40  gamemisc  [role:accessor]  ~get_0x20_465c40 */
undefined8 __cdecl FUN_00465c40(int param_1);

/* 00465c50  gamemisc  [role:accessor]  ~get_0x48_465c50 */
undefined4 __cdecl FUN_00465c50(int param_1);

/* 00465c60  gamemisc  [role:accessor]  ~get_0x4c_465c60 */
undefined4 __cdecl FUN_00465c60(int param_1);

/* 00467ec0  gamemisc  [role:accessor]  ~get_0x20_467ec0 */
undefined4 __cdecl FUN_00467ec0(int param_1);

/* 00467f40  gamemisc  [role:accessor]  ~get_0x24_467f40 */
undefined4 __cdecl FUN_00467f40(int param_1);

/* 004ce1f0  gamemisc  [role:accessor]  ~deref_get_4ce1f0 */
undefined4 __fastcall FUN_004ce1f0(undefined4 * param_1);

/* 004d8e00  gamemisc  [role:accessor]  ~get_0x6c_4d8e00 */
undefined4 __fastcall FUN_004d8e00(int param_1);

/* 0052d860  gamemisc  [role:accessor]  ~get_0x14_52d860 */
undefined4 __fastcall FUN_0052d860(int param_1);

