// helpers_dtor_like (game_misc) -- server. 46 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00405570  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_00405570(void * this, ushort param_1, char param_2);

/* 004129d0  gamemisc  [role:dtor-like] */
int * __thiscall FUN_004129d0(void * this, int * param_1);

/* 00412c70  gamemisc  [role:dtor-like] */
undefined __fastcall FUN_00412c70(int * param_1);

/* 00412d90  gamemisc  [role:dtor-like] */
undefined __fastcall FUN_00412d90(int * param_1);

/* 0041a090  gamemisc  [role:dtor-like] */
undefined __stdcall FUN_0041a090(int * param_1);

/* 0041a120  gamemisc  [role:dtor-like] */
undefined __stdcall FUN_0041a120(int * param_1);

/* 0041ba90  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_0041ba90(void * this, uint param_1);

/* 0041d390  gamemisc  [role:dtor-like] */
undefined4 * __cdecl FUN_0041d390(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 0041e450  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_0041e450(void * this, uint param_1);

/* 0041e540  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_0041e540(void * this, uint param_1);

/* 0041e640  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_0041e640(void * this, uint param_1);

/* 0041e740  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_0041e740(void * this, uint param_1);

/* 00423770  gamemisc  [role:dtor-like] */
undefined __fastcall FUN_00423770(int param_1);

/* 00426c20  gamemisc  [role:dtor-like] */
undefined __stdcall FUN_00426c20(void * param_1);

/* 00426db0  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_00426db0(void * this, uint param_1);

/* 00426f60  gamemisc  [role:dtor-like] */
undefined __fastcall FUN_00426f60(int * param_1);

/* 00428080  gamemisc  [role:dtor-like] */
undefined __fastcall FUN_00428080(int * param_1);

/* 0042af50  gamemisc  [role:dtor-like] */
facet * __cdecl FUN_0042af50(locale * param_1);

/* 0042c2e0  gamemisc  [role:dtor-like] */
undefined __fastcall FUN_0042c2e0(undefined4 * param_1);

/* 0042c350  gamemisc  [role:dtor-like] */
undefined __fastcall FUN_0042c350(undefined4 * param_1);

/* 0042c410  gamemisc  [role:dtor-like] */
undefined __fastcall FUN_0042c410(undefined4 * param_1);

/* 0042d060  gamemisc  [role:dtor-like] */
undefined __stdcall FUN_0042d060(void * param_1);

/* 0042d4c0  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_0042d4c0(void * this, int * param_1);

/* 0042e000  gamemisc  [role:dtor-like] */
int * __thiscall FUN_0042e000(void * this, int * param_1, int * param_2, int * param_3);

/* 0042eee0  gamemisc  [role:dtor-like] */
ios_base * __thiscall FUN_0042eee0(void * this, byte param_1);

/* 0042ef30  gamemisc  [role:dtor-like] */
ios_base * __thiscall FUN_0042ef30(void * this, byte param_1);

/* 00430ec0  gamemisc  [role:dtor-like] */
undefined __fastcall FUN_00430ec0(int param_1);

/* 00469960  gamemisc  [role:dtor-like] */
undefined __cdecl FUN_00469960(int param_1, undefined4 param_2, undefined4 * param_3);

/* 004c24b0  gamemisc  [role:dtor-like] */
undefined __cdecl FUN_004c24b0(int param_1, byte param_2, uint * param_3);

/* 004ce3e0  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_004ce3e0(void * this);

/* 004ce480  gamemisc  [role:dtor-like] */
ios_base * __thiscall FUN_004ce480(void * this, byte param_1);

/* 004ce720  gamemisc  [role:dtor-like] */
undefined __stdcall FUN_004ce720(int * param_1);

/* 004ce7e0  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_004ce7e0(void * this, uint param_1);

/* 004dab90  gamemisc  [role:dtor-like] */
int * __thiscall FUN_004dab90(void * this, int * param_1);

/* 004dcff0  gamemisc  [role:dtor-like] */
bool __thiscall FUN_004dcff0(void * this, undefined4 * param_1, int param_2, int param_3);

/* 004dd0f0  gamemisc  [role:dtor-like] */
undefined4 * __thiscall FUN_004dd0f0(void * this, undefined4 * param_1, int param_2, int param_3);

/* 004e1280  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_004e1280(void * this, uint param_1);

/* 004e2400  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_004e2400(void * this, uint param_1);

/* 004e2500  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_004e2500(void * this, uint param_1);

/* 004f7270  gamemisc  [role:dtor-like] */
undefined __stdcall FUN_004f7270(undefined4 * param_1);

/* 004f7d00  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_004f7d00(void * this, uint param_1);

/* 004f7fe0  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_004f7fe0(void * this, uint param_1);

/* 0052ea70  gamemisc  [role:dtor-like] */
int * __thiscall FUN_0052ea70(void * this, int * param_1);

/* 0052eda0  gamemisc  [role:dtor-like] */
undefined __thiscall FUN_0052eda0(void * this, uint param_1);

/* 0054a6ec  gamemisc  [role:dtor-like] */
undefined __stdcall FUN_0054a6ec(void);

/* 0054b700  gamemisc  [role:dtor-like] */
BOOL __cdecl __IsNonwritableInCurrentImage(PBYTE pTarget);

