// indirect_dispatch_target_02 (game_misc) -- server. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0053778c  gamemisc  [role:dispatch-target] */
undefined __stdcall FUN_0053778c(void);

/* 00537cef  gamemisc  [role:dispatch-target] */
undefined FUN_00537cef(void);

/* 00537f28  gamemisc  [role:dispatch-target] */
undefined FUN_00537f28(void);

