// indirect_dispatch_target_03 (game_misc) -- server. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00537fb4  gamemisc  [role:dispatch-target] */
undefined __fastcall FUN_00537fb4(undefined4 param_1, int param_2);

/* 0053ad3c  gamemisc  [role:dispatch-target] */
undefined FUN_0053ad3c(void);

/* 0053ae68  gamemisc  [role:dispatch-target] */
undefined FUN_0053ae68(void);

