// Unsorted_001 (game_misc) -- server. 150 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00418b60  gamemisc  [none] */
undefined __thiscall FUN_00418b60(void * this, int * param_1);

/* 00418bd0  gamemisc  [none] */
undefined __thiscall FUN_00418bd0(void * this, undefined4 * param_1);

/* 00418ea0  gamemisc  [none] */
undefined __thiscall FUN_00418ea0(void * this, int * param_1, uint * param_2, uint param_3, undefined4 param_4);

/* 00419210  gamemisc  [none] */
undefined __thiscall FUN_00419210(void * this, int * param_1, uint * param_2, uint param_3, short param_4);

/* 00419ac0  gamemisc  [none] */
ushort * __cdecl FUN_00419ac0(ushort * param_1, short param_2);

/* 00419ba0  gamemisc  [none] */
ushort * __cdecl FUN_00419ba0(ushort * param_1, short param_2);

/* 00419c90  gamemisc  [none] */
ushort * __cdecl FUN_00419c90(ushort * param_1, void * param_2);

/* 0041a030  gamemisc  [none] */
undefined __stdcall FUN_0041a030(void);

/* 0041a5d0  gamemisc  [none] */
undefined4 * __thiscall FUN_0041a5d0(void * this, int * param_1);

/* 0041a670  gamemisc  [none] */
undefined __thiscall FUN_0041a670(void * this, int * param_1, undefined4 param_2);

/* 0041a6f0  gamemisc  [none] */
undefined4 * __thiscall FUN_0041a6f0(void * this, undefined4 * param_1, undefined4 param_2, undefined4 param_3);

/* 0041a7b0  gamemisc  [none] */
undefined __thiscall FUN_0041a7b0(void * this, undefined4 * param_1, char param_2, undefined4 * param_3, int * param_4);

/* 0041a9b0  gamemisc  [none] */
undefined __thiscall FUN_0041a9b0(void * this, undefined4 * param_1, undefined4 * param_2, ushort * param_3, undefined4 param_4);

/* 0041ab00  gamemisc  [none] */
undefined __thiscall FUN_0041ab00(void * this, int * param_1, int * param_2);

/* 0041af30  gamemisc  [none] */
undefined4 * __fastcall FUN_0041af30(undefined4 * param_1);

/* 0041af70  gamemisc  [none] */
undefined __thiscall FUN_0041af70(void * this, uint param_1);

/* 0041b000  gamemisc  [none] */
undefined2 __cdecl FUN_0041b000(short param_1);

/* 0041b050  gamemisc  [none] */
undefined __thiscall FUN_0041b050(void * this, undefined4 * param_1);

/* 0041b930  gamemisc  [none] */
undefined4 * __cdecl FUN_0041b930(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 0041bb80  gamemisc  [none] */
undefined __thiscall FUN_0041bb80(void * this, uint param_1);

/* 0041c9e0  gamemisc  [none] */
int __thiscall FUN_0041c9e0(void * this, uint param_1, uint param_2, int param_3);

/* 0041d160  gamemisc  [none] */
int __thiscall FUN_0041d160(void * this, int param_1);

/* 0041d190  gamemisc  [none] */
void * __cdecl FUN_0041d190(int param_1, int param_2, void * param_3);

/* 0041d240  gamemisc  [none] */
void * __cdecl FUN_0041d240(int * param_1, int * param_2, void * param_3);

/* 0041d270  gamemisc  [none] */
undefined4 __cdecl FUN_0041d270(void * param_1, void * param_2, char * param_3);

/* 0041d340  gamemisc  [none] */
undefined4 * __cdecl FUN_0041d340(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 0041d410  gamemisc  [none] */
undefined4 * __cdecl FUN_0041d410(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 0041d460  gamemisc  [none] */
void * __cdecl FUN_0041d460(int * param_1, int * param_2, void * param_3);

/* 0041d500  gamemisc  [none] */
undefined4 * __cdecl FUN_0041d500(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 0041d550  gamemisc  [none] */
undefined __cdecl FUN_0041d550(int param_1, int param_2);

/* 0041d600  gamemisc  [none] */
undefined4 * __cdecl FUN_0041d600(undefined1 * param_1, undefined1 * param_2, undefined4 * param_3);

/* 0041d680  gamemisc  [none] */
void * __cdecl FUN_0041d680(undefined1 * param_1, undefined1 * param_2, void * param_3);

/* 0041d6c0  gamemisc  [none] */
undefined __cdecl FUN_0041d6c0(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 0041d950  gamemisc  [none] */
int * __thiscall FUN_0041d950(void * this, int * param_1);

/* 0041dae0  gamemisc  [none] */
int * __thiscall FUN_0041dae0(void * this, int * param_1);

/* 0041dc60  gamemisc  [none] */
int * __thiscall FUN_0041dc60(void * this, int * param_1);

/* 0041de30  gamemisc  [none] */
void * __thiscall FUN_0041de30(void * this, undefined1 * param_1);

/* 0041df70  gamemisc  [none] */
undefined4 * __thiscall FUN_0041df70(void * this, undefined4 * param_1);

/* 0041e300  gamemisc  [none] */
undefined __thiscall FUN_0041e300(void * this, int * param_1);

/* 0041e320  gamemisc  [none] */
uint __thiscall FUN_0041e320(void * this, uint param_1);

/* 0041e390  gamemisc  [none] */
uint __thiscall FUN_0041e390(void * this, uint param_1);

/* 0041e400  gamemisc  [none] */
uint __thiscall FUN_0041e400(void * this, uint param_1);

/* 0041e840  gamemisc  [none] */
undefined __thiscall FUN_0041e840(void * this, uint param_1);

/* 0041e8f0  gamemisc  [none] */
int __thiscall FUN_0041e8f0(void * this, uint param_1);

/* 0041eab0  gamemisc  [none] */
uint __cdecl FUN_0041eab0(byte * param_1, byte * param_2, uint param_3);

/* 0041ee20  gamemisc  [none] */
undefined __thiscall FUN_0041ee20(void * this, void * param_1, int param_2);

/* 0041f4d0  gamemisc  [none] */
undefined __thiscall FUN_0041f4d0(void * this, undefined4 * param_1);

/* 0041f640  gamemisc  [none] */
undefined4 * __thiscall FUN_0041f640(void * this, uint param_1);

/* 0041faa0  gamemisc  [none] */
undefined __thiscall FUN_0041faa0(void * this, int param_1);

/* 00420200  gamemisc  [none] */
int __stdcall FUN_00420200(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 00420540  gamemisc  [none] */
undefined4 * __thiscall FUN_00420540(void * this, undefined4 * param_1, undefined4 param_2, undefined4 param_3);

/* 00420600  gamemisc  [none] */
undefined __thiscall FUN_00420600(void * this, undefined4 * param_1, char param_2, undefined4 * param_3, undefined4 param_4, int * param_5);

/* 00420810  gamemisc  [none] */
undefined4 * __thiscall FUN_00420810(void * this, undefined4 * param_1, int * param_2, uint * param_3, int * param_4);

/* 00420a60  gamemisc  [none] */
undefined __thiscall FUN_00420a60(void * this, undefined4 * param_1, char param_2, uint * param_3, int * param_4);

/* 004213d0  gamemisc  [none] */
undefined __thiscall FUN_004213d0(void * this, undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 004214a0  gamemisc  [none] */
undefined __thiscall FUN_004214a0(void * this, undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 00421980  gamemisc  [none] */
void * __cdecl FUN_00421980(undefined4 * param_1, undefined4 * param_2, void * param_3);

/* 004219c0  gamemisc  [none] */
undefined __cdecl FUN_004219c0(int * param_1, int * param_2);

/* 00421a30  gamemisc  [none] */
undefined __cdecl FUN_00421a30(int * param_1, int * param_2);

/* 00421aa0  gamemisc  [none] */
undefined __cdecl FUN_00421aa0(int * param_1, int * param_2);

/* 00421b10  gamemisc  [none] */
undefined __cdecl FUN_00421b10(int * param_1, int * param_2);

/* 00421b80  gamemisc  [none] */
undefined __cdecl FUN_00421b80(int * param_1, int * param_2);

/* 00421bf0  gamemisc  [none] */
undefined __cdecl FUN_00421bf0(int * param_1, int * param_2);

/* 00421c60  gamemisc  [none] */
undefined __cdecl FUN_00421c60(int * param_1, int * param_2);

/* 00421ce0  gamemisc  [none] */
undefined __cdecl FUN_00421ce0(int * param_1, int * param_2);

/* 00421d50  gamemisc  [none] */
undefined __cdecl FUN_00421d50(int * param_1, int * param_2);

/* 00421dc0  gamemisc  [none] */
undefined __cdecl FUN_00421dc0(int * param_1, int * param_2);

/* 00422b10  gamemisc  [none] */
void * __thiscall FUN_00422b10(void * this, undefined1 * param_1);

/* 00422c00  gamemisc  [none] */
undefined4 * __thiscall FUN_00422c00(void * this, int param_1);

/* 00422f90  gamemisc  [none] */
undefined4 * __thiscall FUN_00422f90(void * this, undefined4 * param_1);

/* 00423350  gamemisc  [none] */
undefined4 * __thiscall FUN_00423350(void * this, undefined4 * param_1);

/* 00423400  gamemisc  [none] */
void * __thiscall FUN_00423400(void * this, undefined4 * param_1);

/* 004239f0  gamemisc  [none] */
undefined __fastcall FUN_004239f0(int * param_1);

/* 00423c90  gamemisc  [none] */
undefined4 * __thiscall FUN_00423c90(void * this, undefined4 * param_1);

/* 00423ce0  gamemisc  [none] */
undefined __thiscall FUN_00423ce0(void * this, uint * param_1);

/* 00423dd0  gamemisc  [none] */
undefined __fastcall FUN_00423dd0(int * param_1);

/* 004254a0  gamemisc  [none] */
undefined __thiscall FUN_004254a0(void * this);

/* 00426020  gamemisc  [none] */
undefined __fastcall FUN_00426020(int * param_1);

/* 004267b0  gamemisc  [none] */
undefined __stdcall FUN_004267b0(void);

/* 00426a70  gamemisc  [none] */
undefined4 * __fastcall FUN_00426a70(undefined4 * param_1);

/* 00426b80  gamemisc  [none] */
undefined __thiscall FUN_00426b80(void * this, int * param_1, uint * param_2);

/* 00428160  gamemisc  [none] */
int __fastcall FUN_00428160(int * param_1);

/* 00428290  gamemisc  [none] */
undefined1 __fastcall FUN_00428290(char * param_1);

/* 004282d0  gamemisc  [none] */
undefined1 __fastcall FUN_004282d0(char * param_1);

/* 004282f0  gamemisc  [none] */
undefined4 __stdcall FUN_004282f0(undefined1 * param_1);

/* 00428630  gamemisc  [none] */
undefined __thiscall FUN_00428630(void * this, undefined4 * param_1);

/* 004286b0  gamemisc  [none] */
int __cdecl FUN_004286b0(SOCKET param_1, char * param_2, int param_3, int param_4);

/* 00429060  gamemisc  [none] */
undefined __stdcall FUN_00429060(void);

/* 004290d0  gamemisc  [none] */
undefined4 * __thiscall FUN_004290d0(void * this, int * param_1);

/* 004291a0  gamemisc  [none] */
int __stdcall FUN_004291a0(undefined4 * param_1, undefined4 * param_2, int * param_3);

/* 00429280  gamemisc  [none] */
undefined4 * __thiscall FUN_00429280(void * this, undefined4 * param_1);

/* 00429380  gamemisc  [none] */
undefined4 * __thiscall FUN_00429380(void * this, undefined4 * param_1);

/* 00429430  gamemisc  [none] */
undefined __thiscall FUN_00429430(void * this, int * param_1, undefined4 param_2);

/* 004294b0  gamemisc  [none] */
undefined4 * __thiscall FUN_004294b0(void * this, undefined4 * param_1, undefined4 param_2, undefined4 param_3);

/* 004297a0  gamemisc  [none] */
undefined __thiscall FUN_004297a0(void * this, undefined4 * param_1, char param_2, undefined4 * param_3, undefined4 param_4, int * param_5);

/* 004299b0  gamemisc  [none] */
undefined __thiscall FUN_004299b0(void * this, undefined4 * param_1, char param_2, undefined4 * param_3, undefined4 param_4, int * param_5);

/* 00429bc0  gamemisc  [none] */
undefined __thiscall FUN_00429bc0(void * this, undefined4 * param_1, char param_2, undefined4 * param_3, undefined4 param_4, int * param_5);

/* 0042a260  gamemisc  [none] */
undefined4 * __thiscall FUN_0042a260(void * this, undefined4 * param_1, ushort * param_2, ushort * param_3, int * param_4);

/* 0042a450  gamemisc  [none] */
undefined4 * __thiscall FUN_0042a450(void * this, undefined4 * param_1, ushort * param_2, ushort * param_3, int * param_4);

/* 0042a640  gamemisc  [none] */
undefined4 * __thiscall FUN_0042a640(void * this, undefined4 * param_1, ushort * param_2, ushort * param_3, int * param_4);

/* 0042a970  gamemisc  [none] */
undefined __thiscall FUN_0042a970(void * this, undefined4 * param_1, undefined4 * param_2, ushort * param_3, int * param_4);

/* 0042aae0  gamemisc  [none] */
undefined __thiscall FUN_0042aae0(void * this, undefined4 * param_1, undefined4 * param_2, ushort * param_3, int * param_4);

/* 0042ac40  gamemisc  [none] */
undefined __thiscall FUN_0042ac40(void * this, undefined4 * param_1, undefined4 * param_2, ushort * param_3, int * param_4);

/* 0042ada0  gamemisc  [none] */
undefined __thiscall FUN_0042ada0(void * this, undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 0042ae70  gamemisc  [none] */
undefined __thiscall FUN_0042ae70(void * this, undefined4 * param_1, undefined4 * param_2);

/* 0042c820  gamemisc  [none] */
undefined __thiscall FUN_0042c820(void * this, ushort * param_1);

/* 0042c9a0  gamemisc  [none] */
undefined __thiscall FUN_0042c9a0(void * this, ushort * param_1);

/* 0042cad0  gamemisc  [none] */
undefined __thiscall FUN_0042cad0(void * this, ushort * param_1);

/* 0042ced0  gamemisc  [none] */
undefined __stdcall FUN_0042ced0(void);

/* 0042cf40  gamemisc  [none] */
undefined4 * __fastcall FUN_0042cf40(undefined4 * param_1);

/* 0042cf80  gamemisc  [none] */
undefined4 * __fastcall FUN_0042cf80(undefined4 * param_1);

/* 0042d300  gamemisc  [none] */
undefined __thiscall FUN_0042d300(void * this, void * param_1, uint param_2, undefined4 param_3);

/* 0042d420  gamemisc  [none] */
int __cdecl FUN_0042d420(int param_1);

/* 0042d440  gamemisc  [none] */
int * __cdecl FUN_0042d440(int * param_1);

/* 0042d460  gamemisc  [none] */
undefined __thiscall FUN_0042d460(void * this, int * param_1);

/* 0042e220  gamemisc  [none] */
undefined4 __thiscall FUN_0042e220(void * this, int param_1, int param_2);

/* 0042e880  gamemisc  [none] */
int __thiscall FUN_0042e880(void * this, uint param_1, uint param_2);

/* 0042feb0  gamemisc  [none] */
undefined __thiscall FUN_0042feb0(void * this, undefined4 * param_1);

/* 0045f160  gamemisc  [none] */
float10 __cdecl FUN_0045f160(int param_1);

/* 0045f1d0  gamemisc  [none] */
undefined4 __cdecl FUN_0045f1d0(int param_1);

/* 0045fad0  gamemisc  [none] */
undefined __cdecl FUN_0045fad0(int param_1);

/* 0045ff40  gamemisc  [none] */
undefined __cdecl FUN_0045ff40(int param_1, int param_2);

/* 00461320  gamemisc  [none] */
undefined8 __cdecl FUN_00461320(uint param_1, int param_2);

/* 00461bb0  gamemisc  [none] */
undefined __cdecl FUN_00461bb0(int param_1, int param_2, undefined4 * param_3);

/* 00461d80  gamemisc  [none] */
undefined __cdecl FUN_00461d80(int param_1, int param_2, undefined4 * param_3);

/* 00462070  gamemisc  [none] */
undefined4 __cdecl FUN_00462070(undefined8 * param_1);

/* 00462150  gamemisc  [none] */
undefined __cdecl FUN_00462150(int param_1, int param_2, undefined4 * param_3);

/* 00464130  gamemisc  [none] */
uint __cdecl FUN_00464130(int param_1, byte * param_2, int param_3);

/* 00465070  gamemisc  [none] */
undefined4 __cdecl FUN_00465070(int param_1);

/* 00465c90  gamemisc  [none] */
bool __cdecl FUN_00465c90(byte * param_1);

/* 00466390  gamemisc  [none] */
undefined4 __cdecl FUN_00466390(int param_1, uint param_2, int param_3);

/* 004665f0  gamemisc  [none] */
undefined __cdecl FUN_004665f0(int param_1);

/* 00466f30  gamemisc  [none] */
undefined4 __cdecl FUN_00466f30(int param_1, int * param_2);

/* 00468750  gamemisc  [none] */
uint __cdecl FUN_00468750(int param_1, byte * param_2);

/* 00469290  gamemisc  [none] */
int __cdecl FUN_00469290(int * param_1, int param_2, int param_3, int param_4);

/* 00469710  gamemisc  [none] */
int __cdecl FUN_00469710(int * param_1, int param_2, int param_3);

/* 0046a100  gamemisc  [none] */
undefined __cdecl FUN_0046a100(undefined4 param_1, char * param_2, undefined8 * param_3, uint param_4, int * param_5);

/* 0046a520  gamemisc  [none] */
undefined __cdecl FUN_0046a520(undefined4 param_1, undefined4 param_2);

/* 0046b0e0  gamemisc  [none] */
uint __cdecl FUN_0046b0e0(int param_1, byte * param_2, int param_3, uint param_4, int param_5, int param_6, int param_7, int param_8, undefined * param_9);

/* 0046b260  gamemisc  [none] */
int __cdecl FUN_0046b260(int * param_1);

/* 0046b2b0  gamemisc  [none] */
int __cdecl FUN_0046b2b0(int * param_1);

/* 0046bab0  gamemisc  [none] */
bool __cdecl FUN_0046bab0(int param_1, int param_2);

/* 0046f880  gamemisc  [none] */
undefined __cdecl FUN_0046f880(int * param_1);

/* 0046f990  gamemisc  [none] */
undefined __cdecl FUN_0046f990(int * param_1);

/* 00470300  gamemisc  [none] */
undefined __cdecl FUN_00470300(int * param_1);

/* 00470360  gamemisc  [none] */
undefined __cdecl FUN_00470360(int * param_1);

/* 004706c0  gamemisc  [none] */
undefined __cdecl FUN_004706c0(int * param_1);

/* 00470aa0  gamemisc  [none] */
uint __cdecl FUN_00470aa0(int param_1, undefined4 param_2, int param_3, int param_4, undefined * param_5);

/* 00472ef0  gamemisc  [none] */
int __cdecl FUN_00472ef0(int * param_1, undefined4 * param_2, undefined4 * param_3, uint param_4, uint param_5, int param_6, undefined4 * param_7);

/* 004731c0  gamemisc  [none] */
undefined __cdecl FUN_004731c0(int param_1, int param_2, size_t param_3, int * param_4);

