// Unsorted_007_00 (game_misc) -- server. 17 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004f7d00  gamemisc  [none] */
undefined __thiscall FUN_004f7d00(void * this, uint param_1);

/* 004f7fe0  gamemisc  [none] */
undefined __thiscall FUN_004f7fe0(void * this, uint param_1);

/* 004f80d0  gamemisc  [none] */
undefined __thiscall FUN_004f80d0(void * this, uint param_1);

/* 004f8230  gamemisc  [none] */
undefined __thiscall FUN_004f8230(void * this, uint param_1);

/* 004fc060  gamemisc  [none] */
undefined4 * __thiscall FUN_004fc060(void * this, undefined4 * param_1, int * param_2, int * param_3);

/* 004fc100  gamemisc  [none] */
float10 __thiscall FUN_004fc100(void * param_1, float param_2, uint param_3, int param_4);

/* 004feec0  gamemisc  [none] */
undefined __thiscall FUN_004feec0(void * this, int param_1, int param_2);

/* 004ff1a0  gamemisc  [none] */
undefined __cdecl FUN_004ff1a0(int param_1, uint * param_2, uint param_3, int param_4, int param_5, int param_6, int param_7);

/* 004ff59a  gamemisc  [none] */
undefined __stdcall FUN_004ff59a(void);

/* 00501e0a  gamemisc  [none] */
undefined __stdcall FUN_00501e0a(void);

/* 00502a7a  gamemisc  [none] */
undefined __fastcall FUN_00502a7a(int param_1, int param_2);

/* 00502dca  gamemisc  [none] */
undefined __stdcall FUN_00502dca(void);

/* 0050529a  gamemisc  [none] */
undefined __stdcall FUN_0050529a(void);

/* 005053ca  gamemisc  [none] */
undefined __stdcall FUN_005053ca(void);

/* 005054fa  gamemisc  [none] */
undefined __stdcall FUN_005054fa(void);

/* 0050702a  gamemisc  [none] */
undefined __stdcall FUN_0050702a(void);

/* 0050998a  gamemisc  [none] */
undefined __stdcall FUN_0050998a(void);

