// Unsorted_007 (game_misc) -- server. 150 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0048f740  gamemisc  [none] */
char * __cdecl FUN_0048f740(undefined4 * param_1, undefined4 * param_2, byte param_3);

/* 0048f790  gamemisc  [none] */
undefined4 __cdecl FUN_0048f790(undefined4 * param_1, int param_2, int param_3, int param_4, int * param_5);

/* 0048f7e0  gamemisc  [none] */
int __cdecl FUN_0048f7e0(int * param_1, undefined4 * param_2);

/* 0048f870  gamemisc  [none] */
uint __cdecl FUN_0048f870(int * param_1, uint param_2, size_t param_3, void * param_4);

/* 0048f8b0  gamemisc  [none] */
int __cdecl FUN_0048f8b0(int param_1, uint * param_2);

/* 0048f8d0  gamemisc  [none] */
undefined4 __cdecl FUN_0048f8d0(int param_1, undefined4 * param_2);

/* 0048f930  gamemisc  [none] */
uint __cdecl FUN_0048f930(uint * param_1);

/* 0048fb0a  gamemisc  [none] */
int __stdcall FUN_0048fb0a(void);

/* 0048fb70  gamemisc  [none] */
uint __cdecl FUN_0048fb70(undefined4 * param_1, char * param_2, uint * param_3);

/* 0048fdc0  gamemisc  [none] */
undefined __cdecl FUN_0048fdc0(int * param_1, undefined4 * param_2);

/* 0048fe00  gamemisc  [none] */
char __cdecl FUN_0048fe00(undefined4 * param_1);

/* 0048fe50  gamemisc  [none] */
undefined1 * __cdecl FUN_0048fe50(int param_1);

/* 0048fe70  gamemisc  [none] */
undefined __cdecl FUN_0048fe70(undefined4 * param_1, int param_2, undefined4 * param_3);

/* 0048fee0  gamemisc  [none] */
int __cdecl FUN_0048fee0(undefined4 * param_1);

/* 0048ff20  gamemisc  [none] */
uint __cdecl FUN_0048ff20(undefined4 * param_1);

/* 0048ffe0  gamemisc  [none] */
uint * __cdecl FUN_0048ffe0(uint * param_1, byte * param_2, uint param_3, uint param_4, void * param_5, size_t param_6, size_t param_7, int param_8, uint * param_9);

/* 004901e0  gamemisc  [none] */
undefined __cdecl FUN_004901e0(undefined4 * param_1, int param_2, int param_3, int param_4, int * param_5);

/* 00490640  gamemisc  [none] */
int __cdecl FUN_00490640(int param_1, uint * param_2);

/* 004906b0  gamemisc  [none] */
undefined4 __cdecl FUN_004906b0(int param_1, undefined4 * param_2);

/* 004906f0  gamemisc  [none] */
int __cdecl FUN_004906f0(int * param_1, undefined4 * param_2);

/* 00490750  gamemisc  [none] */
undefined __cdecl FUN_00490750(int param_1);

/* 00490780  gamemisc  [none] */
undefined __cdecl FUN_00490780(int param_1);

/* 004907e0  gamemisc  [none] */
undefined __cdecl FUN_004907e0(int * param_1);

/* 00490810  gamemisc  [none] */
int __cdecl FUN_00490810(undefined8 * param_1, int param_2, char param_3);

/* 00490880  gamemisc  [none] */
undefined4 __cdecl FUN_00490880(undefined4 * param_1, int param_2);

/* 004908e0  gamemisc  [none] */
uint __cdecl FUN_004908e0(int * param_1, int * param_2, uint param_3, int param_4, int param_5, uint * param_6);

/* 00490c90  gamemisc  [none] */
int __cdecl FUN_00490c90(int * param_1, undefined4 * param_2);

/* 00490e00  gamemisc  [none] */
undefined __cdecl FUN_00490e00(undefined * param_1, byte * param_2, int param_3, undefined4 * param_4, byte param_5, uint param_6);

/* 00491450  gamemisc  [none] */
int __cdecl FUN_00491450(int * param_1, undefined4 * param_2);

/* 00491620  gamemisc  [none] */
uint __cdecl FUN_00491620(int * param_1, uint param_2, size_t param_3, void * param_4);

/* 00491910  gamemisc  [none] */
uint __cdecl FUN_00491910(undefined4 * param_1, int param_2, int param_3);

/* 004919c0  gamemisc  [none] */
undefined4 __cdecl FUN_004919c0(undefined4 * param_1);

/* 00491a40  gamemisc  [none] */
ushort __cdecl FUN_00491a40(undefined4 * param_1, int param_2);

/* 00491ab0  gamemisc  [none] */
undefined4 __cdecl FUN_00491ab0(undefined4 * param_1, char param_2);

/* 00491b30  gamemisc  [none] */
undefined4 __cdecl FUN_00491b30(undefined4 * param_1, uint param_2);

/* 00491bc0  gamemisc  [none] */
undefined __cdecl FUN_00491bc0(int param_1, undefined4 param_2, undefined4 param_3);

/* 00491c00  gamemisc  [none] */
int __cdecl FUN_00491c00(undefined4 * param_1, uint param_2, uint param_3, int param_4);

/* 00491ce0  gamemisc  [none] */
undefined4 __cdecl FUN_00491ce0(undefined4 * param_1, int param_2, int param_3, int param_4);

/* 00491d30  gamemisc  [none] */
uint __cdecl FUN_00491d30(int * param_1, int param_2);

/* 00491f10  gamemisc  [none] */
undefined1 __cdecl FUN_00491f10(undefined4 * param_1);

/* 00492040  gamemisc  [none] */
uint __cdecl FUN_00492040(undefined4 * param_1, int param_2, undefined4 param_3);

/* 004920e0  gamemisc  [none] */
undefined4 __stdcall FUN_004920e0(void);

/* 00492110  gamemisc  [none] */
undefined __cdecl FUN_00492110(int * param_1, int param_2);

/* 00492280  gamemisc  [none] */
int __cdecl FUN_00492280(int param_1, int param_2, int param_3, undefined4 * param_4, undefined4 * param_5);

/* 00492650  gamemisc  [none] */
undefined __cdecl FUN_00492650(int * param_1);

/* 004927e0  gamemisc  [none] */
int __cdecl FUN_004927e0(int * param_1, int * param_2, byte * param_3);

/* 00492ce0  gamemisc  [none] */
int __cdecl FUN_00492ce0(int * param_1);

/* 00492d70  gamemisc  [none] */
undefined __cdecl FUN_00492d70(int * param_1, int * param_2, uint param_3, int * param_4, uint param_5, undefined4 param_6, undefined4 param_7, undefined4 param_8, undefined4 param_9);

/* 00492dd0  gamemisc  [none] */
undefined __cdecl FUN_00492dd0(int * param_1, int * param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6);

/* 00492f00  gamemisc  [none] */
undefined __cdecl FUN_00492f00(int * param_1, char * param_2, int param_3, int param_4);

/* 00493360  gamemisc  [none] */
undefined __cdecl FUN_00493360(int * param_1, byte * param_2);

/* 00493400  gamemisc  [none] */
undefined __cdecl FUN_00493400(int * param_1, int param_2);

/* 00493630  gamemisc  [none] */
undefined __cdecl FUN_00493630(int * param_1, int * param_2, int param_3, int param_4);

/* 00493750  gamemisc  [none] */
int __cdecl FUN_00493750(char * param_1, char param_2);

/* 00493790  gamemisc  [none] */
undefined __cdecl FUN_00493790(int * param_1, undefined4 * param_2, int param_3, int param_4, int param_5, int param_6, int param_7, int param_8);

/* 00493af0  gamemisc  [none] */
undefined4 __stdcall FUN_00493af0(void);

/* 00493b20  gamemisc  [none] */
undefined4 * __cdecl FUN_00493b20(int param_1, int param_2, int param_3, uint param_4);

/* 00493f20  gamemisc  [none] */
int __cdecl FUN_00493f20(int param_1, byte * param_2, int param_3, uint param_4, undefined4 param_5, int param_6, int param_7, int param_8, int * param_9);

/* 00494960  gamemisc  [none] */
undefined __cdecl FUN_00494960(int * param_1, int * param_2, undefined4 * param_3, int param_4, undefined4 * param_5, int param_6, int param_7);

/* 00494b00  gamemisc  [none] */
undefined __cdecl FUN_00494b00(int param_1, undefined4 * param_2);

/* 00494c20  gamemisc  [none] */
undefined4 * __cdecl FUN_00494c20(int param_1, size_t param_2);

/* 00494c50  gamemisc  [none] */
undefined4 __cdecl FUN_00494c50(int param_1, byte * param_2);

/* 00494db0  gamemisc  [none] */
undefined4 * __cdecl FUN_00494db0(int param_1, char * param_2);

/* 00494e00  gamemisc  [none] */
undefined4 * __cdecl FUN_00494e00(int param_1, void * param_2, size_t param_3);

/* 00494e40  gamemisc  [none] */
undefined __cdecl FUN_00494e40(int param_1);

/* 00494ea0  gamemisc  [none] */
undefined __cdecl FUN_00494ea0(int param_1, undefined1 param_2);

/* 00494ec0  gamemisc  [none] */
undefined __cdecl FUN_00494ec0(int * param_1, short * param_2, byte * param_3);

/* 00495540  gamemisc  [none] */
int __cdecl FUN_00495540(char * param_1);

/* 00495a40  gamemisc  [none] */
undefined __cdecl FUN_00495a40(int * param_1, short * param_2, int param_3);

/* 004961f0  gamemisc  [none] */
undefined __cdecl FUN_004961f0(int param_1, undefined4 param_2, byte * param_3);

/* 004962b0  gamemisc  [none] */
undefined __cdecl FUN_004962b0(int * param_1, byte * param_2);

/* 00496370  gamemisc  [none] */
undefined __cdecl FUN_00496370(int param_1);

/* 00496390  gamemisc  [none] */
undefined __cdecl FUN_00496390(int param_1, int param_2, char * param_3);

/* 004963e0  gamemisc  [none] */
undefined4 * __cdecl FUN_004963e0(int * param_1, undefined4 * param_2, char * param_3);

/* 00496440  gamemisc  [none] */
undefined4 * __cdecl FUN_00496440(int * param_1, undefined4 * param_2, undefined4 * param_3);

/* 00496480  gamemisc  [none] */
char __cdecl FUN_00496480(char * param_1);

/* 00496510  gamemisc  [none] */
undefined4 * __cdecl FUN_00496510(int param_1, int param_2, undefined4 * param_3, int param_4);

/* 00496610  gamemisc  [none] */
undefined __cdecl FUN_00496610(undefined4 param_1, int * param_2);

/* 00496680  gamemisc  [none] */
undefined __cdecl FUN_00496680(undefined4 param_1, int param_2);

/* 004966d0  gamemisc  [none] */
char * __cdecl FUN_004966d0(int param_1, char * param_2, char * param_3);

/* 004967a0  gamemisc  [none] */
undefined __cdecl FUN_004967a0(int * param_1, int param_2);

/* 00496a30  gamemisc  [none] */
undefined __cdecl FUN_00496a30(int param_1, int param_2, undefined4 * param_3, undefined4 * param_4);

/* 00496a90  gamemisc  [none] */
undefined __cdecl FUN_00496a90(int param_1);

/* 00496ca0  gamemisc  [none] */
undefined __cdecl FUN_00496ca0(int param_1, int param_2);

/* 00496d40  gamemisc  [none] */
undefined __cdecl FUN_00496d40(int param_1, int param_2);

/* 00496d90  gamemisc  [none] */
undefined __cdecl FUN_00496d90(int param_1, int param_2, int param_3);

/* 00496df0  gamemisc  [none] */
undefined __cdecl FUN_00496df0(int * param_1, int param_2, int param_3, int param_4);

/* 00496e0a  gamemisc  [none] */
undefined __fastcall FUN_00496e0a(undefined4 * param_1);

/* 00496f30  gamemisc  [none] */
int __cdecl FUN_00496f30(int * param_1, byte * param_2, int param_3);

/* 00496f90  gamemisc  [none] */
int __cdecl FUN_00496f90(int * param_1, byte * param_2, int param_3);

/* 00497010  gamemisc  [none] */
int __cdecl FUN_00497010(int param_1, int * param_2, int param_3, int param_4);

/* 004970c0  gamemisc  [none] */
int __cdecl FUN_004970c0(int * param_1, int * param_2, int param_3, int param_4, int param_5, char param_6);

/* 00497170  gamemisc  [none] */
undefined __cdecl FUN_00497170(int * param_1, int * param_2, undefined4 param_3, int param_4, int param_5);

/* 00497220  gamemisc  [none] */
undefined __cdecl FUN_00497220(int * param_1, char * param_2, int param_3, int param_4);

/* 004975c0  gamemisc  [none] */
undefined __cdecl FUN_004975c0(int * param_1, byte * param_2, undefined4 param_3, undefined4 param_4);

/* 00497600  gamemisc  [none] */
undefined __cdecl FUN_00497600(int param_1, int param_2, int param_3, int param_4);

/* 00498470  gamemisc  [none] */
int __cdecl FUN_00498470(int param_1, undefined4 param_2, int * param_3);

/* 004984d0  gamemisc  [none] */
uint __cdecl FUN_004984d0(int * param_1, char * param_2);

/* 00498610  gamemisc  [none] */
char __cdecl FUN_00498610(char * param_1, char * param_2);

/* 00498830  gamemisc  [none] */
undefined4 * __cdecl FUN_00498830(int * param_1, int * param_2, undefined4 * param_3);

/* 004988a0  gamemisc  [none] */
undefined __cdecl FUN_004988a0(int * param_1, char * param_2, int param_3, uint param_4);

/* 00498b60  gamemisc  [none] */
undefined __cdecl FUN_00498b60(int * param_1, byte * param_2, int param_3, uint param_4);

/* 00498e10  gamemisc  [none] */
undefined4 __cdecl FUN_00498e10(int param_1);

/* 00498e50  gamemisc  [none] */
undefined4 __cdecl FUN_00498e50(int param_1);

/* 00498e90  gamemisc  [none] */
undefined4 __cdecl FUN_00498e90(char * param_1, int * param_2);

/* 00498f00  gamemisc  [none] */
uint * __cdecl FUN_00498f00(int * param_1, uint * param_2, undefined4 * param_3);

/* 00498fb0  gamemisc  [none] */
undefined __cdecl FUN_00498fb0(int * param_1, int * param_2);

/* 00498fe0  gamemisc  [none] */
undefined4 __cdecl FUN_00498fe0(int * param_1, int * param_2);

/* 00499140  gamemisc  [none] */
int * __cdecl FUN_00499140(int param_1, int * param_2, uint param_3);

/* 004992e0  gamemisc  [none] */
undefined __cdecl FUN_004992e0(int * param_1, int * param_2, undefined4 * param_3, int param_4);

/* 00499360  gamemisc  [none] */
undefined __cdecl FUN_00499360(int * param_1, int * param_2, int param_3);

/* 004993e0  gamemisc  [none] */
bool __cdecl FUN_004993e0(char * param_1, char param_2);

/* 004994a0  gamemisc  [none] */
undefined __cdecl FUN_004994a0(int * param_1, int param_2);

/* 004994d0  gamemisc  [none] */
undefined __cdecl FUN_004994d0(char * param_1);

/* 00499500  gamemisc  [none] */
int * __cdecl FUN_00499500(int param_1, byte param_2, byte * param_3, int param_4);

/* 00499540  gamemisc  [none] */
int __cdecl FUN_00499540(int param_1, byte * param_2);

/* 004995c0  gamemisc  [none] */
short * __cdecl FUN_004995c0(int param_1, byte * param_2, size_t param_3, int param_4, byte param_5, char param_6);

/* 004997b0  gamemisc  [none] */
int __cdecl FUN_004997b0(int * param_1, char * param_2, int * param_3);

/* 00499af0  gamemisc  [none] */
int __cdecl FUN_00499af0(int param_1, byte * param_2, byte * param_3);

/* 00499b6a  gamemisc  [none] */
int __fastcall FUN_00499b6a(undefined4 param_1, byte * param_2);

/* 00499c30  gamemisc  [none] */
int __cdecl FUN_00499c30(int param_1, byte * param_2, byte * param_3);

/* 00499c9a  gamemisc  [none] */
int __fastcall FUN_00499c9a(undefined4 param_1, byte * param_2);

/* 00499d70  gamemisc  [none] */
undefined __cdecl FUN_00499d70(int * param_1);

/* 0049a2b0  gamemisc  [none] */
undefined4 __cdecl FUN_0049a2b0(undefined4 param_1, int param_2);

/* 0049a350  gamemisc  [none] */
undefined4 __cdecl FUN_0049a350(undefined4 * param_1, int * param_2, int param_3, undefined4 param_4, undefined4 param_5);

/* 0049a3a0  gamemisc  [none] */
undefined4 __cdecl FUN_0049a3a0(undefined4 param_1, undefined4 * param_2);

/* 0049a430  gamemisc  [none] */
undefined4 __cdecl FUN_0049a430(undefined4 * param_1, short * param_2);

/* 0049a530  gamemisc  [none] */
undefined4 __cdecl FUN_0049a530(undefined4 param_1, int param_2);

/* 0049a5b0  gamemisc  [none] */
undefined __cdecl FUN_0049a5b0(int * param_1, undefined4 * param_2, int param_3, undefined4 param_4);

/* 0049a610  gamemisc  [none] */
undefined __cdecl FUN_0049a610(int * param_1, undefined4 * param_2, int param_3, int param_4);

/* 0049a9aa  gamemisc  [none] */
undefined __stdcall FUN_0049a9aa(void);

/* 0049ad30  gamemisc  [none] */
uint __cdecl FUN_0049ad30(int * param_1, undefined4 * param_2);

/* 0049ae70  gamemisc  [none] */
undefined4 __cdecl FUN_0049ae70(undefined4 * param_1);

/* 0049aed0  gamemisc  [none] */
undefined4 __cdecl FUN_0049aed0(int * param_1, undefined4 * param_2, int param_3, int param_4);

/* 0049b0f0  gamemisc  [none] */
undefined __cdecl FUN_0049b0f0(int param_1, int param_2);

/* 0049b170  gamemisc  [none] */
undefined4 __cdecl FUN_0049b170(int param_1, undefined4 param_2);

/* 0049b1e0  gamemisc  [none] */
undefined __cdecl FUN_0049b1e0(int * param_1, undefined4 * param_2, int param_3, int param_4, int param_5, int param_6, int param_7, int * param_8, undefined4 param_9, int * param_10);

/* 0049c270  gamemisc  [none] */
int __cdecl FUN_0049c270(int * param_1, int * param_2, undefined4 param_3, undefined4 param_4, int param_5);

/* 0049c510  gamemisc  [none] */
undefined __cdecl FUN_0049c510(int * param_1, int * param_2, int param_3, undefined4 param_4, int param_5, int * param_6, int param_7);

/* 0049c860  gamemisc  [none] */
undefined __cdecl FUN_0049c860(int * param_1, int param_2, int param_3, int * param_4);

/* 0049c920  gamemisc  [none] */
undefined4 __cdecl FUN_0049c920(undefined1 * param_1);

/* 0049c950  gamemisc  [none] */
bool __cdecl FUN_0049c950(byte * param_1, byte param_2);

/* 0049ca30  gamemisc  [none] */
undefined4 __cdecl FUN_0049ca30(char * param_1, uint * param_2);

/* 0049cb00  gamemisc  [none] */
int __cdecl FUN_0049cb00(int param_1, int param_2);

/* 0049cb40  gamemisc  [none] */
int __cdecl FUN_0049cb40(int param_1);

/* 0049cb70  gamemisc  [none] */
uint __cdecl FUN_0049cb70(byte * param_1, undefined4 * param_2);

/* 0049d250  gamemisc  [none] */
undefined __cdecl FUN_0049d250(int param_1, int param_2);

/* 0049d270  gamemisc  [none] */
undefined4 __cdecl FUN_0049d270(byte * param_1, uint * param_2);

/* 0049d440  gamemisc  [none] */
uint __cdecl FUN_0049d440(byte * param_1, uint * param_2);

/* 0049d4d0  gamemisc  [none] */
int * __cdecl FUN_0049d4d0(int * param_1);

