// Unsorted_004_00 (game_misc) -- server. 45 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004d8dc0  gamemisc  [none] */
undefined4 __fastcall FUN_004d8dc0(int param_1);

/* 004d8de0  gamemisc  [none] */
undefined4 __fastcall FUN_004d8de0(int param_1);

/* 004d8e10  gamemisc  [none] */
undefined __stdcall FUN_004d8e10(undefined4 * param_1, undefined4 * param_2);

/* 004d8e30  gamemisc  [none] */
float10 __fastcall FUN_004d8e30(double * param_1);

/* 004d9160  gamemisc  [none] */
undefined __thiscall FUN_004d9160(void * this, int param_1, int * param_2, uint param_3, uint param_4);

/* 004d9410  gamemisc  [none] */
undefined __thiscall FUN_004d9410(void * this, int * param_1, uint * param_2);

/* 004d9720  gamemisc  [none] */
float * __stdcall FUN_004d9720(float * param_1);

/* 004d99d0  gamemisc  [none] */
int * __thiscall FUN_004d99d0(void * this, uint * param_1);

/* 004d9a10  gamemisc  [none] */
undefined4 * __thiscall FUN_004d9a10(void * this, int * param_1);

/* 004d9b70  gamemisc  [none] */
int __stdcall FUN_004d9b70(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 004d9be0  gamemisc  [none] */
undefined __thiscall FUN_004d9be0(void * this, int * param_1, undefined4 param_2);

/* 004d9c60  gamemisc  [none] */
undefined4 * __thiscall FUN_004d9c60(void * this, undefined4 * param_1, undefined4 param_2, undefined4 param_3);

/* 004d9d20  gamemisc  [none] */
undefined4 * __thiscall FUN_004d9d20(void * this, undefined4 * param_1, undefined4 param_2, undefined4 param_3);

/* 004da9f0  gamemisc  [none] */
undefined __thiscall FUN_004da9f0(void * this, int * param_1, int * param_2);

/* 004db1b0  gamemisc  [none] */
undefined __thiscall FUN_004db1b0(void * this, int * param_1, uint * param_2);

/* 004db200  gamemisc  [none] */
undefined __stdcall FUN_004db200(void * param_1, int param_2);

/* 004dcdca  gamemisc  [none] */
undefined __fastcall FUN_004dcdca(int param_1, int param_2);

/* 004dd9da  gamemisc  [none] */
undefined __fastcall FUN_004dd9da(int param_1, uint param_2);

/* 004dde00  gamemisc  [none] */
undefined __thiscall FUN_004dde00(void * this, float * param_1, float * param_2);

/* 004e1230  gamemisc  [none] */
undefined4 * __cdecl FUN_004e1230(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 004e1370  gamemisc  [none] */
undefined __thiscall FUN_004e1370(void * this, uint param_1);

/* 004e1420  gamemisc  [none] */
undefined __thiscall FUN_004e1420(void * this, undefined4 * param_1);

/* 004e1520  gamemisc  [none] */
undefined __cdecl FUN_004e1520(float * param_1, float param_2, float * param_3);

/* 004e1560  gamemisc  [none] */
undefined __cdecl FUN_004e1560(int param_1, int param_2, int param_3, int * param_4, int * param_5);

/* 004e15f0  gamemisc  [none] */
undefined __cdecl FUN_004e15f0(int * param_1, int * param_2, int * param_3);

/* 004e16f0  gamemisc  [none] */
undefined __cdecl FUN_004e16f0(int param_1, int param_2, int * param_3);

/* 004e17c0  gamemisc  [none] */
undefined __cdecl FUN_004e17c0(int * param_1, int * param_2, int * param_3, int * param_4);

/* 004e1870  gamemisc  [none] */
undefined __cdecl FUN_004e1870(int * param_1, int * param_2, int * param_3, int * param_4);

/* 004e1910  gamemisc  [none] */
undefined __cdecl FUN_004e1910(undefined8 * param_1, undefined8 * param_2, undefined8 * param_3);

/* 004e1950  gamemisc  [none] */
undefined __cdecl FUN_004e1950(int param_1, int param_2, int param_3, int * param_4, int * param_5);

/* 004e1ae0  gamemisc  [none] */
undefined __cdecl FUN_004e1ae0(undefined4 * param_1, int param_2, int * param_3);

/* 004e1b40  gamemisc  [none] */
undefined __cdecl FUN_004e1b40(uint * param_1, int * param_2, int * param_3, int * param_4);

/* 004e1d70  gamemisc  [none] */
undefined __cdecl FUN_004e1d70(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 004e1db0  gamemisc  [none] */
undefined __cdecl FUN_004e1db0(int param_1, int param_2);

/* 004e1e00  gamemisc  [none] */
undefined __cdecl FUN_004e1e00(undefined8 * param_1, undefined8 * param_2, undefined8 * param_3);

/* 004e1e50  gamemisc  [none] */
undefined4 * __cdecl FUN_004e1e50(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 004e1e90  gamemisc  [none] */
undefined4 * __thiscall FUN_004e1e90(void * this, undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);

/* 004e1eb0  gamemisc  [none] */
undefined4 * __fastcall FUN_004e1eb0(undefined4 * param_1);

/* 004e2360  gamemisc  [none] */
int * __thiscall FUN_004e2360(void * this, int * param_1, int param_2);

/* 004e23b0  gamemisc  [none] */
uint __thiscall FUN_004e23b0(void * this, uint param_1);

/* 004e26c0  gamemisc  [none] */
int __thiscall FUN_004e26c0(void * this, uint param_1);

/* 004e2730  gamemisc  [none] */
undefined __thiscall FUN_004e2730(void * this, uint param_1);

/* 004e27b0  gamemisc  [none] */
undefined __thiscall FUN_004e27b0(void * this, uint param_1);

/* 004e310a  gamemisc  [none] */
undefined __stdcall FUN_004e310a(void);

/* 004eaa7a  gamemisc  [none] */
undefined __fastcall FUN_004eaa7a(int param_1);

