// Unsorted_006_01 (game_misc) -- server. 68 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004ee3aa  gamemisc  [none] */
undefined __stdcall FUN_004ee3aa(void);

/* 004f3820  gamemisc  [none] */
int __fastcall FUN_004f3820(int * param_1);

/* 004f3840  gamemisc  [none] */
int __fastcall FUN_004f3840(int * param_1);

/* 004f3850  gamemisc  [none] */
undefined8 __cdecl FUN_004f3850(uint param_1, uint param_2, uint param_3);

/* 004f3880  gamemisc  [none] */
uint * __thiscall FUN_004f3880(void * this, byte * param_1);

/* 004f38a0  gamemisc  [none] */
undefined __cdecl FUN_004f38a0(int param_1, int param_2, int param_3, float * param_4);

/* 004f3940  gamemisc  [none] */
undefined __cdecl FUN_004f3940(int param_1, int param_2, int param_3, undefined4 * param_4);

/* 004f3a80  gamemisc  [none] */
undefined __cdecl FUN_004f3a80(int param_1, int param_2, int param_3, undefined4 * param_4);

/* 004f3b20  gamemisc  [none] */
undefined4 * __thiscall FUN_004f3b20(void * this, undefined4 * param_1);

/* 004f3b60  gamemisc  [none] */
undefined4 * __thiscall FUN_004f3b60(void * this, undefined4 * param_1);

/* 004f3bf0  gamemisc  [none] */
undefined __cdecl FUN_004f3bf0(undefined4 * param_1, undefined4 * param_2);

/* 004f3c60  gamemisc  [none] */
undefined __thiscall FUN_004f3c60(void * this, undefined4 * param_1, char param_2, undefined4 * param_3, undefined4 param_4, int * param_5);

/* 004f4080  gamemisc  [none] */
undefined4 * __thiscall FUN_004f4080(void * this, undefined4 * param_1, int * param_2, int * param_3, int * param_4);

/* 004f42d0  gamemisc  [none] */
undefined4 * __thiscall FUN_004f42d0(void * this, undefined4 * param_1, int * param_2, int * param_3, int * param_4);

/* 004f4560  gamemisc  [none] */
undefined __thiscall FUN_004f4560(void * this, undefined4 * param_1, char param_2, int * param_3, int * param_4);

/* 004f46c0  gamemisc  [none] */
undefined __thiscall FUN_004f46c0(void * this, undefined4 * param_1, char param_2, int * param_3, int * param_4);

/* 004f4860  gamemisc  [none] */
undefined __cdecl FUN_004f4860(float * param_1, float * param_2);

/* 004f4940  gamemisc  [none] */
undefined __cdecl FUN_004f4940(undefined8 * param_1, undefined8 * param_2);

/* 004f4a5a  gamemisc  [none] */
undefined __fastcall FUN_004f4a5a(float * param_1, float * param_2);

/* 004f4ab0  gamemisc  [none] */
undefined __cdecl FUN_004f4ab0(undefined8 * param_1, undefined8 * param_2);

/* 004f4aea  gamemisc  [none] */
undefined __fastcall FUN_004f4aea(undefined8 * param_1, undefined8 * param_2);

/* 004f4b50  gamemisc  [none] */
undefined __cdecl FUN_004f4b50(int param_1, int param_2);

/* 004f4cb0  gamemisc  [none] */
undefined __cdecl FUN_004f4cb0(int param_1, int param_2);

/* 004f4f30  gamemisc  [none] */
undefined __cdecl FUN_004f4f30(int param_1, int param_2);

/* 004f5050  gamemisc  [none] */
undefined __cdecl FUN_004f5050(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 004f50e0  gamemisc  [none] */
undefined __cdecl FUN_004f50e0(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 004f5170  gamemisc  [none] */
undefined __cdecl FUN_004f5170(float * param_1, float * param_2, float * param_3);

/* 004f5500  gamemisc  [none] */
undefined __cdecl FUN_004f5500(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 004f5940  gamemisc  [none] */
undefined __cdecl FUN_004f5940(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 004f59f0  gamemisc  [none] */
undefined1 * __cdecl FUN_004f59f0(undefined4 * param_1, undefined4 * param_2, undefined1 * param_3);

/* 004f5ac0  gamemisc  [none] */
undefined __cdecl FUN_004f5ac0(int param_1, int param_2, int param_3, float * param_4);

/* 004f5b40  gamemisc  [none] */
undefined __cdecl FUN_004f5b40(int param_1, int param_2, int param_3, undefined4 * param_4);

/* 004f5c40  gamemisc  [none] */
undefined __cdecl FUN_004f5c40(int param_1, int param_2, int param_3, undefined4 * param_4);

/* 004f5e00  gamemisc  [none] */
undefined __cdecl FUN_004f5e00(int * param_1, int * param_2, int param_3, undefined4 param_4);

/* 004f6080  gamemisc  [none] */
undefined __cdecl FUN_004f6080(float * param_1, float * param_2, int param_3, undefined4 param_4);

/* 004f61c0  gamemisc  [none] */
undefined __cdecl FUN_004f61c0(undefined4 * param_1, int param_2);

/* 004f6280  gamemisc  [none] */
undefined __cdecl FUN_004f6280(undefined4 * param_1, undefined4 * param_2);

/* 004f63f0  gamemisc  [none] */
undefined __cdecl FUN_004f63f0(undefined4 * param_1, undefined4 * param_2);

/* 004f64a0  gamemisc  [none] */
undefined __cdecl FUN_004f64a0(undefined4 * param_1, float * param_2, float * param_3);

/* 004f654a  gamemisc  [none] */
undefined __fastcall FUN_004f654a(undefined4 param_1, float * param_2);

/* 004f67f0  gamemisc  [none] */
undefined __cdecl FUN_004f67f0(undefined4 * param_1, int * param_2, int * param_3);

/* 004f6b0a  gamemisc  [none] */
undefined __fastcall FUN_004f6b0a(undefined4 param_1, float * param_2);

/* 004f6db0  gamemisc  [none] */
undefined __cdecl FUN_004f6db0(undefined4 * param_1, float * param_2, float * param_3);

/* 004f70f0  gamemisc  [none] */
void * __cdecl FUN_004f70f0(undefined4 * param_1, undefined4 * param_2, void * param_3);

/* 004f7130  gamemisc  [none] */
void * __cdecl FUN_004f7130(int * param_1, int * param_2, void * param_3);

/* 004f71e0  gamemisc  [none] */
undefined4 * __cdecl FUN_004f71e0(int param_1, int param_2, undefined4 * param_3);

/* 004f7230  gamemisc  [none] */
undefined4 * __cdecl FUN_004f7230(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);

/* 004f7270  gamemisc  [none] */
undefined __stdcall FUN_004f7270(undefined4 * param_1);

/* 004f72d0  gamemisc  [none] */
undefined __cdecl FUN_004f72d0(undefined1 * param_1, undefined1 * param_2, undefined1 * param_3);

/* 004f72f0  gamemisc  [none] */
undefined __cdecl FUN_004f72f0(undefined1 * param_1, undefined1 * param_2, undefined1 * param_3);

/* 004f7310  gamemisc  [none] */
undefined4 * __fastcall FUN_004f7310(undefined4 * param_1);

/* 004f7330  gamemisc  [none] */
undefined4 * __fastcall FUN_004f7330(undefined4 * param_1);

/* 004f7350  gamemisc  [none] */
undefined __thiscall FUN_004f7350(void * this, undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);

/* 004f73ca  gamemisc  [none] */
undefined __fastcall FUN_004f73ca(undefined2 * param_1, int param_2);

/* 004f7400  gamemisc  [none] */
undefined4 * __thiscall FUN_004f7400(void * this, undefined4 * param_1);

/* 004f7490  gamemisc  [none] */
undefined4 * __fastcall FUN_004f7490(undefined4 * param_1);

/* 004f7540  gamemisc  [none] */
undefined4 * __fastcall FUN_004f7540(undefined4 * param_1);

/* 004f7710  gamemisc  [none] */
undefined __fastcall FUN_004f7710(undefined4 * param_1);

/* 004f7740  gamemisc  [none] */
undefined __fastcall FUN_004f7740(undefined4 * param_1);

/* 004f7890  gamemisc  [none] */
int * __thiscall FUN_004f7890(void * this, int * param_1);

/* 004f7910  gamemisc  [none] */
int * __thiscall FUN_004f7910(void * this, int * param_1);

/* 004f79b0  gamemisc  [none] */
int __thiscall FUN_004f79b0(void * this, int param_1);

/* 004f79d0  gamemisc  [none] */
undefined __thiscall FUN_004f79d0(void * this, int * param_1);

/* 004f7a30  gamemisc  [none] */
undefined __cdecl FUN_004f7a30(int * param_1, undefined4 param_2, uint * param_3);

/* 004f7a70  gamemisc  [none] */
undefined __thiscall FUN_004f7a70(void * this, float * param_1, float param_2);

/* 004f7ab0  gamemisc  [none] */
undefined4 __stdcall FUN_004f7ab0(int * param_1, int * param_2);

/* 004f7b60  gamemisc  [none] */
undefined __stdcall FUN_004f7b60(undefined4 * param_1, undefined4 * param_2);

/* 004f7ca0  gamemisc  [none] */
undefined4 * __thiscall FUN_004f7ca0(void * this, int * param_1);

