// Unsorted_013 (game_misc) -- server. 26 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 005571a0  gamemisc  [none] */
undefined __stdcall FUN_005571a0(void);

/* 005571d0  gamemisc  [none] */
undefined __stdcall FUN_005571d0(void);

/* 00557200  gamemisc  [none] */
undefined __stdcall FUN_00557200(void);

/* 00557230  gamemisc  [none] */
undefined __stdcall FUN_00557230(void);

/* 00557260  gamemisc  [none] */
undefined __stdcall FUN_00557260(void);

/* 00557290  gamemisc  [none] */
undefined __stdcall FUN_00557290(void);

/* 005572c0  gamemisc  [none] */
undefined __stdcall FUN_005572c0(void);

/* 005572f0  gamemisc  [none] */
undefined __stdcall FUN_005572f0(void);

/* 00557320  gamemisc  [none] */
undefined __stdcall FUN_00557320(void);

/* 00557350  gamemisc  [none] */
undefined __stdcall FUN_00557350(void);

/* 00557380  gamemisc  [none] */
undefined __stdcall FUN_00557380(void);

/* 005573b0  gamemisc  [none] */
undefined __stdcall FUN_005573b0(void);

/* 005573e0  gamemisc  [none] */
undefined __stdcall FUN_005573e0(void);

/* 00557410  gamemisc  [none] */
undefined __stdcall FUN_00557410(void);

/* 00557440  gamemisc  [none] */
undefined __stdcall FUN_00557440(void);

/* 00557470  gamemisc  [none] */
undefined __stdcall FUN_00557470(void);

/* 005574a0  gamemisc  [none] */
undefined __stdcall FUN_005574a0(void);

/* 005574d0  gamemisc  [none] */
undefined __stdcall FUN_005574d0(void);

/* 00557500  gamemisc  [none] */
undefined __stdcall FUN_00557500(void);

/* 00557530  gamemisc  [none] */
undefined __stdcall FUN_00557530(void);

/* 00557560  gamemisc  [none] */
undefined __stdcall FUN_00557560(void);

/* 00557590  gamemisc  [none] */
undefined __stdcall FUN_00557590(void);

/* 005575c0  gamemisc  [none] */
undefined __stdcall FUN_005575c0(void);

/* 005575f0  gamemisc  [none] */
undefined __stdcall FUN_005575f0(void);

/* 00557618  gamemisc  [none] */
undefined __stdcall FUN_00557618(void);

/* 0055765b  gamemisc  [none] */
undefined __stdcall FUN_0055765b(void);

