// Unsorted_007_07 (game_misc) -- server. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 0053afb9  gamemisc  [none] */
undefined __stdcall FUN_0053afb9(void);

/* 0053b973  gamemisc  [none] */
undefined FUN_0053b973(void);

/* 0053caf5  gamemisc  [none] */
undefined FUN_0053caf5(void);

