// helpers_dtor_like (ai) -- server. 4 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00405330  gamemisc  [role:dtor-like] */
undefined __fastcall FUN_00405330(int param_1);

/* 004dcff0  gamemisc  [role:dtor-like] */
bool __thiscall FUN_004dcff0(void * this, undefined4 * param_1, int param_2, int param_3);

/* 004dd0f0  gamemisc  [role:dtor-like] */
undefined4 * __thiscall FUN_004dd0f0(void * this, undefined4 * param_1, int param_2, int param_3);

/* 004f8520  gamemisc  [role:dtor-like] */
undefined __fastcall FUN_004f8520(int * param_1);

