// LookAtPlayerBehavior (ai) -- server. 3 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 00414720  game  [rtti] */
LookAtPlayerBehavior * __thiscall LookAtPlayerBehavior(LookAtPlayerBehavior * this);

/* 00414730  game  [rtti] */
void __thiscall vfunction1(LookAtPlayerBehavior * this, int param_1);

/* 004149c0  game  [rtti] */
undefined4 * __thiscall vfunction2(LookAtPlayerBehavior * this);

