// WalkPathBehavior (ai) -- server. 4 functions.
// Generated by tools/cw_decomp/tools/structure.py -- do not hand-edit.
#pragma once
#include "../include/cw_types.h"

/* 004c5d10  game  [rtti] */
WalkPathBehavior * __thiscall WalkPathBehavior(WalkPathBehavior * this, int param_1);

/* 004c5d50  game  [rtti] */
WalkPathBehavior * __thiscall WalkPathBehavior(WalkPathBehavior * this, undefined4 param_1);

/* 004c5e00  game  [rtti] */
void __thiscall vfunction1(WalkPathBehavior * this, void * param_1, void * param_2, int param_3);

/* 004c63e0  game  [rtti] */
undefined4 * __thiscall vfunction2(WalkPathBehavior * this);

